/// Build script for bloom-dex-factory.
///
/// Generates the 4-byte BLAKE3 selectors for the factory-internal methods
/// (feeTo / feeToSetter management) that are not in bloom-dex-abi's
/// generated selectors (those cover only the four public factory methods
/// listed in DEX spec §4.1).
///
/// The generated file is included via:
///   `include!(concat!(env!("OUT_DIR"), "/factory_selectors.rs"))`
///
/// Method strings follow the same convention as bloom-dex-abi (DEX spec §4.1):
///   - `factory.fee_to()`
///   - `factory.fee_to_setter()`
///   - `factory.set_fee_to(address)`
///   - `factory.set_fee_to_setter(address)`

use std::env;
use std::fs;
use std::path::Path;

fn selector(method: &str) -> [u8; 4] {
    let h = blake3::hash(method.as_bytes());
    let b = h.as_bytes();
    [b[0], b[1], b[2], b[3]]
}

fn arr_literal(s: [u8; 4]) -> String {
    format!("[0x{:02x}, 0x{:02x}, 0x{:02x}, 0x{:02x}]", s[0], s[1], s[2], s[3])
}

fn main() {
    let methods: &[(&str, &str)] = &[
        ("SEL_FEE_TO",             "factory.fee_to()"),
        ("SEL_FEE_TO_SETTER",      "factory.fee_to_setter()"),
        ("SEL_SET_FEE_TO",         "factory.set_fee_to(address)"),
        ("SEL_SET_FEE_TO_SETTER",  "factory.set_fee_to_setter(address)"),
    ];

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs — do not edit.\n");
    out.push_str("// Factory-internal selectors (first 4 bytes of blake3(method_string)).\n\n");

    for (name, method) in methods {
        let sel = selector(method);
        out.push_str(&format!(
            "/// Selector for `{method}`\n\
             pub const {name}: [u8; 4] = {lit};\n\n",
            method = method,
            name = name,
            lit = arr_literal(sel),
        ));
    }

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("factory_selectors.rs");
    fs::write(dest, out).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
}
