//! Typed cross-contract interfaces.
//!
//! Phase 1 ships only the marker trait. The `#[bloom::interface]` proc-macro
//! in Phase 5 expands trait declarations into selector tables, calldata
//! builders, and `ContractRef<I>` wrappers.

use crate::types::Address;
use core::marker::PhantomData;

/// Marker trait implemented by every type generated from a
/// `#[bloom::interface]` declaration. Carries the canonical ABI domain (the
/// prefix used inside selector signatures, e.g. `"erc20"`).
pub trait ContractInterface {
    const ABI_DOMAIN: &'static str;
}

/// Typed reference to a deployed contract that implements interface `I`.
///
/// Methods are generated by the `#[bloom::interface]` macro in Phase 5. The
/// runtime wrapper exists in Phase 1 so the macro has a stable type to
/// target.
#[derive(Clone, Copy)]
pub struct ContractRef<I: ContractInterface> {
    pub address: Address,
    _marker: PhantomData<I>,
}

impl<I: ContractInterface> ContractRef<I> {
    #[inline]
    pub const fn new(address: Address) -> Self {
        Self { address, _marker: PhantomData }
    }

    #[inline]
    pub const fn address(&self) -> &Address {
        &self.address
    }
}
