//! bloom-dex-wloom — Wrapped LOOM (wLOOM) petal for bloom-chain DEX.
//!
//! Mirrors WETH9 semantics: wraps native LOOM as an ERC-20 token.
//! Single global deployment per DEX; its address is baked into router init.
//!
//! ## Constants
//! - name    = "Wrapped LOOM"
//! - symbol  = "wLOOM"
//! - decimals = 18
//!
//! ## init
//! No parameters expected. Writes `total_supply = 0` to storage (idempotent
//! no-op, since unset slots default to zero — this just marks the petal as
//! deployed). Name/symbol/decimals are hardcoded constants; they do not need
//! to be stored.
//!
//! ## Storage layout (DEX spec §6.4)
//! All keys are 32-byte BLAKE3 digests:
//! - `K_TOTAL      = blake3("wloom.total_supply")`
//! - `K_BAL(a)     = blake3("wloom.balance:" || a)`           a = 32-byte address
//! - `K_ALLOW(o,s) = blake3("wloom.allowance:" || o || s)`   o,s = 32-byte addresses
//!
//! ## Events (DEX spec §11)
//! - `Transfer(from, to, value)` — ERC-20 mint/burn/transfer; topic0 is the
//!   4-byte blake3 prefix of `"Transfer(address,address,u256)"`.
//! - `Approval(owner, spender, value)`.
//! - `Deposit(dst, value)` — topic0 = blake3("Deposit(address,u256)")[..4],
//!   topic1 = dst (32B), data = value (32B).
//! - `Withdrawal(src, value)` — topic0 = blake3("Withdrawal(address,u256)")[..4],
//!   topic1 = src (32B), data = value (32B).
//!
//! Deposit also emits `Transfer(0x0, dst, value)` (mint signal).
//! Withdrawal also emits `Transfer(src, 0x0, value)` (burn signal).
//!
//! ## ABI
//!
//! The wLOOM-specific selectors (`wloom.deposit()`, `wloom.withdraw(u256)`)
//! are generated by the chain-owned `bloom_chain_abi::contract!` macro below.
//! ERC-20 selectors (name, symbol, decimals, total_supply, balance_of,
//! allowance, transfer, transfer_from, approve) keep their legacy
//! `bloom_dex_abi::selectors::ERC20_*` byte values and are hand-dispatched
//! before falling through to the macro-generated dispatcher — this preserves
//! byte-identical wire compatibility with the router and other DEX peers,
//! which still link against `bloom-dex-abi`.
//!
//! ## dispatch
//! `call` entry point:
//! - If `calldata.len() < 4` (empty or too-short, including bare value transfers),
//!   route to `deposit()` — the receive-LOOM fallback per DEX spec §7.
//! - Otherwise, hand-dispatch any matching ERC-20 selector against the
//!   `bloom-dex-abi` constants; if none match, defer to `wloom::dispatch`
//!   for `deposit` / `withdraw`.

#![cfg_attr(target_arch = "wasm32", no_std)]

extern crate alloc;

use alloc::vec::Vec;

use bloom_chain_abi::{DispatchError, U256, contract};
use bloom_dex_abi::{
    decode::{AbiError, Buf},
    selectors,
};
use bloom_petal_sdk::{crypto, log, msg, petal, state, LoomValue};

// ---------------------------------------------------------------------------
// Chain-owned ABI declaration
// ---------------------------------------------------------------------------
//
// Only the wLOOM-specific surface (`deposit` / `withdraw`) lives in the
// macro: those are the methods peers refer to as `wloom.<name>(...)` and
// whose selectors must equal `blake3("wloom.<sig>")[..4]`. The remaining
// ERC-20 surface is hand-dispatched against the legacy
// `bloom_dex_abi::selectors::ERC20_*` constants for wire compatibility.

contract! {
    contract Wloom {
        fn deposit();
        fn withdraw(amount: U256);
    }
}

// ---------------------------------------------------------------------------
// Storage key derivation
// ---------------------------------------------------------------------------

/// Storage key for `total_supply`.
fn k_total() -> [u8; 32] {
    crypto::blake3(b"wloom.total_supply")
}

/// Storage key for `balance_of(addr)`.
fn k_bal(addr: &[u8; 32]) -> [u8; 32] {
    let mut buf = Vec::with_capacity(14 + 32);
    buf.extend_from_slice(b"wloom.balance:");
    buf.extend_from_slice(addr);
    crypto::blake3(&buf)
}

/// Storage key for `allowance(owner, spender)`.
fn k_allow(owner: &[u8; 32], spender: &[u8; 32]) -> [u8; 32] {
    let mut buf = Vec::with_capacity(16 + 64);
    buf.extend_from_slice(b"wloom.allowance:");
    buf.extend_from_slice(owner);
    buf.extend_from_slice(spender);
    crypto::blake3(&buf)
}

// ---------------------------------------------------------------------------
// Storage helpers
// ---------------------------------------------------------------------------

fn read_u256(key: &[u8; 32]) -> U256 {
    match state::read(key) {
        Some(v) => U256(v),
        None => U256::ZERO,
    }
}

fn write_u256(key: &[u8; 32], v: U256) {
    state::write(key, &v.0);
}

// ---------------------------------------------------------------------------
// ABI decoder helpers (legacy ERC-20 hand-dispatch path)
// ---------------------------------------------------------------------------

fn parse<T>(res: Result<T, AbiError>, msg: &str) -> T {
    res.unwrap_or_else(|_| petal::revert(msg))
}

// ---------------------------------------------------------------------------
// ERC-20 metadata constants
// ---------------------------------------------------------------------------

/// Name "Wrapped LOOM" as a NUL-right-padded bytes32.
fn name_bytes32() -> [u8; 32] {
    let s = b"Wrapped LOOM";
    let mut b = [0u8; 32];
    b[..s.len()].copy_from_slice(s);
    b
}

/// Symbol "wLOOM" as a NUL-right-padded bytes32.
fn symbol_bytes32() -> [u8; 32] {
    let s = b"wLOOM";
    let mut b = [0u8; 32];
    b[..s.len()].copy_from_slice(s);
    b
}

/// Decimals = 18 in a 32-byte slot (low byte).
fn decimals_bytes32() -> [u8; 32] {
    let mut b = [0u8; 32];
    b[31] = 18;
    b
}

// ---------------------------------------------------------------------------
// Event topic helpers — 4-byte blake3 prefix of each event signature.
// ---------------------------------------------------------------------------

fn topic_transfer() -> [u8; 4] {
    let h = crypto::blake3(b"Transfer(address,address,u256)");
    [h[0], h[1], h[2], h[3]]
}

fn topic_approval() -> [u8; 4] {
    let h = crypto::blake3(b"Approval(address,address,u256)");
    [h[0], h[1], h[2], h[3]]
}

fn topic_deposit() -> [u8; 4] {
    let h = crypto::blake3(b"Deposit(address,u256)");
    [h[0], h[1], h[2], h[3]]
}

fn topic_withdrawal() -> [u8; 4] {
    let h = crypto::blake3(b"Withdrawal(address,u256)");
    [h[0], h[1], h[2], h[3]]
}

// ---------------------------------------------------------------------------
// Log helpers
// ---------------------------------------------------------------------------

/// Emit `Transfer(from, to, value)` — ERC-20 style, 1 topic, data = from||to||value.
fn emit_transfer(from: &[u8; 32], to: &[u8; 32], value: &[u8; 32]) {
    let mut data: Vec<u8> = Vec::with_capacity(96);
    data.extend_from_slice(from);
    data.extend_from_slice(to);
    data.extend_from_slice(value);
    log::emit(&[topic_transfer()], &data);
}

/// Emit `Approval(owner, spender, value)`.
fn emit_approval(owner: &[u8; 32], spender: &[u8; 32], value: &[u8; 32]) {
    let mut data: Vec<u8> = Vec::with_capacity(96);
    data.extend_from_slice(owner);
    data.extend_from_slice(spender);
    data.extend_from_slice(value);
    log::emit(&[topic_approval()], &data);
}

/// Emit `Deposit(dst, value)`.
///
/// Per DEX spec §11: topic0 = blake3("Deposit(address,u256)")[..4],
/// topic1 = dst (32B address as raw topic), data = value (32B).
///
/// The host `log.emit` expects `topic_count * 32` contiguous bytes at `topic_ptr`.
/// We build a 64-byte topic buffer manually: [topic0_padded_32 || dst_32].
fn emit_deposit(dst: &[u8; 32], value: &[u8; 32]) {
    let td = topic_deposit();
    let mut topics = [0u8; 64];
    topics[0..4].copy_from_slice(&td);
    // bytes 4..32 remain zero (left-zero-pad of the 4-byte prefix to 32 bytes)
    topics[32..64].copy_from_slice(dst);
    emit_raw_2topics(&topics, value);
}

/// Emit `Withdrawal(src, value)`.
fn emit_withdrawal(src: &[u8; 32], value: &[u8; 32]) {
    let tw = topic_withdrawal();
    let mut topics = [0u8; 64];
    topics[0..4].copy_from_slice(&tw);
    topics[32..64].copy_from_slice(src);
    emit_raw_2topics(&topics, value);
}

/// Emit a log entry with a pre-built 64-byte topics buffer (2 × 32-byte topics)
/// and 32-byte data, calling the `log.emit` host import directly.
fn emit_raw_2topics(topics_buf: &[u8; 64], data: &[u8; 32]) {
    use bloom_petal_sdk::imports;
    let result = unsafe {
        imports::log_emit(
            topics_buf.as_ptr() as i32,
            2, // topic_count = 2
            data.as_ptr() as i32,
            32,
        )
    };
    if result < 0 {
        petal::revert("wloom: log_emit failed");
    }
}

// ---------------------------------------------------------------------------
// Internal raw transfer (balance accounting, no events)
// ---------------------------------------------------------------------------

fn transfer_raw(from: &[u8; 32], to: &[u8; 32], amount: U256) {
    let from_bal = read_u256(&k_bal(from));
    let new_from = from_bal
        .checked_sub(amount)
        .unwrap_or_else(|| petal::revert("wloom: insufficient balance"));
    write_u256(&k_bal(from), new_from);

    let to_bal = read_u256(&k_bal(to));
    let new_to = to_bal
        .checked_add(amount)
        .unwrap_or_else(|| petal::revert("wloom: balance overflow"));
    write_u256(&k_bal(to), new_to);
}

// ---------------------------------------------------------------------------
// Legacy ERC-20 handlers — hand-dispatched against bloom_dex_abi selectors.
//
// These keep the byte-identical selector encoding used by the router and
// other DEX peers. Each handler diverges via petal::return_data / petal::revert.
// ---------------------------------------------------------------------------

fn handle_total_supply() {
    let ts = read_u256(&k_total());
    petal::return_data(&ts.0);
}

fn handle_balance_of(buf: &mut Buf) {
    let addr = parse(buf.read_address(), "wloom: bad address arg");
    let bal = read_u256(&k_bal(&addr));
    petal::return_data(&bal.0);
}

fn handle_allowance(buf: &mut Buf) {
    let owner = parse(buf.read_address(), "wloom: bad owner arg");
    let spender = parse(buf.read_address(), "wloom: bad spender arg");
    let allow = read_u256(&k_allow(&owner, &spender));
    petal::return_data(&allow.0);
}

fn handle_name() {
    petal::return_data(&name_bytes32());
}

fn handle_symbol() {
    petal::return_data(&symbol_bytes32());
}

fn handle_decimals() {
    petal::return_data(&decimals_bytes32());
}

fn handle_approve(buf: &mut Buf) {
    let spender = parse(buf.read_address(), "wloom: bad spender arg");
    let amount = parse(buf.read_u256(), "wloom: bad amount arg");
    let owner = msg::sender();
    let amount_u256 = U256(amount.0);
    write_u256(&k_allow(&owner, &spender), amount_u256);
    emit_approval(&owner, &spender, &amount.0);
    petal::return_data(&[1u8]);
}

fn handle_transfer(buf: &mut Buf) {
    let to = parse(buf.read_address(), "wloom: bad to arg");
    let amount = parse(buf.read_u256(), "wloom: bad amount arg");
    let from = msg::sender();
    transfer_raw(&from, &to, U256(amount.0));
    emit_transfer(&from, &to, &amount.0);
    petal::return_data(&[1u8]);
}

fn handle_transfer_from(buf: &mut Buf) {
    let from = parse(buf.read_address(), "wloom: bad from arg");
    let to = parse(buf.read_address(), "wloom: bad to arg");
    let amount = parse(buf.read_u256(), "wloom: bad amount arg");
    let spender = msg::sender();
    let amount_u256 = U256(amount.0);

    // Check and reduce allowance. U256::MAX = infinite (skip deduction).
    let allow_key = k_allow(&from, &spender);
    let allow = read_u256(&allow_key);
    if allow != U256([0xff; 32]) {
        let new_allow = allow
            .checked_sub(amount_u256)
            .unwrap_or_else(|| petal::revert("wloom: insufficient allowance"));
        write_u256(&allow_key, new_allow);
    }

    transfer_raw(&from, &to, amount_u256);
    emit_transfer(&from, &to, &amount.0);
    petal::return_data(&[1u8]);
}

// ---------------------------------------------------------------------------
// Handler — wloom.deposit() / wloom.withdraw(u256) via chain-ABI macro.
// ---------------------------------------------------------------------------

struct WloomHandler;

impl wloom::Handler for WloomHandler {
    /// `wloom.deposit()` — payable.
    ///
    /// Credits `msg.sender` with `msg.value` wLOOM and increments `total_supply`.
    /// Emits:
    /// - `Deposit(sender, value)` with sender as topic1, value as data.
    /// - `Transfer(0x0, sender, value)` — mint signal for ERC-20 indexers.
    ///
    /// If `msg.value == 0`, the function returns immediately without any storage
    /// writes or events (no-op zero deposit).
    fn deposit(&mut self) -> Result<(), &'static str> {
        let sender = msg::sender();
        let value = msg::value(); // LoomValue (u128 wrapper)
        let amount = U256::from_u128(value.to_u128());

        if !amount.is_zero() {
            // total_supply += amount
            let ts_key = k_total();
            let ts = read_u256(&ts_key);
            let new_ts = ts
                .checked_add(amount)
                .ok_or("wloom: total supply overflow")?;
            write_u256(&ts_key, new_ts);

            // balance_of(sender) += amount
            let bal_key = k_bal(&sender);
            let bal = read_u256(&bal_key);
            let new_bal = bal
                .checked_add(amount)
                .ok_or("wloom: balance overflow")?;
            write_u256(&bal_key, new_bal);

            // Emit Deposit(sender, amount)
            emit_deposit(&sender, &amount.0);

            // Emit Transfer(0x0, sender, amount) — mint signal.
            emit_transfer(&[0u8; 32], &sender, &amount.0);
        }

        Ok(())
    }

    /// `wloom.withdraw(amount: u256)`.
    ///
    /// Debits `amount` from `msg.sender`, decrements `total_supply`, emits
    /// `Withdrawal(sender, amount)` and `Transfer(sender, 0x0, amount)` (burn),
    /// then sends native LOOM to `msg.sender` via
    /// `petal::call(msg.sender, calldata=[], value=amount)`.
    ///
    /// Reverts on insufficient balance, on a >u128 amount (native LOOM is a
    /// u128 quantity), or if the native LOOM transfer fails.
    fn withdraw(&mut self, amount: U256) -> Result<(), &'static str> {
        if amount.is_zero() {
            return Ok(());
        }

        let sender = msg::sender();

        // Debit sender balance.
        let bal_key = k_bal(&sender);
        let bal = read_u256(&bal_key);
        let new_bal = bal
            .checked_sub(amount)
            .ok_or("wloom: insufficient balance")?;
        write_u256(&bal_key, new_bal);

        // Decrement total_supply.
        let ts_key = k_total();
        let ts = read_u256(&ts_key);
        let new_ts = ts
            .checked_sub(amount)
            .ok_or("wloom: total supply underflow")?;
        write_u256(&ts_key, new_ts);

        // Emit Withdrawal(sender, amount).
        emit_withdrawal(&sender, &amount.0);

        // Emit Transfer(sender, 0x0, amount) — burn signal.
        emit_transfer(&sender, &[0u8; 32], &amount.0);

        // Send native LOOM to sender via empty-calldata petal.call with value.
        // wLOOM mints are gated through deposits, so balances always fit in u128
        // (the native LOOM type); converting via try_from_be_u256_bytes guards
        // against any future code path that could put a >u128 amount here.
        let value = LoomValue::try_from_be_u256_bytes(&amount.0)
            .map_err(|_| "wloom: withdraw amount exceeds u128")?;
        let result = petal::call(&sender, &[], value);
        if result.is_err() {
            return Err("wloom: native LOOM transfer failed");
        }

        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Petal entry points
// ---------------------------------------------------------------------------

bloom_petal_sdk::petal! {
    init => do_init,
    call => do_call,
}

/// `init` — no parameters. Writes `total_supply = 0` to mark the petal
/// as initialised. Name/symbol/decimals are hardcoded and not stored.
fn do_init(_calldata: Vec<u8>) {
    write_u256(&k_total(), U256::ZERO);
}

/// `call` — dispatches on the 4-byte selector.
///
/// Routing order:
/// 1. `calldata.len() < 4` → run the `deposit` handler (receive-LOOM fallback
///    per DEX spec §7).
/// 2. Hand-dispatch the legacy ERC-20 selectors (byte-identical to
///    `bloom_dex_abi::selectors::ERC20_*`).
/// 3. Otherwise defer to `wloom::dispatch` for `wloom.deposit()` /
///    `wloom.withdraw(u256)`.
fn do_call(calldata: Vec<u8>) -> i32 {
    if calldata.len() < 4 {
        // Empty/short calldata → deposit fallback (receive-LOOM behaviour).
        run_deposit_fallback();
    }

    let sel: [u8; 4] = [calldata[0], calldata[1], calldata[2], calldata[3]];

    // Legacy ERC-20 selectors are hand-dispatched first (preserves wire compat
    // with the router / pair / pre-migration peers that still link against the
    // bloom-dex-abi selector table).
    let args = &calldata[4..];
    let mut buf = Buf::new(args);
    match sel {
        s if s == selectors::ERC20_TOTAL_SUPPLY  => handle_total_supply(),
        s if s == selectors::ERC20_BALANCE_OF    => handle_balance_of(&mut buf),
        s if s == selectors::ERC20_ALLOWANCE     => handle_allowance(&mut buf),
        s if s == selectors::ERC20_NAME          => handle_name(),
        s if s == selectors::ERC20_SYMBOL        => handle_symbol(),
        s if s == selectors::ERC20_DECIMALS      => handle_decimals(),
        s if s == selectors::ERC20_APPROVE       => handle_approve(&mut buf),
        s if s == selectors::ERC20_TRANSFER      => handle_transfer(&mut buf),
        s if s == selectors::ERC20_TRANSFER_FROM => handle_transfer_from(&mut buf),
        _ => {} // fall through to the chain-ABI dispatcher below
    }
    // The ERC-20 arms above all diverge via petal::return_data / petal::revert;
    // execution only reaches here when none of those selectors matched.

    let mut handler = WloomHandler;
    let caller = msg::sender();
    match wloom::dispatch(&mut handler, &caller, &calldata) {
        Ok(data) => petal::return_data(&data),
        Err(DispatchError::ShortCalldata) => petal::revert("wloom: calldata too short"),
        Err(DispatchError::UnknownSelector(_)) => petal::revert("wloom: unknown selector"),
        Err(DispatchError::Decode(_)) => petal::revert("wloom: bad args"),
        Err(DispatchError::Unauthorized) => petal::revert("wloom: unauthorized"),
        Err(DispatchError::Handler(msg)) => petal::revert(msg),
    }
}

/// Invoke the `deposit` handler directly for the bare-LOOM-transfer fallback
/// (calldata shorter than the 4-byte selector window). Exits via
/// `petal::return_data` on success or `petal::revert` on overflow.
fn run_deposit_fallback() -> ! {
    let mut handler = WloomHandler;
    match wloom::Handler::deposit(&mut handler) {
        Ok(()) => petal::return_data(&[]),
        Err(msg) => petal::revert(msg),
    }
}

// ---------------------------------------------------------------------------
// Host-target unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests;
