//! Args / return buffer protocol for `__petal_<fn>` wasm exports
//! (spec §11.1).
//!
//! Encoding rules (canonical, deterministic, no float):
//! - `u8` / `bool` / `AccessMode`: 1 byte
//! - `u16`: 2 bytes BE
//! - `u32`: 4 bytes BE
//! - `u64`: 8 bytes BE
//! - `u128`: 16 bytes BE
//! - address / `ObjectId`: 32 bytes raw
//! - handle (`RuntimeHandle`): i32 BE (4 bytes)
//! - bytes / string: 4-byte BE length + raw bytes (utf-8 for string)
//! - `TypeTag`: via `bloom_objects::TypeTag` canonical codec (recursive,
//!   variant-tagged; see `bloom-objects/src/type_tag.rs`)
//!
//! The same encoding is consumed by:
//! - the chain's PTB executor when building the args buffer
//! - the macro-emitted `__petal_<name>` entry point when decoding args
//! - the macro-emitted return path when building the ret buffer
//! - the chain's PTB executor when reading returns
//!
//! Macros generated by `bloom-resource-macros` emit code that calls
//! `ArgReader` / `RetWriter` methods directly — the names and
//! signatures here are part of the contract.

use bloom_objects::{CodecError, ObjectId, TypeTag};
use thiserror::Error;

use crate::handle::RuntimeHandle;

/// Errors returned by `ArgReader` / `RetWriter` consumers.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum AbiError {
    /// Buffer ran out before the requested number of bytes could be read.
    #[error("unexpected eof in args buffer: need {needed}, have {available}")]
    UnexpectedEof {
        /// Number of bytes the caller tried to read.
        needed: usize,
        /// Number of bytes that were actually available.
        available: usize,
    },
    /// Bytes remained after `expect_eof` was called.
    #[error("trailing bytes in args buffer: {remaining}")]
    TrailingBytes {
        /// Number of bytes left over.
        remaining: usize,
    },
    /// A `read_string` call decoded a non-UTF-8 byte sequence.
    #[error("invalid utf-8 in string field")]
    InvalidUtf8,
    /// `read_bool` saw a byte other than `0` or `1`.
    #[error("invalid bool byte: {0}")]
    InvalidBool(u8),
    /// `read_handle` saw a sentinel-`-1` handle (or other invalid raw).
    #[error("invalid handle: {0}")]
    InvalidHandle(i32),
    /// Underlying `TypeTag` codec rejected the bytes.
    #[error("type tag codec error: {0}")]
    TypeTagError(#[from] CodecError),
}

// ---------------------------------------------------------------------------
// ArgReader
// ---------------------------------------------------------------------------

/// Cursor over an args buffer; the macro-emitted wasm entry shim drives
/// this in declaration order.
#[derive(Debug)]
pub struct ArgReader<'a> {
    cursor: &'a [u8],
}

impl<'a> ArgReader<'a> {
    /// Wrap a borrowed buffer.
    pub fn new(buf: &'a [u8]) -> Self {
        Self { cursor: buf }
    }

    /// Bytes not yet consumed.
    pub fn remaining(&self) -> usize {
        self.cursor.len()
    }

    /// Borrow the still-pending slice (used in tests and for adapters
    /// that need to forward bytes verbatim).
    pub fn as_slice(&self) -> &'a [u8] {
        self.cursor
    }

    fn take(&mut self, n: usize) -> Result<&'a [u8], AbiError> {
        if self.cursor.len() < n {
            return Err(AbiError::UnexpectedEof {
                needed: n,
                available: self.cursor.len(),
            });
        }
        let (head, tail) = self.cursor.split_at(n);
        self.cursor = tail;
        Ok(head)
    }

    /// Read a single byte.
    pub fn read_u8(&mut self) -> Result<u8, AbiError> {
        let bytes = self.take(1)?;
        Ok(bytes[0])
    }

    /// Read a big-endian `u16`.
    pub fn read_u16(&mut self) -> Result<u16, AbiError> {
        let bytes = self.take(2)?;
        let mut a = [0u8; 2];
        a.copy_from_slice(bytes);
        Ok(u16::from_be_bytes(a))
    }

    /// Read a big-endian `u32`.
    pub fn read_u32(&mut self) -> Result<u32, AbiError> {
        let bytes = self.take(4)?;
        let mut a = [0u8; 4];
        a.copy_from_slice(bytes);
        Ok(u32::from_be_bytes(a))
    }

    /// Read a big-endian `u64`.
    pub fn read_u64(&mut self) -> Result<u64, AbiError> {
        let bytes = self.take(8)?;
        let mut a = [0u8; 8];
        a.copy_from_slice(bytes);
        Ok(u64::from_be_bytes(a))
    }

    /// Read a big-endian `u128`.
    pub fn read_u128(&mut self) -> Result<u128, AbiError> {
        let bytes = self.take(16)?;
        let mut a = [0u8; 16];
        a.copy_from_slice(bytes);
        Ok(u128::from_be_bytes(a))
    }

    /// Read a 32-byte address payload (post-quantum address, hash, raw
    /// pubkey hash, etc.).
    pub fn read_address(&mut self) -> Result<[u8; 32], AbiError> {
        let bytes = self.take(32)?;
        let mut a = [0u8; 32];
        a.copy_from_slice(bytes);
        Ok(a)
    }

    /// Read a 32-byte `ObjectId`.
    pub fn read_object_id(&mut self) -> Result<ObjectId, AbiError> {
        Ok(ObjectId(self.read_address()?))
    }

    /// Read a `RuntimeHandle` (4-byte BE i32). Sentinel `-1` is rejected
    /// because a valid arg handle must point at a real borrow.
    pub fn read_handle(&mut self) -> Result<RuntimeHandle, AbiError> {
        let bytes = self.take(4)?;
        let mut a = [0u8; 4];
        a.copy_from_slice(bytes);
        let raw = i32::from_be_bytes(a);
        if raw < 0 {
            return Err(AbiError::InvalidHandle(raw));
        }
        Ok(RuntimeHandle::from_raw(raw))
    }

    /// Decode a recursive `TypeTag` using its canonical codec.
    ///
    /// The encoded `TypeTag` is *not* length-prefixed — the codec is
    /// self-delimiting. To decode within a larger buffer we walk the
    /// codec via `TypeTag::decode_from`, then advance our cursor by
    /// however many bytes it consumed.
    pub fn read_type_tag(&mut self) -> Result<TypeTag, AbiError> {
        let before = self.cursor;
        let mut walker = before;
        let tag = TypeTag::decode_from(&mut walker, 0)?;
        let consumed = before.len() - walker.len();
        // Advance our own cursor by the exact number of bytes the
        // TypeTag codec consumed.
        self.cursor = &self.cursor[consumed..];
        Ok(tag)
    }

    /// Read a length-prefixed byte vector.
    pub fn read_bytes(&mut self) -> Result<Vec<u8>, AbiError> {
        let len = self.read_u32()? as usize;
        let bytes = self.take(len)?;
        Ok(bytes.to_vec())
    }

    /// Read a length-prefixed UTF-8 string.
    pub fn read_string(&mut self) -> Result<String, AbiError> {
        let len = self.read_u32()? as usize;
        let bytes = self.take(len)?;
        core::str::from_utf8(bytes)
            .map(|s| s.to_owned())
            .map_err(|_| AbiError::InvalidUtf8)
    }

    /// Read a 1-byte boolean. Strict: only `0` and `1` are accepted.
    pub fn read_bool(&mut self) -> Result<bool, AbiError> {
        let b = self.read_u8()?;
        match b {
            0 => Ok(false),
            1 => Ok(true),
            other => Err(AbiError::InvalidBool(other)),
        }
    }

    /// Assert that the buffer has been fully consumed; called by the
    /// macro-emitted entry shim before dispatching to the user fn.
    pub fn expect_eof(&self) -> Result<(), AbiError> {
        if self.cursor.is_empty() {
            Ok(())
        } else {
            Err(AbiError::TrailingBytes {
                remaining: self.cursor.len(),
            })
        }
    }
}

// ---------------------------------------------------------------------------
// RetWriter
// ---------------------------------------------------------------------------

/// Builder for a `__petal_<fn>` return buffer.
#[derive(Debug, Default)]
pub struct RetWriter {
    buf: Vec<u8>,
}

impl RetWriter {
    /// Empty buffer.
    pub fn new() -> Self {
        Self::default()
    }

    /// Pre-sized buffer.
    pub fn with_capacity(cap: usize) -> Self {
        Self {
            buf: Vec::with_capacity(cap),
        }
    }

    /// Write a single byte.
    pub fn write_u8(&mut self, v: u8) {
        self.buf.push(v);
    }

    /// Write a big-endian `u16`.
    pub fn write_u16(&mut self, v: u16) {
        self.buf.extend_from_slice(&v.to_be_bytes());
    }

    /// Write a big-endian `u32`.
    pub fn write_u32(&mut self, v: u32) {
        self.buf.extend_from_slice(&v.to_be_bytes());
    }

    /// Write a big-endian `u64`.
    pub fn write_u64(&mut self, v: u64) {
        self.buf.extend_from_slice(&v.to_be_bytes());
    }

    /// Write a big-endian `u128`.
    pub fn write_u128(&mut self, v: u128) {
        self.buf.extend_from_slice(&v.to_be_bytes());
    }

    /// Write a 32-byte raw address payload.
    pub fn write_address(&mut self, v: &[u8; 32]) {
        self.buf.extend_from_slice(v);
    }

    /// Write a 32-byte `ObjectId`.
    pub fn write_object_id(&mut self, v: &ObjectId) {
        self.buf.extend_from_slice(&v.0);
    }

    /// Write a `RuntimeHandle` as a 4-byte BE i32.
    pub fn write_handle(&mut self, v: RuntimeHandle) {
        self.buf.extend_from_slice(&v.as_raw().to_be_bytes());
    }

    /// Encode a recursive `TypeTag` via its canonical codec.
    ///
    /// Returns an error rather than panicking if encoding overflows the
    /// codec's width constraints (a 64KB+ type name, etc.).
    pub fn write_type_tag(&mut self, v: &TypeTag) -> Result<(), AbiError> {
        v.encode_into(&mut self.buf).map_err(AbiError::from)
    }

    /// Write a length-prefixed byte vector.
    pub fn write_bytes(&mut self, v: &[u8]) {
        let len = u32::try_from(v.len()).expect("bytes length fits in u32 for canonical encoding");
        self.buf.extend_from_slice(&len.to_be_bytes());
        self.buf.extend_from_slice(v);
    }

    /// Write a length-prefixed UTF-8 string.
    pub fn write_string(&mut self, v: &str) {
        self.write_bytes(v.as_bytes());
    }

    /// Write a 1-byte boolean.
    pub fn write_bool(&mut self, v: bool) {
        self.buf.push(u8::from(v));
    }

    /// Finalize and return the underlying buffer.
    pub fn finish(self) -> Vec<u8> {
        self.buf
    }

    /// Borrow the in-progress buffer (useful for size queries before
    /// finishing, e.g. when checking against the `ret_cap` budget).
    pub fn as_slice(&self) -> &[u8] {
        &self.buf
    }

    /// Current encoded length.
    pub fn len(&self) -> usize {
        self.buf.len()
    }

    /// `true` iff nothing has been written yet.
    pub fn is_empty(&self) -> bool {
        self.buf.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use bloom_objects::TypeTag;

    fn rt_round<F, G, T>(write: F, read: G, value: T)
    where
        F: FnOnce(&mut RetWriter, &T),
        G: FnOnce(&mut ArgReader<'_>) -> T,
        T: PartialEq + core::fmt::Debug,
    {
        let mut w = RetWriter::new();
        write(&mut w, &value);
        let buf = w.finish();
        let mut r = ArgReader::new(&buf);
        let got = read(&mut r);
        r.expect_eof().unwrap();
        assert_eq!(got, value);
    }

    #[test]
    fn u8_round_trip() {
        rt_round(
            |w, v| w.write_u8(*v),
            |r| r.read_u8().unwrap(),
            0xABu8,
        );
    }

    #[test]
    fn u16_round_trip() {
        rt_round(
            |w, v| w.write_u16(*v),
            |r| r.read_u16().unwrap(),
            0xBEEFu16,
        );
    }

    #[test]
    fn u32_round_trip() {
        rt_round(
            |w, v| w.write_u32(*v),
            |r| r.read_u32().unwrap(),
            0xDEAD_BEEFu32,
        );
    }

    #[test]
    fn u64_round_trip() {
        rt_round(
            |w, v| w.write_u64(*v),
            |r| r.read_u64().unwrap(),
            0x0102_0304_0506_0708u64,
        );
    }

    #[test]
    fn u128_round_trip() {
        rt_round(
            |w, v| w.write_u128(*v),
            |r| r.read_u128().unwrap(),
            0x0102_0304_0506_0708_090A_0B0C_0D0E_0F10u128,
        );
    }

    #[test]
    fn u16_is_big_endian_on_the_wire() {
        let mut w = RetWriter::new();
        w.write_u16(0x1234);
        assert_eq!(w.finish(), vec![0x12, 0x34]);
    }

    #[test]
    fn u32_is_big_endian_on_the_wire() {
        let mut w = RetWriter::new();
        w.write_u32(0xAABB_CCDD);
        assert_eq!(w.finish(), vec![0xAA, 0xBB, 0xCC, 0xDD]);
    }

    #[test]
    fn address_round_trip() {
        let addr = [0xAB; 32];
        rt_round(
            |w, v| w.write_address(v),
            |r| r.read_address().unwrap(),
            addr,
        );
    }

    #[test]
    fn object_id_round_trip() {
        let id = ObjectId([0x42; 32]);
        rt_round(
            |w, v| w.write_object_id(v),
            |r| r.read_object_id().unwrap(),
            id,
        );
    }

    #[test]
    fn handle_round_trip() {
        let h = RuntimeHandle::from_raw(7);
        rt_round(
            |w, v| w.write_handle(*v),
            |r| r.read_handle().unwrap(),
            h,
        );
    }

    #[test]
    fn handle_is_big_endian_on_the_wire() {
        let mut w = RetWriter::new();
        w.write_handle(RuntimeHandle::from_raw(0x0001_0203));
        assert_eq!(w.finish(), vec![0, 1, 2, 3]);
    }

    #[test]
    fn handle_rejects_negative() {
        let mut w = RetWriter::new();
        w.write_handle(RuntimeHandle::INVALID);
        let buf = w.finish();
        let mut r = ArgReader::new(&buf);
        assert_eq!(r.read_handle(), Err(AbiError::InvalidHandle(-1)));
    }

    #[test]
    fn bytes_round_trip() {
        let v = b"hello bloom".to_vec();
        rt_round(
            |w, v| w.write_bytes(v),
            |r| r.read_bytes().unwrap(),
            v,
        );
    }

    #[test]
    fn bytes_empty_round_trip() {
        let v: Vec<u8> = Vec::new();
        rt_round(
            |w, v| w.write_bytes(v),
            |r| r.read_bytes().unwrap(),
            v,
        );
    }

    #[test]
    fn bytes_length_prefix_is_big_endian() {
        let mut w = RetWriter::new();
        w.write_bytes(b"abc");
        assert_eq!(w.finish(), vec![0, 0, 0, 3, b'a', b'b', b'c']);
    }

    #[test]
    fn string_round_trip() {
        rt_round(
            |w, v| w.write_string(v),
            |r| r.read_string().unwrap(),
            "Coin<USDC>".to_string(),
        );
    }

    #[test]
    fn string_rejects_invalid_utf8() {
        // 4-byte BE length prefix 2, then two non-UTF-8 bytes.
        let buf = [0u8, 0, 0, 2, 0xFF, 0xFE];
        let mut r = ArgReader::new(&buf);
        assert_eq!(r.read_string(), Err(AbiError::InvalidUtf8));
    }

    #[test]
    fn bool_round_trip() {
        rt_round(
            |w, v| w.write_bool(*v),
            |r| r.read_bool().unwrap(),
            true,
        );
        rt_round(
            |w, v| w.write_bool(*v),
            |r| r.read_bool().unwrap(),
            false,
        );
    }

    #[test]
    fn bool_rejects_garbage() {
        let buf = [3u8];
        let mut r = ArgReader::new(&buf);
        assert_eq!(r.read_bool(), Err(AbiError::InvalidBool(3)));
    }

    #[test]
    fn unexpected_eof_reports_need_and_have() {
        let buf = [1u8, 2];
        let mut r = ArgReader::new(&buf);
        assert_eq!(
            r.read_u32(),
            Err(AbiError::UnexpectedEof {
                needed: 4,
                available: 2,
            })
        );
    }

    #[test]
    fn expect_eof_detects_trailing() {
        let buf = [1u8, 2, 3];
        let r = ArgReader::new(&buf);
        assert_eq!(r.expect_eof(), Err(AbiError::TrailingBytes { remaining: 3 }));
    }

    #[test]
    fn expect_eof_passes_when_drained() {
        let mut w = RetWriter::new();
        w.write_u8(7);
        let buf = w.finish();
        let mut r = ArgReader::new(&buf);
        r.read_u8().unwrap();
        r.expect_eof().unwrap();
    }

    #[test]
    fn type_tag_round_trip_concrete() {
        let tag = TypeTag::Concrete {
            petal_hash: [0x11; 32],
            type_name: "Coin".to_string(),
            type_args: vec![TypeTag::Concrete {
                petal_hash: [0x22; 32],
                type_name: "USDC".to_string(),
                type_args: vec![],
            }],
        };
        let mut w = RetWriter::new();
        w.write_type_tag(&tag).unwrap();
        let buf = w.finish();
        let mut r = ArgReader::new(&buf);
        let got = r.read_type_tag().unwrap();
        r.expect_eof().unwrap();
        assert_eq!(got, tag);
    }

    #[test]
    fn type_tag_round_trip_generic() {
        let tag = TypeTag::Generic { idx: 0 };
        let mut w = RetWriter::new();
        w.write_type_tag(&tag).unwrap();
        let buf = w.finish();
        let mut r = ArgReader::new(&buf);
        assert_eq!(r.read_type_tag().unwrap(), tag);
        r.expect_eof().unwrap();
    }

    #[test]
    fn mixed_args_buffer_round_trip() {
        // Simulates: fn(addr: Address, amount: u128, handle: RuntimeHandle, name: String)
        let addr = [0xAB; 32];
        let amount: u128 = 1_000_000_000_000_000_000;
        let handle = RuntimeHandle::from_raw(42);
        let name = "swap_a_for_b".to_string();

        let mut w = RetWriter::new();
        w.write_address(&addr);
        w.write_u128(amount);
        w.write_handle(handle);
        w.write_string(&name);
        let buf = w.finish();

        let mut r = ArgReader::new(&buf);
        assert_eq!(r.read_address().unwrap(), addr);
        assert_eq!(r.read_u128().unwrap(), amount);
        assert_eq!(r.read_handle().unwrap(), handle);
        assert_eq!(r.read_string().unwrap(), name);
        r.expect_eof().unwrap();
    }

    #[test]
    fn ret_writer_len_and_is_empty() {
        let mut w = RetWriter::new();
        assert!(w.is_empty());
        assert_eq!(w.len(), 0);
        w.write_u64(1);
        assert!(!w.is_empty());
        assert_eq!(w.len(), 8);
    }

    #[test]
    fn ret_writer_with_capacity_does_not_change_output() {
        let mut a = RetWriter::with_capacity(64);
        let mut b = RetWriter::new();
        for w in [&mut a, &mut b] {
            w.write_u32(1);
            w.write_u32(2);
        }
        assert_eq!(a.finish(), b.finish());
    }

    #[test]
    fn arg_reader_remaining_decreases() {
        let mut w = RetWriter::new();
        w.write_u32(1);
        w.write_u32(2);
        let buf = w.finish();
        let mut r = ArgReader::new(&buf);
        assert_eq!(r.remaining(), 8);
        r.read_u32().unwrap();
        assert_eq!(r.remaining(), 4);
        r.read_u32().unwrap();
        assert_eq!(r.remaining(), 0);
    }
}
