//! Args / return buffer protocol for `__petal_<fn>` wasm exports
//! (spec §11.1).
//!
//! Encoding rules (canonical, deterministic, no float):
//! - `u8` / `bool` / `AccessMode`: 1 byte
//! - `u16`: 2 bytes BE
//! - `u32`: 4 bytes BE
//! - `u64`: 8 bytes BE
//! - `u128`: 16 bytes BE
//! - address / `ObjectId`: 32 bytes raw
//! - handle (`RuntimeHandle`): i32 BE (4 bytes)
//! - bytes / string: ULEB128 length + raw bytes (utf-8 for string)
//! - `TypeTag`: via `bloom_objects::TypeTag` canonical codec (recursive,
//!   variant-tagged; see `bloom-objects/src/type_tag.rs`)
//!
//! The same encoding is consumed by:
//! - the chain's PTB executor when building the args buffer
//! - the macro-emitted `__petal_<name>` entry point when decoding args
//! - the macro-emitted return path when building the ret buffer
//! - the chain's PTB executor when reading returns
//!
//! Macros generated by `bloom-resource-macros` emit code that calls
//! `ArgReader` / `RetWriter` methods directly — the names and
//! signatures here are part of the contract.

use bloom_objects::{CodecError, ObjectId, TypeTag};
use bloom_value::{read_uleb128, write_uleb128};
use thiserror::Error;

use crate::handle::RuntimeHandle;

/// Errors returned by `ArgReader` / `RetWriter` consumers.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum AbiError {
    /// Buffer ran out before the requested number of bytes could be read.
    #[error("unexpected eof in args buffer: need {needed}, have {available}")]
    UnexpectedEof {
        /// Number of bytes the caller tried to read.
        needed: usize,
        /// Number of bytes that were actually available.
        available: usize,
    },
    /// Bytes remained after `expect_eof` was called.
    #[error("trailing bytes in args buffer: {remaining}")]
    TrailingBytes {
        /// Number of bytes left over.
        remaining: usize,
    },
    /// A `read_string` call decoded a non-UTF-8 byte sequence.
    #[error("invalid utf-8 in string field")]
    InvalidUtf8,
    /// `read_bool` saw a byte other than `0` or `1`.
    #[error("invalid bool byte: {0}")]
    InvalidBool(u8),
    /// `read_handle` saw a sentinel-`-1` handle (or other invalid raw).
    #[error("invalid handle: {0}")]
    InvalidHandle(i32),
    /// Underlying `TypeTag` codec rejected the bytes.
    #[error("type tag codec error: {0}")]
    TypeTagError(#[from] CodecError),
    /// Shared value codec rejected canonical bytes.
    #[error("value codec error: {0}")]
    ValueCodec(String),
    /// A framed arg's tag byte did not match the variant the declared
    /// parameter expected (e.g. a `Signer` slot fed an `Object` arg).
    #[error("arg tag mismatch: expected {expected}, got {got}")]
    ArgTagMismatch {
        /// Tag byte the parameter shape expected.
        expected: u8,
        /// Tag byte actually present on the wire.
        got: u8,
    },
    /// A framed `Object` / `Use` arg carried a byte length other than the
    /// 32 bytes a raw `ObjectId` requires.
    #[error("object arg id must be 32 bytes, got {0}")]
    BadObjectIdLen(usize),
}

// ---------------------------------------------------------------------------
// ArgReader
// ---------------------------------------------------------------------------

/// Cursor over an args buffer; the macro-emitted wasm entry shim drives
/// this in declaration order.
#[derive(Debug)]
pub struct ArgReader<'a> {
    cursor: &'a [u8],
}

impl<'a> ArgReader<'a> {
    /// Wrap a borrowed buffer.
    pub fn new(buf: &'a [u8]) -> Self {
        Self { cursor: buf }
    }

    /// Bytes not yet consumed.
    pub fn remaining(&self) -> usize {
        self.cursor.len()
    }

    /// Borrow the still-pending slice (used in tests and for adapters
    /// that need to forward bytes verbatim).
    pub fn as_slice(&self) -> &'a [u8] {
        self.cursor
    }

    fn take(&mut self, n: usize) -> Result<&'a [u8], AbiError> {
        if self.cursor.len() < n {
            return Err(AbiError::UnexpectedEof {
                needed: n,
                available: self.cursor.len(),
            });
        }
        let (head, tail) = self.cursor.split_at(n);
        self.cursor = tail;
        Ok(head)
    }

    fn read_len(&mut self, kind: &str) -> Result<usize, AbiError> {
        let len =
            read_uleb128(&mut self.cursor).map_err(|e| AbiError::ValueCodec(e.to_string()))?;
        usize::try_from(len).map_err(|_| {
            AbiError::ValueCodec(format!("{kind} length does not fit in usize: {len}"))
        })
    }

    /// Read a single byte.
    pub fn read_u8(&mut self) -> Result<u8, AbiError> {
        let bytes = self.take(1)?;
        Ok(bytes[0])
    }

    /// Read a big-endian `u16`.
    pub fn read_u16(&mut self) -> Result<u16, AbiError> {
        let bytes = self.take(2)?;
        let mut a = [0u8; 2];
        a.copy_from_slice(bytes);
        Ok(u16::from_be_bytes(a))
    }

    /// Read a big-endian `u32`.
    pub fn read_u32(&mut self) -> Result<u32, AbiError> {
        let bytes = self.take(4)?;
        let mut a = [0u8; 4];
        a.copy_from_slice(bytes);
        Ok(u32::from_be_bytes(a))
    }

    /// Read a big-endian `u64`.
    pub fn read_u64(&mut self) -> Result<u64, AbiError> {
        let bytes = self.take(8)?;
        let mut a = [0u8; 8];
        a.copy_from_slice(bytes);
        Ok(u64::from_be_bytes(a))
    }

    /// Read a big-endian `u128`.
    pub fn read_u128(&mut self) -> Result<u128, AbiError> {
        let bytes = self.take(16)?;
        let mut a = [0u8; 16];
        a.copy_from_slice(bytes);
        Ok(u128::from_be_bytes(a))
    }

    /// Read a 32-byte address payload (post-quantum address, hash, raw
    /// pubkey hash, etc.).
    pub fn read_address(&mut self) -> Result<[u8; 32], AbiError> {
        let bytes = self.take(32)?;
        let mut a = [0u8; 32];
        a.copy_from_slice(bytes);
        Ok(a)
    }

    /// Read a 32-byte `ObjectId`.
    pub fn read_object_id(&mut self) -> Result<ObjectId, AbiError> {
        Ok(ObjectId(self.read_address()?))
    }

    /// Read a `RuntimeHandle` (4-byte BE i32). Sentinel `-1` is rejected
    /// because a valid arg handle must point at a real borrow.
    pub fn read_handle(&mut self) -> Result<RuntimeHandle, AbiError> {
        let bytes = self.take(4)?;
        let mut a = [0u8; 4];
        a.copy_from_slice(bytes);
        let raw = i32::from_be_bytes(a);
        if raw < 0 {
            return Err(AbiError::InvalidHandle(raw));
        }
        Ok(RuntimeHandle::from_raw(raw))
    }

    /// Decode a recursive `TypeTag` using its canonical codec.
    ///
    /// The encoded `TypeTag` is *not* length-prefixed — the codec is
    /// self-delimiting. To decode within a larger buffer we walk the
    /// codec via `TypeTag::decode_from`, then advance our cursor by
    /// however many bytes it consumed.
    pub fn read_type_tag(&mut self) -> Result<TypeTag, AbiError> {
        let before = self.cursor;
        let mut walker = before;
        let tag = TypeTag::decode_from(&mut walker, 0)?;
        let consumed = before.len() - walker.len();
        // Advance our own cursor by the exact number of bytes the
        // TypeTag codec consumed.
        self.cursor = &self.cursor[consumed..];
        Ok(tag)
    }

    /// Read a length-prefixed byte vector.
    pub fn read_bytes(&mut self) -> Result<Vec<u8>, AbiError> {
        let len = self.read_len("bytes")?;
        let bytes = self.take(len)?;
        Ok(bytes.to_vec())
    }

    /// Read a length-prefixed UTF-8 string.
    pub fn read_string(&mut self) -> Result<String, AbiError> {
        let len = self.read_len("string")?;
        let bytes = self.take(len)?;
        core::str::from_utf8(bytes)
            .map(|s| s.to_owned())
            .map_err(|_| AbiError::InvalidUtf8)
    }

    /// Read a 1-byte boolean. Strict: only `0` and `1` are accepted.
    pub fn read_bool(&mut self) -> Result<bool, AbiError> {
        let b = self.read_u8()?;
        match b {
            0 => Ok(false),
            1 => Ok(true),
            other => Err(AbiError::InvalidBool(other)),
        }
    }

    /// Assert that the buffer has been fully consumed; called by the
    /// macro-emitted entry shim before dispatching to the user fn.
    pub fn expect_eof(&self) -> Result<(), AbiError> {
        if self.cursor.is_empty() {
            Ok(())
        } else {
            Err(AbiError::TrailingBytes {
                remaining: self.cursor.len(),
            })
        }
    }
}

// ---------------------------------------------------------------------------
// RetWriter
// ---------------------------------------------------------------------------

fn write_len(len: usize, out: &mut Vec<u8>) {
    let len_u64 = u64::try_from(len).expect("length fits in u64");
    write_uleb128(len_u64, out);
}

/// Builder for a `__petal_<fn>` return buffer.
#[derive(Debug, Default)]
pub struct RetWriter {
    buf: Vec<u8>,
}

impl RetWriter {
    /// Empty buffer.
    pub fn new() -> Self {
        Self::default()
    }

    /// Pre-sized buffer.
    pub fn with_capacity(cap: usize) -> Self {
        Self {
            buf: Vec::with_capacity(cap),
        }
    }

    /// Write a single byte.
    pub fn write_u8(&mut self, v: u8) {
        self.buf.push(v);
    }

    /// Write a big-endian `u16`.
    pub fn write_u16(&mut self, v: u16) {
        self.buf.extend_from_slice(&v.to_be_bytes());
    }

    /// Write a big-endian `u32`.
    pub fn write_u32(&mut self, v: u32) {
        self.buf.extend_from_slice(&v.to_be_bytes());
    }

    /// Write a big-endian `u64`.
    pub fn write_u64(&mut self, v: u64) {
        self.buf.extend_from_slice(&v.to_be_bytes());
    }

    /// Write a big-endian `u128`.
    pub fn write_u128(&mut self, v: u128) {
        self.buf.extend_from_slice(&v.to_be_bytes());
    }

    /// Write a 32-byte raw address payload.
    pub fn write_address(&mut self, v: &[u8; 32]) {
        self.buf.extend_from_slice(v);
    }

    /// Write a 32-byte `ObjectId`.
    pub fn write_object_id(&mut self, v: &ObjectId) {
        self.buf.extend_from_slice(&v.0);
    }

    /// Write a `RuntimeHandle` as a 4-byte BE i32.
    pub fn write_handle(&mut self, v: RuntimeHandle) {
        self.buf.extend_from_slice(&v.as_raw().to_be_bytes());
    }

    /// Encode a recursive `TypeTag` via its canonical codec.
    ///
    /// Returns an error rather than panicking if encoding overflows the
    /// codec's width constraints (a 64KB+ type name, etc.).
    pub fn write_type_tag(&mut self, v: &TypeTag) -> Result<(), AbiError> {
        v.encode_into(&mut self.buf).map_err(AbiError::from)
    }

    /// Write a length-prefixed byte vector.
    pub fn write_bytes(&mut self, v: &[u8]) {
        write_len(v.len(), &mut self.buf);
        self.buf.extend_from_slice(v);
    }

    /// Write a length-prefixed UTF-8 string.
    pub fn write_string(&mut self, v: &str) {
        self.write_bytes(v.as_bytes());
    }

    /// Write a 1-byte boolean.
    pub fn write_bool(&mut self, v: bool) {
        self.buf.push(u8::from(v));
    }

    /// Finalize and return the underlying buffer.
    pub fn finish(self) -> Vec<u8> {
        self.buf
    }

    /// Borrow the in-progress buffer (useful for size queries before
    /// finishing, e.g. when checking against the `ret_cap` budget).
    pub fn as_slice(&self) -> &[u8] {
        &self.buf
    }

    /// Current encoded length.
    pub fn len(&self) -> usize {
        self.buf.len()
    }

    /// `true` iff nothing has been written yet.
    pub fn is_empty(&self) -> bool {
        self.buf.is_empty()
    }
}

/// Cursor over a count-prefixed return-slot envelope produced by
/// [`RetWriter`].
#[derive(Debug)]
pub struct RetReader<'a> {
    inner: ArgReader<'a>,
    count: u32,
    consumed: u32,
}

impl<'a> RetReader<'a> {
    /// Wrap a buffer and read the leading `u32` BE return count.
    pub fn new(buf: &'a [u8]) -> Result<Self, AbiError> {
        let mut inner = ArgReader::new(buf);
        let count = inner.read_u32()?;
        Ok(Self {
            inner,
            count,
            consumed: 0,
        })
    }

    /// The return-slot count declared by the leading prefix.
    pub fn declared_count(&self) -> u32 {
        self.count
    }

    /// Decode the next length-prefixed return slot.
    pub fn next_bytes(&mut self, max_len: usize) -> Result<Vec<u8>, AbiError> {
        if self.consumed >= self.count {
            return Err(AbiError::UnexpectedEof {
                needed: 1,
                available: 0,
            });
        }
        let bytes = self.inner.read_bytes()?;
        if bytes.len() > max_len {
            return Err(AbiError::ValueCodec(format!(
                "return slot too large: {} > {}",
                bytes.len(),
                max_len
            )));
        }
        self.consumed += 1;
        Ok(bytes)
    }

    /// Assert that all declared slots and all bytes have been consumed.
    pub fn expect_finished(&self) -> Result<(), AbiError> {
        if self.consumed != self.count {
            return Err(AbiError::UnexpectedEof {
                needed: (self.count - self.consumed) as usize,
                available: 0,
            });
        }
        if self.inner.remaining() != 0 {
            return Err(AbiError::TrailingBytes {
                remaining: self.inner.remaining(),
            });
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// CallArgsWriter / CallArgsReader — the *framed* PTB calldata envelope
// ---------------------------------------------------------------------------
//
// The chain's PTB executor marshals a `Command::Move`'s args into a
// count-prefixed, per-arg-tagged buffer (`executor.rs::marshal_args`):
//
//     count(u32 BE) | repeat count times: tag(u8) + payload
//
// where the tags mirror the `Arg` enum the CLI / PtbSession lowered from:
//
//     tag 0  Signer   → u16 BE signer index
//     tag 1  Const    → ULEB128 len + raw bytes
//     tag 2  Object   → 32 raw `ObjectId` bytes
//     tag 3  Use      → ULEB128 len + raw bytes (an upstream return slot;
//                       for Coin/Capability threading this is a 32-byte id)
//     tag 4  TypeArg  → ULEB128 len + canonical `TypeTag` bytes
//
// The macro-emitted `__petal_<fn>` shim consumes exactly this framing via
// `CallArgsReader`, and the host-side test harness produces it via
// `CallArgsWriter`. Keeping one writer/reader pair here means the wire
// format has a single source of truth shared by the executor, the shim,
// and the tests.

/// Per-arg tag byte for a `Signer` slot.
pub const ARG_TAG_SIGNER: u8 = 0;
/// Per-arg tag byte for a `Const` (raw bytes) slot.
pub const ARG_TAG_CONST: u8 = 1;
/// Per-arg tag byte for an `Object` (32-byte id) slot.
pub const ARG_TAG_OBJECT: u8 = 2;
/// Per-arg tag byte for a `Use` (upstream return) slot.
pub const ARG_TAG_USE: u8 = 3;
/// Per-arg tag byte for a `TypeArg` (canonical `TypeTag`) slot.
pub const ARG_TAG_TYPE: u8 = 4;

/// Builder for the count-prefixed, per-arg-tagged calldata envelope that
/// the chain PTB executor hands a `__petal_<fn>` export.
#[derive(Debug, Default)]
pub struct CallArgsWriter {
    count: u32,
    body: Vec<u8>,
}

impl CallArgsWriter {
    /// Empty envelope (no args pushed yet).
    pub fn new() -> Self {
        Self::default()
    }

    fn push_tag(&mut self, tag: u8) {
        self.count += 1;
        self.body.push(tag);
    }

    /// Append a `Signer` arg (its `signers[]` index).
    pub fn push_signer(&mut self, idx: u16) {
        self.push_tag(ARG_TAG_SIGNER);
        self.body.extend_from_slice(&idx.to_be_bytes());
    }

    /// Append a `Const` arg (raw, length-prefixed bytes).
    pub fn push_const(&mut self, bytes: &[u8]) {
        self.push_tag(ARG_TAG_CONST);
        write_len(bytes.len(), &mut self.body);
        self.body.extend_from_slice(bytes);
    }

    /// Append an `Object` arg (32 raw `ObjectId` bytes).
    pub fn push_object(&mut self, id: &ObjectId) {
        self.push_tag(ARG_TAG_OBJECT);
        self.body.extend_from_slice(&id.0);
    }

    /// Append a `Use` arg — an upstream command's return slot, length
    /// prefixed. For Coin/Capability threading this is a 32-byte id.
    pub fn push_use(&mut self, bytes: &[u8]) {
        self.push_tag(ARG_TAG_USE);
        write_len(bytes.len(), &mut self.body);
        self.body.extend_from_slice(bytes);
    }

    /// Append a `TypeArg` slot, encoding `tag` via its canonical codec.
    pub fn push_type_arg(&mut self, tag: &TypeTag) -> Result<(), AbiError> {
        let enc = tag.encode_canonical()?;
        self.push_tag(ARG_TAG_TYPE);
        write_len(enc.len(), &mut self.body);
        self.body.extend_from_slice(&enc);
        Ok(())
    }

    /// Finalize: prepend the `u32` BE arg count to the accumulated body.
    pub fn finish(self) -> Vec<u8> {
        let mut out = Vec::with_capacity(4 + self.body.len());
        out.extend_from_slice(&self.count.to_be_bytes());
        out.extend_from_slice(&self.body);
        out
    }
}

/// Cursor over the framed calldata envelope. The macro-emitted shim
/// drives this in declaration order, calling the `next_*` accessor that
/// matches each parameter's shape.
#[derive(Debug)]
pub struct CallArgsReader<'a> {
    inner: ArgReader<'a>,
    count: u32,
    consumed: u32,
}

impl<'a> CallArgsReader<'a> {
    /// Wrap a buffer and read the leading `u32` BE arg count.
    pub fn new(buf: &'a [u8]) -> Result<Self, AbiError> {
        let mut inner = ArgReader::new(buf);
        let count = inner.read_u32()?;
        Ok(Self {
            inner,
            count,
            consumed: 0,
        })
    }

    /// The arg count declared by the leading length prefix.
    pub fn declared_count(&self) -> u32 {
        self.count
    }

    /// Bytes not yet consumed from the body.
    pub fn remaining(&self) -> usize {
        self.inner.remaining()
    }

    fn expect_tag(&mut self, expected: u8) -> Result<(), AbiError> {
        if self.consumed >= self.count {
            return Err(AbiError::UnexpectedEof {
                needed: 1,
                available: 0,
            });
        }
        let got = self.inner.read_u8()?;
        if got == expected {
            self.consumed += 1;
            Ok(())
        } else {
            Err(AbiError::ArgTagMismatch { expected, got })
        }
    }

    /// Assert the declared arg count and byte body are fully consumed.
    pub fn expect_finished(&self) -> Result<(), AbiError> {
        if self.consumed != self.count {
            return Err(AbiError::UnexpectedEof {
                needed: (self.count - self.consumed) as usize,
                available: 0,
            });
        }
        if self.inner.remaining() != 0 {
            return Err(AbiError::TrailingBytes {
                remaining: self.inner.remaining(),
            });
        }
        Ok(())
    }

    /// Decode a `Signer` slot to its signer index.
    pub fn next_signer(&mut self) -> Result<u16, AbiError> {
        self.expect_tag(ARG_TAG_SIGNER)?;
        self.inner.read_u16()
    }

    /// Decode a `Const` (or `Use`) slot to its raw length-prefixed bytes.
    /// Accepts either tag because a value-typed parameter can be supplied
    /// as a literal `Const` or threaded from an upstream `Use` return.
    pub fn next_const_bytes(&mut self) -> Result<Vec<u8>, AbiError> {
        if self.consumed >= self.count {
            return Err(AbiError::UnexpectedEof {
                needed: 1,
                available: 0,
            });
        }
        let tag = self.inner.read_u8()?;
        match tag {
            ARG_TAG_CONST | ARG_TAG_USE => {
                let bytes = self.inner.read_bytes()?;
                self.consumed += 1;
                Ok(bytes)
            }
            other => Err(AbiError::ArgTagMismatch {
                expected: ARG_TAG_CONST,
                got: other,
            }),
        }
    }

    /// Decode an `Object` slot (tag 2, 32 raw bytes) or a `Use` slot
    /// (tag 3, length-prefixed) that threads a Coin/Capability id, into a
    /// 32-byte `ObjectId`.
    pub fn next_object_id(&mut self) -> Result<ObjectId, AbiError> {
        if self.consumed >= self.count {
            return Err(AbiError::UnexpectedEof {
                needed: 1,
                available: 0,
            });
        }
        let tag = self.inner.read_u8()?;
        let out = match tag {
            ARG_TAG_OBJECT => self.inner.read_object_id(),
            ARG_TAG_USE => {
                let b = self.inner.read_bytes()?;
                if b.len() != 32 {
                    return Err(AbiError::BadObjectIdLen(b.len()));
                }
                let mut a = [0u8; 32];
                a.copy_from_slice(&b);
                Ok(ObjectId(a))
            }
            other => Err(AbiError::ArgTagMismatch {
                expected: ARG_TAG_OBJECT,
                got: other,
            }),
        }?;
        self.consumed += 1;
        Ok(out)
    }

    /// Decode a `TypeArg` slot (tag 4) into a `TypeTag`.
    pub fn next_type_arg(&mut self) -> Result<TypeTag, AbiError> {
        self.expect_tag(ARG_TAG_TYPE)?;
        let b = self.inner.read_bytes()?;
        TypeTag::decode_canonical(&b).map_err(AbiError::from)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use bloom_objects::TypeTag;

    fn rt_round<F, G, T>(write: F, read: G, value: T)
    where
        F: FnOnce(&mut RetWriter, &T),
        G: FnOnce(&mut ArgReader<'_>) -> T,
        T: PartialEq + core::fmt::Debug,
    {
        let mut w = RetWriter::new();
        write(&mut w, &value);
        let buf = w.finish();
        let mut r = ArgReader::new(&buf);
        let got = read(&mut r);
        r.expect_eof().unwrap();
        assert_eq!(got, value);
    }

    #[test]
    fn u8_round_trip() {
        rt_round(|w, v| w.write_u8(*v), |r| r.read_u8().unwrap(), 0xABu8);
    }

    #[test]
    fn u16_round_trip() {
        rt_round(|w, v| w.write_u16(*v), |r| r.read_u16().unwrap(), 0xBEEFu16);
    }

    #[test]
    fn u32_round_trip() {
        rt_round(
            |w, v| w.write_u32(*v),
            |r| r.read_u32().unwrap(),
            0xDEAD_BEEFu32,
        );
    }

    #[test]
    fn u64_round_trip() {
        rt_round(
            |w, v| w.write_u64(*v),
            |r| r.read_u64().unwrap(),
            0x0102_0304_0506_0708u64,
        );
    }

    #[test]
    fn u128_round_trip() {
        rt_round(
            |w, v| w.write_u128(*v),
            |r| r.read_u128().unwrap(),
            0x0102_0304_0506_0708_090A_0B0C_0D0E_0F10u128,
        );
    }

    #[test]
    fn u16_is_big_endian_on_the_wire() {
        let mut w = RetWriter::new();
        w.write_u16(0x1234);
        assert_eq!(w.finish(), vec![0x12, 0x34]);
    }

    #[test]
    fn u32_is_big_endian_on_the_wire() {
        let mut w = RetWriter::new();
        w.write_u32(0xAABB_CCDD);
        assert_eq!(w.finish(), vec![0xAA, 0xBB, 0xCC, 0xDD]);
    }

    #[test]
    fn address_round_trip() {
        let addr = [0xAB; 32];
        rt_round(
            |w, v| w.write_address(v),
            |r| r.read_address().unwrap(),
            addr,
        );
    }

    #[test]
    fn object_id_round_trip() {
        let id = ObjectId([0x42; 32]);
        rt_round(
            |w, v| w.write_object_id(v),
            |r| r.read_object_id().unwrap(),
            id,
        );
    }

    #[test]
    fn handle_round_trip() {
        let h = RuntimeHandle::from_raw(7);
        rt_round(|w, v| w.write_handle(*v), |r| r.read_handle().unwrap(), h);
    }

    #[test]
    fn handle_is_big_endian_on_the_wire() {
        let mut w = RetWriter::new();
        w.write_handle(RuntimeHandle::from_raw(0x0001_0203));
        assert_eq!(w.finish(), vec![0, 1, 2, 3]);
    }

    #[test]
    fn handle_rejects_negative() {
        let mut w = RetWriter::new();
        w.write_handle(RuntimeHandle::INVALID);
        let buf = w.finish();
        let mut r = ArgReader::new(&buf);
        assert_eq!(r.read_handle(), Err(AbiError::InvalidHandle(-1)));
    }

    #[test]
    fn bytes_round_trip() {
        let v = b"hello bloom".to_vec();
        rt_round(|w, v| w.write_bytes(v), |r| r.read_bytes().unwrap(), v);
    }

    #[test]
    fn bytes_empty_round_trip() {
        let v: Vec<u8> = Vec::new();
        rt_round(|w, v| w.write_bytes(v), |r| r.read_bytes().unwrap(), v);
    }

    #[test]
    fn bytes_length_prefix_is_uleb128() {
        let mut w = RetWriter::new();
        w.write_bytes(b"abc");
        assert_eq!(w.finish(), vec![3, b'a', b'b', b'c']);
    }

    #[test]
    fn ret_reader_round_trips_slots() {
        let mut w = RetWriter::new();
        w.write_u32(2);
        w.write_bytes(b"one");
        w.write_bytes(b"two");
        let buf = w.finish();
        let mut r = RetReader::new(&buf).unwrap();
        assert_eq!(r.declared_count(), 2);
        assert_eq!(r.next_bytes(16).unwrap(), b"one");
        assert_eq!(r.next_bytes(16).unwrap(), b"two");
        r.expect_finished().unwrap();
    }

    #[test]
    fn ret_reader_rejects_oversized_slot() {
        let mut w = RetWriter::new();
        w.write_u32(1);
        w.write_bytes(b"toolong");
        let buf = w.finish();
        let mut r = RetReader::new(&buf).unwrap();
        assert!(matches!(r.next_bytes(3), Err(AbiError::ValueCodec(_))));
    }

    #[test]
    fn string_round_trip() {
        rt_round(
            |w, v| w.write_string(v),
            |r| r.read_string().unwrap(),
            "Coin<USDC>".to_string(),
        );
    }

    #[test]
    fn string_rejects_invalid_utf8() {
        // ULEB128 length prefix 2, then two non-UTF-8 bytes.
        let buf = [2, 0xFF, 0xFE];
        let mut r = ArgReader::new(&buf);
        assert_eq!(r.read_string(), Err(AbiError::InvalidUtf8));
    }

    #[test]
    fn bool_round_trip() {
        rt_round(|w, v| w.write_bool(*v), |r| r.read_bool().unwrap(), true);
        rt_round(|w, v| w.write_bool(*v), |r| r.read_bool().unwrap(), false);
    }

    #[test]
    fn bool_rejects_garbage() {
        let buf = [3u8];
        let mut r = ArgReader::new(&buf);
        assert_eq!(r.read_bool(), Err(AbiError::InvalidBool(3)));
    }

    #[test]
    fn unexpected_eof_reports_need_and_have() {
        let buf = [1u8, 2];
        let mut r = ArgReader::new(&buf);
        assert_eq!(
            r.read_u32(),
            Err(AbiError::UnexpectedEof {
                needed: 4,
                available: 2,
            })
        );
    }

    #[test]
    fn expect_eof_detects_trailing() {
        let buf = [1u8, 2, 3];
        let r = ArgReader::new(&buf);
        assert_eq!(
            r.expect_eof(),
            Err(AbiError::TrailingBytes { remaining: 3 })
        );
    }

    #[test]
    fn expect_eof_passes_when_drained() {
        let mut w = RetWriter::new();
        w.write_u8(7);
        let buf = w.finish();
        let mut r = ArgReader::new(&buf);
        r.read_u8().unwrap();
        r.expect_eof().unwrap();
    }

    #[test]
    fn type_tag_round_trip_concrete() {
        let tag = TypeTag::Concrete {
            petal_hash: [0x11; 32],
            type_name: "Coin".to_string(),
            type_args: vec![TypeTag::Concrete {
                petal_hash: [0x22; 32],
                type_name: "USDC".to_string(),
                type_args: vec![],
            }],
        };
        let mut w = RetWriter::new();
        w.write_type_tag(&tag).unwrap();
        let buf = w.finish();
        let mut r = ArgReader::new(&buf);
        let got = r.read_type_tag().unwrap();
        r.expect_eof().unwrap();
        assert_eq!(got, tag);
    }

    #[test]
    fn type_tag_round_trip_generic() {
        let tag = TypeTag::Generic { idx: 0 };
        let mut w = RetWriter::new();
        w.write_type_tag(&tag).unwrap();
        let buf = w.finish();
        let mut r = ArgReader::new(&buf);
        assert_eq!(r.read_type_tag().unwrap(), tag);
        r.expect_eof().unwrap();
    }

    #[test]
    fn mixed_args_buffer_round_trip() {
        // Simulates: fn(addr: Address, amount: u128, handle: RuntimeHandle, name: String)
        let addr = [0xAB; 32];
        let amount: u128 = 1_000_000_000_000_000_000;
        let handle = RuntimeHandle::from_raw(42);
        let name = "swap_a_for_b".to_string();

        let mut w = RetWriter::new();
        w.write_address(&addr);
        w.write_u128(amount);
        w.write_handle(handle);
        w.write_string(&name);
        let buf = w.finish();

        let mut r = ArgReader::new(&buf);
        assert_eq!(r.read_address().unwrap(), addr);
        assert_eq!(r.read_u128().unwrap(), amount);
        assert_eq!(r.read_handle().unwrap(), handle);
        assert_eq!(r.read_string().unwrap(), name);
        r.expect_eof().unwrap();
    }

    #[test]
    fn ret_writer_len_and_is_empty() {
        let mut w = RetWriter::new();
        assert!(w.is_empty());
        assert_eq!(w.len(), 0);
        w.write_u64(1);
        assert!(!w.is_empty());
        assert_eq!(w.len(), 8);
    }

    #[test]
    fn ret_writer_with_capacity_does_not_change_output() {
        let mut a = RetWriter::with_capacity(64);
        let mut b = RetWriter::new();
        for w in [&mut a, &mut b] {
            w.write_u32(1);
            w.write_u32(2);
        }
        assert_eq!(a.finish(), b.finish());
    }

    #[test]
    fn arg_reader_remaining_decreases() {
        let mut w = RetWriter::new();
        w.write_u32(1);
        w.write_u32(2);
        let buf = w.finish();
        let mut r = ArgReader::new(&buf);
        assert_eq!(r.remaining(), 8);
        r.read_u32().unwrap();
        assert_eq!(r.remaining(), 4);
        r.read_u32().unwrap();
        assert_eq!(r.remaining(), 0);
    }

    // -----------------------------------------------------------------
    // CallArgsWriter / CallArgsReader — framed PTB calldata envelope
    // -----------------------------------------------------------------

    #[test]
    fn call_args_empty_envelope() {
        let buf = CallArgsWriter::new().finish();
        assert_eq!(buf, vec![0, 0, 0, 0]); // count = 0
        let r = CallArgsReader::new(&buf).unwrap();
        assert_eq!(r.declared_count(), 0);
        assert_eq!(r.remaining(), 0);
    }

    #[test]
    fn call_args_count_is_leading_be_u32() {
        let mut w = CallArgsWriter::new();
        w.push_signer(0);
        w.push_signer(1);
        let buf = w.finish();
        assert_eq!(&buf[..4], &[0, 0, 0, 2]); // count = 2
    }

    #[test]
    fn call_args_signer_round_trip() {
        let mut w = CallArgsWriter::new();
        w.push_signer(0x1234);
        let buf = w.finish();
        let mut r = CallArgsReader::new(&buf).unwrap();
        assert_eq!(r.declared_count(), 1);
        assert_eq!(r.next_signer().unwrap(), 0x1234);
        assert_eq!(r.remaining(), 0);
    }

    #[test]
    fn call_args_const_round_trip() {
        let payload = 0xDEAD_BEEF_u32.to_be_bytes();
        let mut w = CallArgsWriter::new();
        w.push_const(&payload);
        let buf = w.finish();
        let mut r = CallArgsReader::new(&buf).unwrap();
        assert_eq!(r.next_const_bytes().unwrap(), payload.to_vec());
    }

    #[test]
    fn call_args_object_round_trip() {
        let id = ObjectId([0x42; 32]);
        let mut w = CallArgsWriter::new();
        w.push_object(&id);
        let buf = w.finish();
        let mut r = CallArgsReader::new(&buf).unwrap();
        assert_eq!(r.next_object_id().unwrap(), id);
    }

    #[test]
    fn call_args_use_threads_object_id() {
        // A `Use` slot carrying a 32-byte upstream id decodes as Object.
        let id = ObjectId([0x7; 32]);
        let mut w = CallArgsWriter::new();
        w.push_use(&id.0);
        let buf = w.finish();
        let mut r = CallArgsReader::new(&buf).unwrap();
        assert_eq!(r.next_object_id().unwrap(), id);
    }

    #[test]
    fn call_args_use_wrong_len_is_rejected_as_object() {
        let mut w = CallArgsWriter::new();
        w.push_use(&[1, 2, 3]); // not 32 bytes
        let buf = w.finish();
        let mut r = CallArgsReader::new(&buf).unwrap();
        assert_eq!(r.next_object_id(), Err(AbiError::BadObjectIdLen(3)));
    }

    #[test]
    fn call_args_type_arg_round_trip() {
        let tag = TypeTag::Concrete {
            petal_hash: [0x11; 32],
            type_name: "USDC".to_string(),
            type_args: vec![],
        };
        let mut w = CallArgsWriter::new();
        w.push_type_arg(&tag).unwrap();
        let buf = w.finish();
        let mut r = CallArgsReader::new(&buf).unwrap();
        assert_eq!(r.next_type_arg().unwrap(), tag);
    }

    #[test]
    fn call_args_rejects_trailing_slots() {
        let mut w = CallArgsWriter::new();
        w.push_signer(7);
        w.push_signer(8);
        let buf = w.finish();
        let mut r = CallArgsReader::new(&buf).unwrap();
        assert_eq!(r.next_signer().unwrap(), 7);
        assert_eq!(
            r.expect_finished(),
            Err(AbiError::UnexpectedEof {
                needed: 1,
                available: 0
            })
        );
    }

    #[test]
    fn call_args_rejects_trailing_bytes_after_counted_slots() {
        let mut buf = CallArgsWriter::new().finish();
        buf.push(ARG_TAG_SIGNER);
        let r = CallArgsReader::new(&buf).unwrap();
        assert_eq!(
            r.expect_finished(),
            Err(AbiError::TrailingBytes { remaining: 1 })
        );
    }

    #[test]
    fn call_args_tag_mismatch_is_reported() {
        // Push a Signer, try to read it as an Object.
        let mut w = CallArgsWriter::new();
        w.push_signer(3);
        let buf = w.finish();
        let mut r = CallArgsReader::new(&buf).unwrap();
        assert_eq!(
            r.next_object_id(),
            Err(AbiError::ArgTagMismatch {
                expected: ARG_TAG_OBJECT,
                got: ARG_TAG_SIGNER,
            })
        );
    }

    #[test]
    fn call_args_mixed_envelope_round_trip() {
        // Mirrors a generic swap call:
        //   type:Coin<USDC> | signer:0 | obj:pool | const:amount
        let type_tag = TypeTag::Generic { idx: 0 };
        let pool = ObjectId([0x9; 32]);
        let amount = 1_000_000u128.to_be_bytes();

        let mut w = CallArgsWriter::new();
        w.push_type_arg(&type_tag).unwrap();
        w.push_signer(0);
        w.push_object(&pool);
        w.push_const(&amount);
        let buf = w.finish();

        let mut r = CallArgsReader::new(&buf).unwrap();
        assert_eq!(r.declared_count(), 4);
        assert_eq!(r.next_type_arg().unwrap(), type_tag);
        assert_eq!(r.next_signer().unwrap(), 0);
        assert_eq!(r.next_object_id().unwrap(), pool);
        assert_eq!(r.next_const_bytes().unwrap(), amount.to_vec());
        assert_eq!(r.remaining(), 0);
    }
}
