[package]
name = "beth-tx"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Tx engine, intent parser, policy for bloom-eth"

[dependencies]
beth-proto.workspace = true
beth-chain.workspace = true
beth-rpc.workspace = true
beth-keystore.workspace = true
beth-mempool.workspace = true
beth-tools.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
thiserror.workspace = true
anyhow.workspace = true
hex.workspace = true
tokio.workspace = true
tracing.workspace = true
alloy.workspace = true
parking_lot.workspace = true
async-trait.workspace = true

[dev-dependencies]
tempfile.workspace = true
