//! bloom-dex-wloom — Wrapped LOOM (wLOOM) petal for bloom-chain DEX.
//!
//! Mirrors WETH9 semantics: wraps native LOOM as an ERC-20 token.
//! Single global deployment per DEX; its address is baked into router init.
//!
//! ## Constants
//! - `name`    = "Wrapped LOOM"
//! - `symbol`  = "wLOOM"
//! - `decimals` = 18
//!
//! ## init
//! No parameters. Writes `total_supply = 0` (idempotent no-op since unset
//! storage reads as zero). Name/symbol/decimals are hardcoded; they do not
//! need to be stored.
//!
//! ## Storage layout
//! Declared inside the `contract!` block below.
//! - `wloom.total_supply`               → U256
//! - `wloom.balance:` || addr           → U256
//! - `wloom.allowance:` || owner || sp  → U256
//!
//! ## ABI surface
//! The wLOOM-specific methods `wloom.deposit()` and `wloom.withdraw(u256)`
//! are generated by the chain-owned `bloom_chain_abi::contract!` macro
//! (selectors / calldata / dispatcher). The standard ERC-20 surface
//! (`name` / `symbol` / `decimals` / `total_supply` / `balance_of` /
//! `allowance` / `transfer` / `transfer_from` / `approve`) uses the
//! canonical `erc20.*` signatures so peer DEX petals can call wLOOM with
//! the same `erc20::abi::call::*` calldata they use for any other ERC-20
//! petal. Those selectors are computed at runtime from canonical signature
//! strings via `bloom_chain_abi::selector` and hand-dispatched ahead of
//! `wloom::dispatch`.
//!
//! ## Events
//! Declared inside the `contract!` block.
//! - `Transfer(#[indexed] from, #[indexed] to, value)` — same signature
//!   string as ERC-20 `Transfer(address,address,u256)`, so topic0 matches
//!   any peer ERC-20 token's `Transfer` event byte-for-byte.
//! - `Approval(#[indexed] owner, #[indexed] spender, value)` — likewise.
//! - `Deposit(#[indexed] dst, value)`.
//! - `Withdrawal(#[indexed] src, value)`.
//!
//! Deposit also emits `Transfer(0x0, dst, value)` as a mint signal;
//! Withdrawal also emits `Transfer(src, 0x0, value)` as a burn signal.

#![cfg_attr(target_arch = "wasm32", no_std)]

extern crate alloc;

use alloc::vec::Vec;

use bloom_chain_abi::{DispatchError, U256, contract};
use bloom_petal_sdk::{msg, petal, LoomValue};

// ---------------------------------------------------------------------------
// Chain-owned ABI declaration — storage, events, deposit/withdraw surface.
// ---------------------------------------------------------------------------
//
// The standard ERC-20 surface lives outside the macro (canonical signatures
// are `erc20.*`, not `wloom.*`) and is hand-dispatched in `do_call` below.

contract! {
    contract Wloom {
        storage {
            total_supply: U256                              @ "wloom.total_supply";
            balances:     Mapping<Address, U256>            @ "wloom.balance:";
            allowances:   Mapping<(Address, Address), U256> @ "wloom.allowance:";
        }

        event Transfer(#[indexed] from: Address, #[indexed] to: Address, value: U256);
        event Approval(#[indexed] owner: Address, #[indexed] spender: Address, value: U256);
        event Deposit(#[indexed] dst: Address, value: U256);
        event Withdrawal(#[indexed] src: Address, value: U256);

        fn deposit();
        fn withdraw(amount: U256);
    }
}

// ---------------------------------------------------------------------------
// U256::MAX sentinel for unlimited allowance.
// ---------------------------------------------------------------------------

const U256_MAX: U256 = U256([0xff; 32]);

// ---------------------------------------------------------------------------
// ERC-20 metadata constants
// ---------------------------------------------------------------------------

/// Name "Wrapped LOOM" as a NUL-right-padded bytes32.
fn name_bytes32() -> [u8; 32] {
    let s = b"Wrapped LOOM";
    let mut b = [0u8; 32];
    b[..s.len()].copy_from_slice(s);
    b
}

/// Symbol "wLOOM" as a NUL-right-padded bytes32.
fn symbol_bytes32() -> [u8; 32] {
    let s = b"wLOOM";
    let mut b = [0u8; 32];
    b[..s.len()].copy_from_slice(s);
    b
}

/// `decimals = 18` as a single byte (returned directly, not in a 32-byte slot).
const DECIMALS: u8 = 18;

// ---------------------------------------------------------------------------
// Canonical ERC-20 selectors — derived from the same hashing rule the macro
// uses, so they stay anchored to the canonical signature strings.
// ---------------------------------------------------------------------------

fn sel_name() -> [u8; 4] { bloom_chain_abi::selector("erc20.name()") }
fn sel_symbol() -> [u8; 4] { bloom_chain_abi::selector("erc20.symbol()") }
fn sel_decimals() -> [u8; 4] { bloom_chain_abi::selector("erc20.decimals()") }
fn sel_total_supply() -> [u8; 4] { bloom_chain_abi::selector("erc20.total_supply()") }
fn sel_balance_of() -> [u8; 4] { bloom_chain_abi::selector("erc20.balance_of(address)") }
fn sel_allowance() -> [u8; 4] {
    bloom_chain_abi::selector("erc20.allowance(address,address)")
}
fn sel_transfer() -> [u8; 4] { bloom_chain_abi::selector("erc20.transfer(address,u256)") }
fn sel_transfer_from() -> [u8; 4] {
    bloom_chain_abi::selector("erc20.transfer_from(address,address,u256)")
}
fn sel_approve() -> [u8; 4] { bloom_chain_abi::selector("erc20.approve(address,u256)") }

// ---------------------------------------------------------------------------
// Internal transfer (balance accounting, no events)
// ---------------------------------------------------------------------------

fn transfer_raw(from: &[u8; 32], to: &[u8; 32], amount: U256) {
    let from_bal = wloom::abi::storage::balances::get(from);
    let new_from = from_bal
        .checked_sub(amount)
        .unwrap_or_else(|| petal::revert("wloom: insufficient balance"));
    wloom::abi::storage::balances::set(from, &new_from);

    let to_bal = wloom::abi::storage::balances::get(to);
    let new_to = to_bal
        .checked_add(amount)
        .unwrap_or_else(|| petal::revert("wloom: balance overflow"));
    wloom::abi::storage::balances::set(to, &new_to);
}

// ---------------------------------------------------------------------------
// Hand-dispatched ERC-20 handlers. Each one diverges via
// `petal::return_data` / `petal::revert`.
// ---------------------------------------------------------------------------

fn handle_total_supply() -> ! {
    let ts = wloom::abi::storage::total_supply();
    petal::return_data(&ts.0);
}

fn handle_balance_of(args: &[u8]) -> ! {
    if args.len() != 32 {
        petal::revert("wloom: bad balance_of args");
    }
    let mut addr = [0u8; 32];
    addr.copy_from_slice(args);
    let bal = wloom::abi::storage::balances::get(&addr);
    petal::return_data(&bal.0);
}

fn handle_allowance(args: &[u8]) -> ! {
    if args.len() != 64 {
        petal::revert("wloom: bad allowance args");
    }
    let mut owner = [0u8; 32];
    owner.copy_from_slice(&args[..32]);
    let mut spender = [0u8; 32];
    spender.copy_from_slice(&args[32..]);
    let allow = wloom::abi::storage::allowances::get((&owner, &spender));
    petal::return_data(&allow.0);
}

fn handle_name() -> ! { petal::return_data(&name_bytes32()); }
fn handle_symbol() -> ! { petal::return_data(&symbol_bytes32()); }
fn handle_decimals() -> ! { petal::return_data(&[DECIMALS]); }

fn handle_approve(args: &[u8]) -> ! {
    if args.len() != 64 {
        petal::revert("wloom: bad approve args");
    }
    let mut spender = [0u8; 32];
    spender.copy_from_slice(&args[..32]);
    let mut amount_bytes = [0u8; 32];
    amount_bytes.copy_from_slice(&args[32..]);
    let amount = U256(amount_bytes);
    let owner = msg::sender();
    wloom::abi::storage::allowances::set((&owner, &spender), &amount);
    wloom::abi::events::emit_approval(&owner, &spender, &amount);
    petal::return_data(&[1u8]);
}

fn handle_transfer(args: &[u8]) -> ! {
    if args.len() != 64 {
        petal::revert("wloom: bad transfer args");
    }
    let mut to = [0u8; 32];
    to.copy_from_slice(&args[..32]);
    let mut amount_bytes = [0u8; 32];
    amount_bytes.copy_from_slice(&args[32..]);
    let amount = U256(amount_bytes);
    let from = msg::sender();
    transfer_raw(&from, &to, amount);
    wloom::abi::events::emit_transfer(&from, &to, &amount);
    petal::return_data(&[1u8]);
}

fn handle_transfer_from(args: &[u8]) -> ! {
    if args.len() != 96 {
        petal::revert("wloom: bad transfer_from args");
    }
    let mut from = [0u8; 32];
    from.copy_from_slice(&args[..32]);
    let mut to = [0u8; 32];
    to.copy_from_slice(&args[32..64]);
    let mut amount_bytes = [0u8; 32];
    amount_bytes.copy_from_slice(&args[64..]);
    let amount = U256(amount_bytes);
    let spender = msg::sender();

    // Check and reduce allowance. U256::MAX = infinite (skip deduction).
    let current = wloom::abi::storage::allowances::get((&from, &spender));
    if current != U256_MAX {
        let new_allow = current
            .checked_sub(amount)
            .unwrap_or_else(|| petal::revert("wloom: insufficient allowance"));
        wloom::abi::storage::allowances::set((&from, &spender), &new_allow);
    }

    transfer_raw(&from, &to, amount);
    wloom::abi::events::emit_transfer(&from, &to, &amount);
    petal::return_data(&[1u8]);
}

// ---------------------------------------------------------------------------
// Handler — wloom.deposit() / wloom.withdraw(u256) via the chain-ABI macro.
// ---------------------------------------------------------------------------

struct WloomHandler;

impl wloom::Handler for WloomHandler {
    /// `wloom.deposit()` — payable.
    ///
    /// Credits `msg.sender` with `msg.value` wLOOM and increments total supply.
    /// Emits `Deposit(sender, value)` plus `Transfer(0x0, sender, value)` as a
    /// mint signal. `msg.value == 0` is a no-op.
    fn deposit(&mut self) -> Result<(), &'static str> {
        let sender = msg::sender();
        let value = msg::value();
        let amount = U256::from_u128(value.to_u128());

        if !amount.is_zero() {
            let ts = wloom::abi::storage::total_supply();
            let new_ts = ts
                .checked_add(amount)
                .ok_or("wloom: total supply overflow")?;
            wloom::abi::storage::set_total_supply(&new_ts);

            let bal = wloom::abi::storage::balances::get(&sender);
            let new_bal = bal.checked_add(amount).ok_or("wloom: balance overflow")?;
            wloom::abi::storage::balances::set(&sender, &new_bal);

            wloom::abi::events::emit_deposit(&sender, &amount);
            wloom::abi::events::emit_transfer(&[0u8; 32], &sender, &amount);
        }
        Ok(())
    }

    /// `wloom.withdraw(amount: u256)`.
    ///
    /// Debits `amount` from `msg.sender`, decrements total supply, emits
    /// `Withdrawal(sender, amount)` and `Transfer(sender, 0x0, amount)` (burn),
    /// then sends native LOOM to `msg.sender` via empty-calldata
    /// `petal::call`. Reverts on insufficient balance, on a >u128 amount, or
    /// if the native LOOM transfer fails.
    fn withdraw(&mut self, amount: U256) -> Result<(), &'static str> {
        if amount.is_zero() {
            return Ok(());
        }
        let sender = msg::sender();

        let bal = wloom::abi::storage::balances::get(&sender);
        let new_bal = bal
            .checked_sub(amount)
            .ok_or("wloom: insufficient balance")?;
        wloom::abi::storage::balances::set(&sender, &new_bal);

        let ts = wloom::abi::storage::total_supply();
        let new_ts = ts
            .checked_sub(amount)
            .ok_or("wloom: total supply underflow")?;
        wloom::abi::storage::set_total_supply(&new_ts);

        wloom::abi::events::emit_withdrawal(&sender, &amount);
        wloom::abi::events::emit_transfer(&sender, &[0u8; 32], &amount);

        // wLOOM mints are gated through deposits, so balances always fit in
        // u128 (the native LOOM type); the explicit conversion guards any
        // future code path that could put a >u128 amount here.
        let value = LoomValue::try_from_be_u256_bytes(&amount.0)
            .map_err(|_| "wloom: withdraw amount exceeds u128")?;
        let result = petal::call(&sender, &[], value);
        if result.is_err() {
            return Err("wloom: native LOOM transfer failed");
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Petal entry points
// ---------------------------------------------------------------------------

bloom_petal_sdk::petal! {
    init => do_init,
    call => do_call,
}

/// `init` — no parameters. Writes `total_supply = 0` to mark the petal as
/// initialised. Name/symbol/decimals are hardcoded constants and not stored.
fn do_init(_calldata: Vec<u8>) {
    wloom::abi::storage::set_total_supply(&U256::ZERO);
}

/// `call` — dispatches on the 4-byte selector.
///
/// Routing order:
/// 1. `calldata.len() < 4` → run the `deposit` handler (receive-LOOM fallback
///    per DEX spec §7).
/// 2. Hand-dispatch the standard ERC-20 selectors (canonical `erc20.*` names).
/// 3. Otherwise defer to `wloom::dispatch` for `wloom.deposit()` /
///    `wloom.withdraw(u256)`.
fn do_call(calldata: Vec<u8>) -> i32 {
    if calldata.len() < 4 {
        // Empty / short calldata → deposit fallback.
        run_deposit_fallback();
    }

    let sel: [u8; 4] = [calldata[0], calldata[1], calldata[2], calldata[3]];
    let args = &calldata[4..];

    if sel == sel_total_supply() {
        if !args.is_empty() {
            petal::revert("wloom: total_supply: trailing calldata bytes");
        }
        handle_total_supply();
    }
    if sel == sel_balance_of() { handle_balance_of(args); }
    if sel == sel_allowance() { handle_allowance(args); }
    if sel == sel_name() {
        if !args.is_empty() {
            petal::revert("wloom: name: trailing calldata bytes");
        }
        handle_name();
    }
    if sel == sel_symbol() {
        if !args.is_empty() {
            petal::revert("wloom: symbol: trailing calldata bytes");
        }
        handle_symbol();
    }
    if sel == sel_decimals() {
        if !args.is_empty() {
            petal::revert("wloom: decimals: trailing calldata bytes");
        }
        handle_decimals();
    }
    if sel == sel_approve() { handle_approve(args); }
    if sel == sel_transfer() { handle_transfer(args); }
    if sel == sel_transfer_from() { handle_transfer_from(args); }

    // None of the ERC-20 selectors matched — defer to the macro dispatcher.
    let mut handler = WloomHandler;
    let caller = msg::sender();
    match wloom::dispatch(&mut handler, &caller, &calldata) {
        Ok(data) => petal::return_data(&data),
        Err(DispatchError::ShortCalldata) => petal::revert("wloom: calldata too short"),
        Err(DispatchError::UnknownSelector(_)) => petal::revert("wloom: unknown selector"),
        Err(DispatchError::Decode(_)) => petal::revert("wloom: bad args"),
        Err(DispatchError::Unauthorized) => petal::revert("wloom: unauthorized"),
        Err(DispatchError::Handler(msg)) => petal::revert(msg),
    }
}

/// Invoke the `deposit` handler directly for the bare-LOOM-transfer fallback
/// (calldata shorter than the 4-byte selector window).
fn run_deposit_fallback() -> ! {
    let mut handler = WloomHandler;
    match wloom::Handler::deposit(&mut handler) {
        Ok(()) => petal::return_data(&[]),
        Err(msg) => petal::revert(msg),
    }
}

// ---------------------------------------------------------------------------
// Host-target unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests;
