pub mod addressbook;
pub mod chains;
pub mod chains_contracts;
mod chains_history;
mod chains_nfts;
pub mod defi;
pub mod docs;
pub mod ens;
pub mod prices;
pub mod simulate;
pub mod status;
pub mod tools;
pub mod wallets;
pub mod watch;

pub use addressbook::AddressBookHandler;
pub use chains::ChainsHandler;
pub use defi::DefiHandler;
pub use docs::DocsHandler;
pub use ens::EnsHandler;
pub use prices::PricesHandler;
pub use simulate::SimulateHandler;
pub use status::StatusHandler;
pub use tools::ToolsHandler;
pub use wallets::WalletsHandler;
pub use watch::WatchHandler;
