//! `#[object]` struct attribute (spec §4 / §11.3).
//!
//! Recognised forms:
//! ```ignore
//! #[object]                                   // abilities = "key"
//! #[object(abilities = "key, store")]
//! #[object(abilities = "key, store, copy, drop")]
//! #[object(no_abilities)]                     // phantom witness types
//! #[object(phantom = "T, U")]                 // phantom generic params
//! ```
//!
//! The macro:
//! 1. Validates the ability list against the bitfield in
//!    `bloom_objects::AbilitySet`.
//! 2. Parses an optional `phantom = "T, U"` attribute, treating those
//!    generic params as `TypeParamKind::Phantom` (manifest only).
//! 3. Builds an [`ObjectTypeDecl`] for emission later by `#[bloom::petal]`.
//! 4. Re-emits the struct unchanged, with an autogenerated impl of
//!    [`crate::object_marker::BloomObject`] (just a marker trait).
//!
//! The full manifest assembly happens at the petal level — `#[object]`
//! only records *one* object decl into a thread-local registry consumed
//! by `#[bloom::petal]`. For this phase the recorded decl is also
//! exposed via a per-struct `const __BLOOM_OBJECT_DECL_<NAME>: &str = …`
//! debug string so host-side tests can introspect what the macro saw.

use bloom_objects::AbilitySet;
use proc_macro2::TokenStream;
use quote::quote;
use syn::{Attribute, Fields, GenericParam, ItemStruct, Meta};

use syn::spanned::Spanned;

use crate::ast::{attr_is_named, ident, parse_ident_list, parse_str_value, struct_name};
use crate::error::err_spanned;
use crate::type_tag::TypeTagCtx;
use bloom_petal_manifest::types::{FieldDecl, ObjectTypeDecl, TypeParamDecl, TypeParamKind};

/// Output of parsing an `#[object(...)]` attribute on a struct.
#[derive(Debug, Clone, Default)]
pub(crate) struct ObjectAttr {
    /// Explicit ability list (`AbilitySet::default()` if unset).
    pub abilities: Option<AbilitySet>,
    /// `no_abilities` flag — overrides everything.
    pub no_abilities: bool,
    /// Generic-param names declared with `phantom = "T, U"`.
    pub phantom: Vec<String>,
}

impl ObjectAttr {
    /// Parse `attr` (the bare `(abilities = "...", phantom = "...")`
    /// tokens) into a structured form.
    pub fn parse(attr: TokenStream) -> syn::Result<Self> {
        // Wrap the bare meta into `#[object(<attr>)]` so we can reuse
        // `Attribute::parse_outer`. If `attr` is empty we get default.
        if attr.is_empty() {
            return Ok(Self::default());
        }
        let attr_text = format!("#[object({})]", attr);
        let attrs: Vec<Attribute> =
            syn::parse::Parser::parse_str(Attribute::parse_outer, &attr_text)?;
        let outer = attrs.into_iter().next().ok_or_else(|| {
            syn::Error::new(proc_macro2::Span::call_site(), "expected `#[object(...)]`")
        })?;
        let mut out = Self::default();
        // Inside the `(...)` we might see `no_abilities`, `abilities =
        // "..."`, `phantom = "..."`.
        if let Meta::List(list) = &outer.meta {
            let nested = list.parse_args_with(
                syn::punctuated::Punctuated::<Meta, syn::Token![,]>::parse_terminated,
            )?;
            for meta in nested {
                match &meta {
                    Meta::Path(p) if p.is_ident("no_abilities") => {
                        out.no_abilities = true;
                    }
                    Meta::NameValue(nv) if nv.path.is_ident("abilities") => {
                        let raw = parse_str_value(nv)?;
                        out.abilities = Some(parse_abilities(&raw, &nv.value)?);
                    }
                    Meta::NameValue(nv) if nv.path.is_ident("phantom") => {
                        let raw = parse_str_value(nv)?;
                        out.phantom = parse_ident_list(&raw, nv.value.span())?;
                    }
                    other => {
                        return Err(err_spanned(
                            other,
                            "unknown #[object] argument; expected `abilities`, `phantom`, or `no_abilities`",
                        ));
                    }
                }
            }
        }
        // Sanity: `no_abilities` and `abilities` are mutually exclusive.
        if out.no_abilities && out.abilities.is_some() {
            return Err(syn::Error::new(
                proc_macro2::Span::call_site(),
                "`#[object(no_abilities)]` cannot be combined with `abilities = ...`",
            ));
        }
        Ok(out)
    }

    /// Resolve the final `AbilitySet` for the struct.
    pub fn resolved_abilities(&self) -> AbilitySet {
        if self.no_abilities {
            return AbilitySet::from_bits(0);
        }
        self.abilities
            .unwrap_or_else(|| AbilitySet::from_bits(AbilitySet::KEY))
    }
}

/// Parse an ability list string like `"key, store, copy"` into an
/// `AbilitySet`. Delegates to `AbilitySet::from_str_list`.
fn parse_abilities(raw: &str, span: &impl syn::spanned::Spanned) -> syn::Result<AbilitySet> {
    AbilitySet::from_str_list(raw)
        .map_err(|e| syn::Error::new(span.span(), format!("invalid ability list: {}", e)))
}

/// Build the [`ObjectTypeDecl`] that the petal-level macro will fold
/// into the manifest. Used in tests and (transitively) from
/// [`expand`].
pub(crate) fn build_decl(item: &ItemStruct, attr: &ObjectAttr) -> syn::Result<ObjectTypeDecl> {
    let name = struct_name(item);

    // Generic-param list, in declaration order.
    let mut type_params = Vec::<TypeParamDecl>::new();
    let mut generic_names = Vec::<String>::new();
    for p in &item.generics.params {
        if let GenericParam::Type(t) = p {
            let n = t.ident.to_string();
            let kind = if attr.phantom.iter().any(|p| p == &n) {
                TypeParamKind::Phantom
            } else {
                TypeParamKind::Resource
            };
            type_params.push(TypeParamDecl {
                name: n.clone(),
                kind,
                bounds: Vec::new(),
            });
            generic_names.push(n);
        }
    }

    // Validate every `phantom = "..."` name actually appears in the
    // struct generics.
    for declared in &attr.phantom {
        if !generic_names.iter().any(|n| n == declared) {
            return Err(syn::Error::new(
                item.ident.span(),
                format!(
                    "phantom parameter `{}` is not a generic of `{}`",
                    declared, name
                ),
            ));
        }
    }

    // Non-phantom generic-param names — for payload validation.
    let non_phantom: Vec<String> = type_params
        .iter()
        .filter(|p| matches!(p.kind, TypeParamKind::Resource))
        .map(|p| p.name.clone())
        .collect();

    // Lower each field to a `FieldDecl`.
    let ctx = TypeTagCtx::from_generic_names(generic_names.iter().cloned());
    let mut fields = Vec::<FieldDecl>::new();
    let field_iter: Box<dyn Iterator<Item = (&syn::Field, usize)>> = match &item.fields {
        Fields::Named(named) => Box::new(named.named.iter().enumerate().map(|(i, f)| (f, i))),
        Fields::Unnamed(unnamed) => {
            Box::new(unnamed.unnamed.iter().enumerate().map(|(i, f)| (f, i)))
        }
        Fields::Unit => Box::new(std::iter::empty()),
    };
    // Running byte offset for the fixed-width prefix (ADR-011). `None`
    // once any preceding field is variable-width: every field from that
    // point on is not statically addressable.
    let mut running_offset: Option<u32> = Some(0);
    for (field, i) in field_iter {
        if crate::bloom_type::is_phantom_data_type(&field.ty) {
            continue;
        }
        // Reject plain `T` in field position unless wrapped in
        // `Resource<T>` (spec §11.2).
        crate::type_tag::reject_plain_generic_in_payload(&field.ty, &non_phantom)?;
        let field_name = field
            .ident
            .as_ref()
            .map(|i| i.to_string())
            .unwrap_or_else(|| i.to_string());
        let ty = ctx.lower(&field.ty)?;
        let width = bloom_petal_manifest::types::canonical_byte_width(&ty);
        // A field is addressable only while it *and* every preceding
        // field have a known fixed width.
        let offset = running_offset;
        running_offset = match (running_offset, width) {
            (Some(off), Some(w)) => Some(off + w),
            _ => None,
        };
        fields.push(FieldDecl {
            name: field_name,
            ty,
            offset: offset.filter(|_| width.is_some()),
            width,
        });
    }

    Ok(ObjectTypeDecl {
        name,
        abilities: attr.resolved_abilities(),
        type_params,
        fields,
    })
}

/// Macro entry: parse the input, validate, and re-emit the struct
/// (currently unchanged; manifest assembly happens at petal level).
pub(crate) fn expand(attr: TokenStream, item: TokenStream) -> syn::Result<TokenStream> {
    let parsed: ItemStruct = syn::parse2(item)?;
    let attr = ObjectAttr::parse(attr)?;
    let _decl = build_decl(&parsed, &attr)?;

    // Strip the `#[object]` self-attribute if it lingered.
    let mut output = parsed.clone();
    output.attrs.retain(|a| !attr_is_named(a, "object"));

    // Emit the struct unchanged plus a marker fn that records the
    // ability bits. The marker fn is `pub(crate)` so it doesn't leak
    // outside the petal.
    let abilities_byte = attr.resolved_abilities().bits();
    let marker_ident = ident(
        &format!("__BLOOM_OBJECT_{}__ABILITIES", output.ident),
        proc_macro2::Span::call_site(),
    );
    let bloom_type_impl = crate::bloom_type::emit_struct_impl_for_item(&output, true)?;

    Ok(quote! {
        #output
        #bloom_type_impl

        /// Ability bits recorded by `#[object]`. The petal-level macro
        /// reads this when assembling the manifest. Auto-generated.
        #[allow(non_upper_case_globals, dead_code)]
        pub(crate) const #marker_ident: u8 = #abilities_byte;
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use quote::quote;

    fn parse_struct(toks: TokenStream) -> ItemStruct {
        syn::parse2(toks).unwrap()
    }

    #[test]
    fn parse_empty_attr_defaults_to_key() {
        let attr = ObjectAttr::parse(TokenStream::new()).unwrap();
        assert!(attr.resolved_abilities().has_key());
        assert!(!attr.resolved_abilities().has_store());
        assert!(!attr.no_abilities);
        assert!(attr.phantom.is_empty());
    }

    #[test]
    fn parse_abilities_full_set() {
        let attr = ObjectAttr::parse(quote! { abilities = "key, store, copy, drop" }).unwrap();
        let abilities = attr.resolved_abilities();
        assert!(abilities.has_key());
        assert!(abilities.has_store());
        assert!(abilities.has_copy());
        assert!(abilities.has_drop());
    }

    #[test]
    fn parse_abilities_rejects_unknown() {
        assert!(ObjectAttr::parse(quote! { abilities = "weird" }).is_err());
    }

    #[test]
    fn parse_no_abilities() {
        let attr = ObjectAttr::parse(quote! { no_abilities }).unwrap();
        assert!(attr.no_abilities);
        assert_eq!(attr.resolved_abilities().bits(), 0);
    }

    #[test]
    fn no_abilities_and_abilities_conflict() {
        assert!(ObjectAttr::parse(quote! { no_abilities, abilities = "key" }).is_err());
    }

    #[test]
    fn parse_phantom_list() {
        let attr = ObjectAttr::parse(quote! { phantom = "A, B" }).unwrap();
        assert_eq!(attr.phantom, vec!["A", "B"]);
    }

    #[test]
    fn build_decl_records_fields_and_abilities() {
        let s = parse_struct(quote! {
            pub struct Pool {
                id: UID,
                reserve_a: u128,
                reserve_b: u128,
            }
        });
        let attr = ObjectAttr::parse(quote! { abilities = "key, store" }).unwrap();
        let d = build_decl(&s, &attr).unwrap();
        assert_eq!(d.name, "Pool");
        assert_eq!(d.fields.len(), 3);
        assert_eq!(d.fields[0].name, "id");
        assert!(d.abilities.has_key());
        assert!(d.abilities.has_store());
    }

    #[test]
    fn build_decl_marks_phantom_generics() {
        let s = parse_struct(quote! {
            pub struct Coin<T> {
                id: UID,
                value: u128,
            }
        });
        let attr = ObjectAttr::parse(quote! { abilities = "key, store", phantom = "T" }).unwrap();
        let d = build_decl(&s, &attr).unwrap();
        assert_eq!(d.type_params.len(), 1);
        assert_eq!(d.type_params[0].name, "T");
        assert!(matches!(d.type_params[0].kind, TypeParamKind::Phantom));
    }

    #[test]
    fn build_decl_rejects_plain_generic_field() {
        let s = parse_struct(quote! {
            pub struct Bad<T> {
                id: UID,
                payload: T,
            }
        });
        let attr = ObjectAttr::parse(quote! {}).unwrap();
        assert!(build_decl(&s, &attr).is_err());
    }

    #[test]
    fn build_decl_accepts_resource_wrapped_generic() {
        let s = parse_struct(quote! {
            pub struct Boxed<T> {
                id: UID,
                payload: Resource<T>,
            }
        });
        let attr = ObjectAttr::parse(quote! {}).unwrap();
        let d = build_decl(&s, &attr).unwrap();
        assert_eq!(d.fields[1].name, "payload");
    }

    #[test]
    fn build_decl_rejects_phantom_param_not_in_generics() {
        let s = parse_struct(quote! {
            pub struct Pool {
                id: UID,
            }
        });
        let attr = ObjectAttr::parse(quote! { phantom = "T" }).unwrap();
        assert!(build_decl(&s, &attr).is_err());
    }

    #[test]
    fn expand_round_trip_emits_marker_const() {
        let item = quote! {
            pub struct Pool {
                id: UID,
                k_last: u128,
            }
        };
        let toks = expand(quote! { abilities = "key, store" }, item).unwrap();
        let s = toks.to_string();
        assert!(s.contains("__BLOOM_OBJECT_Pool__ABILITIES"));
        assert!(s.contains("u8"));
    }
}
