//! bloom-dex-factory — Uniswap-v2-style DEX factory petal.
//!
//! Keeps a registry of deployed pair petals and deploys new ones on demand
//! via `host.deploy` (chain spec §7.6).
//!
//! # Storage layout (declared via `storage { ... }` in `contract!` below)
//!
//! | Field              | Domain tag                                  | Value type     |
//! |--------------------|---------------------------------------------|----------------|
//! | `pair_petal_hash`  | `"factory.pair_petal_hash"`                 | bytes32        |
//! | `fee_to`           | `"factory.fee_to"`                          | Address        |
//! | `fee_to_setter`    | `"factory.fee_to_setter"`                   | Address        |
//! | `self_addr`        | `"factory.self"`     (explicit override)    | Address        |
//! | `all_pairs_len`    | `"factory.all_pairs.len"` (explicit override) | u64 BE       |
//! | `pair_of`          | `"factory.pair:" || t0 || t1`               | Address        |
//! | `all_pairs_at`     | `"factory.all_pairs:" || u64_be(i)`         | Address (raw)  |
//!
//! `pair_of` is stored for **both** orderings so `get_pair` is order-invariant.
//!
//! The `all_pairs_at` mapping uses an 8-byte big-endian `u64` index in its key
//! preimage. The chain-ABI macro's `Mapping<K, V>` DSL only accepts
//! `Address` / `U256` mapping keys in v0, so this single slot is derived via
//! a direct `bloom_chain_abi::storage::slot_mapping` call (the same helper the
//! macro itself uses) to preserve the existing on-disk key bytes.
//!
//! # ABI
//!
//! Selectors, calldata encoding, return packing, the init layout, storage
//! accessors, and event emitters are all generated by the chain-owned
//! `bloom_chain_abi::contract!` macro below. Method signatures (canonical
//! strings used for selector hashing) match the DEX v0 spec §4.1.

#![no_std]

extern crate alloc;

use alloc::vec::Vec;

use bloom_chain_abi::{DispatchError, contract, storage::slot_mapping};
use bloom_petal_sdk::{crypto, host, msg, petal};

// ---------------------------------------------------------------------------
// Chain-owned ABI declaration
// ---------------------------------------------------------------------------

contract! {
    contract Factory {
        storage {
            pair_petal_hash: Hash32;
            fee_to:          Address;
            fee_to_setter:   Address;
            self_addr:       Address @ "factory.self";
            all_pairs_len:   u64     @ "factory.all_pairs.len";

            pair_of: Mapping<(Address, Address), Address> @ "factory.pair:";
        }

        event PairCreated(
            #[indexed] token0: Address,
            #[indexed] token1: Address,
            pair: Address,
            all_pairs_length: u64,
        );

        init(pair_petal_hash: Hash32, fee_to_setter: Address, factory_self_addr: Address);

        fn create_pair(token_a: Address, token_b: Address) -> Address;
        fn get_pair(token_a: Address, token_b: Address) -> Address;
        fn all_pairs(index: u64) -> Address;
        fn all_pairs_length() -> u64;
        fn fee_to() -> Address;
        fn fee_to_setter() -> Address;
        fn set_fee_to(addr: Address);
        fn set_fee_to_setter(addr: Address);
    }
}

// ---------------------------------------------------------------------------
// Storage helpers for the u64-keyed `all_pairs_at` slot.
//
// The macro DSL does not accept `Mapping<u64, V>` in v0 (spec §A: keys are
// limited to {Address, U256, (Address, Address), (Address, U256)}). The pair
// registry's `index → pair_addr` lookup uses an 8-byte big-endian `u64` index
// as the mapping-key preimage, so we derive the slot via the same
// `bloom_chain_abi::storage::slot_mapping` helper the macro itself invokes.
// ---------------------------------------------------------------------------

const ALL_PAIRS_AT_TAG: &str = "factory.all_pairs:";

fn all_pairs_at_slot(i: u64) -> [u8; 32] {
    slot_mapping(ALL_PAIRS_AT_TAG, &i.to_be_bytes())
}

fn read_all_pairs_at(i: u64) -> [u8; 32] {
    bloom_petal_sdk::state::read(&all_pairs_at_slot(i)).unwrap_or([0u8; 32])
}

fn write_all_pairs_at(i: u64, addr: &[u8; 32]) {
    bloom_petal_sdk::state::write(&all_pairs_at_slot(i), addr);
}

// ---------------------------------------------------------------------------
// Pair sort + derivation helpers (pub for off-chain test pre-computation)
// ---------------------------------------------------------------------------

/// Sort two 32-byte addresses lexicographically; returns `(smaller, larger)`.
pub fn sort_tokens(a: &[u8; 32], b: &[u8; 32]) -> ([u8; 32], [u8; 32]) {
    if a <= b { (*a, *b) } else { (*b, *a) }
}

/// `salt = blake3("dex.pair.salt:" || t0 || t1)`. `t0` and `t1` must be sorted.
pub fn pair_salt(t0: &[u8; 32], t1: &[u8; 32]) -> [u8; 32] {
    let mut buf = Vec::with_capacity(14 + 32 + 32);
    buf.extend_from_slice(b"dex.pair.salt:");
    buf.extend_from_slice(t0);
    buf.extend_from_slice(t1);
    crypto::blake3(&buf)
}

/// Pre-compute the pair address via chain spec §7.7.
pub fn compute_pair_address(
    factory_addr: &[u8; 32],
    salt: &[u8; 32],
    pair_petal_hash: &[u8; 32],
) -> [u8; 32] {
    let prefix = b"bloom-chain.v0.addr:deploy:";
    let sep = b":";
    let mut preimage = Vec::with_capacity(prefix.len() + 32 + 1 + 32 + 1 + 32);
    preimage.extend_from_slice(prefix);
    preimage.extend_from_slice(factory_addr);
    preimage.extend_from_slice(sep);
    preimage.extend_from_slice(salt);
    preimage.extend_from_slice(sep);
    preimage.extend_from_slice(pair_petal_hash);
    crypto::blake3(&preimage)
}

const ZERO_ADDR: [u8; 32] = [0u8; 32];

// ---------------------------------------------------------------------------
// petal entry points (init + call wired into the macro-generated codec)
// ---------------------------------------------------------------------------

bloom_petal_sdk::petal! {
    init => do_init,
    call => do_call,
}

/// Decodes the 96-byte factory init payload via the chain-ABI codec and writes
/// the config slots. Strict decoding (any length other than 96 is rejected by
/// `factory::parse_init`).
///
/// Phase C: the legacy `reentrancy_addr` field has been removed from both the
/// pair's init payload and the factory's own init payload, since the
/// reentrancy guard moved into `#[nonreentrant]` (no separate reentrancy
/// petal). The factory init shrinks from 128 → 96 bytes.
fn do_init(calldata: alloc::vec::Vec<u8>) {
    let args = match factory::parse_init(&calldata) {
        Ok(a) => a,
        Err(_) => petal::revert("factory: init: calldata must be 96 bytes"),
    };

    factory::abi::storage::set_pair_petal_hash(&args.pair_petal_hash);
    factory::abi::storage::set_fee_to(&ZERO_ADDR);
    factory::abi::storage::set_fee_to_setter(&args.fee_to_setter);
    factory::abi::storage::set_self_addr(&args.factory_self_addr);
    factory::abi::storage::set_all_pairs_len(0);
}

/// Routes a method call through the macro-generated dispatcher and translates
/// the typed result into the petal-SDK return / revert ABI.
fn do_call(calldata: alloc::vec::Vec<u8>) -> i32 {
    let mut handler = FactoryHandler;
    let caller = msg::sender();
    match factory::dispatch(&mut handler, &caller, &calldata) {
        Ok(data) => petal::return_data(&data),
        Err(DispatchError::ShortCalldata) => petal::revert("factory: calldata too short"),
        Err(DispatchError::UnknownSelector(_)) => petal::revert("factory: unknown selector"),
        Err(DispatchError::Decode(_)) => petal::revert("factory: bad args"),
        Err(DispatchError::Unauthorized) => petal::revert("factory: unauthorized"),
        Err(DispatchError::Handler(msg)) => petal::revert(msg),
    }
}

// ---------------------------------------------------------------------------
// Handler — pure business logic against the chain-owned ABI shape
// ---------------------------------------------------------------------------

struct FactoryHandler;

impl factory::Handler for FactoryHandler {
    fn create_pair(
        &mut self,
        token_a: [u8; 32],
        token_b: [u8; 32],
    ) -> Result<[u8; 32], &'static str> {
        if token_a == token_b {
            return Err("factory: identical addresses");
        }

        let (t0, t1) = sort_tokens(&token_a, &token_b);
        if t0 == ZERO_ADDR {
            return Err("factory: zero address");
        }

        if factory::abi::storage::pair_of::get((&t0, &t1)) != ZERO_ADDR {
            return Err("factory: pair exists");
        }

        let salt = pair_salt(&t0, &t1);
        let pair_hash = factory::abi::storage::pair_petal_hash();
        let factory_self = factory::abi::storage::self_addr();
        let precomputed_pair_addr = compute_pair_address(&factory_self, &salt, &pair_hash);

        // Pair init: t0 || t1 || pair_self_addr (96 bytes).
        //
        // The pair's init payload is a raw `host.deploy` blob (not a
        // selector-dispatched method call), so we build it inline rather than
        // pulling in `bloom-dex-pair` as an rlib dep just to call
        // `pair::init_calldata`. The format is byte-identical to that helper
        // and is asserted in the `pair_init_payload_is_exactly_96_bytes` test
        // below.
        //
        // The pre-Phase-B layout included a `reentrancy_addr` field; that field
        // was dropped when the pair's reentrancy guard moved into the language
        // via `#[nonreentrant]`. Phase C removes the matching `reentrancy_addr`
        // slot from the factory's own state and `init(...)` signature.
        let mut init_calldata = Vec::with_capacity(96);
        init_calldata.extend_from_slice(&t0);
        init_calldata.extend_from_slice(&t1);
        init_calldata.extend_from_slice(&precomputed_pair_addr);

        let pair_addr = host::deploy(&pair_hash, &salt, &init_calldata)
            .map_err(|_| "factory: deploy failed")?;

        // Store pair in both directions; append to allPairs.
        factory::abi::storage::pair_of::set((&t0, &t1), &pair_addr);
        factory::abi::storage::pair_of::set((&t1, &t0), &pair_addr);

        let count = factory::abi::storage::all_pairs_len();
        write_all_pairs_at(count, &pair_addr);
        let new_count = count + 1;
        factory::abi::storage::set_all_pairs_len(new_count);

        // Emit PairCreated(t0, t1, pair_addr, allPairsLength).
        factory::abi::events::emit_pair_created(&t0, &t1, &pair_addr, new_count);

        Ok(pair_addr)
    }

    fn get_pair(
        &mut self,
        token_a: [u8; 32],
        token_b: [u8; 32],
    ) -> Result<[u8; 32], &'static str> {
        let (t0, t1) = sort_tokens(&token_a, &token_b);
        Ok(factory::abi::storage::pair_of::get((&t0, &t1)))
    }

    fn all_pairs(&mut self, index: u64) -> Result<[u8; 32], &'static str> {
        let count = factory::abi::storage::all_pairs_len();
        if index >= count {
            return Err("factory: allPairs: index out of bounds");
        }
        Ok(read_all_pairs_at(index))
    }

    fn all_pairs_length(&mut self) -> Result<u64, &'static str> {
        Ok(factory::abi::storage::all_pairs_len())
    }

    fn fee_to(&mut self) -> Result<[u8; 32], &'static str> {
        Ok(factory::abi::storage::fee_to())
    }

    fn fee_to_setter(&mut self) -> Result<[u8; 32], &'static str> {
        Ok(factory::abi::storage::fee_to_setter())
    }

    fn set_fee_to(&mut self, addr: [u8; 32]) -> Result<(), &'static str> {
        let setter = factory::abi::storage::fee_to_setter();
        if msg::sender() != setter {
            return Err("factory: setFeeTo: not feeToSetter");
        }
        factory::abi::storage::set_fee_to(&addr);
        Ok(())
    }

    fn set_fee_to_setter(&mut self, addr: [u8; 32]) -> Result<(), &'static str> {
        let setter = factory::abi::storage::fee_to_setter();
        if msg::sender() != setter {
            return Err("factory: setFeeToSetter: not feeToSetter");
        }
        factory::abi::storage::set_fee_to_setter(&addr);
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Tests (host-side, non-wasm32 only)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sort_tokens_already_sorted() {
        let a = [0u8; 32];
        let mut b = [0u8; 32];
        b[31] = 1;
        let (t0, t1) = sort_tokens(&a, &b);
        assert_eq!(t0, a);
        assert_eq!(t1, b);
    }

    #[test]
    fn sort_tokens_reversed() {
        let mut a = [0u8; 32];
        a[31] = 5;
        let b = [0u8; 32];
        let (t0, t1) = sort_tokens(&a, &b);
        assert_eq!(t0, b);
        assert_eq!(t1, a);
    }

    #[test]
    fn sort_tokens_is_commutative() {
        let mut a = [0u8; 32];
        a[0] = 0x10;
        let mut b = [0u8; 32];
        b[0] = 0x20;
        let (t0_ab, t1_ab) = sort_tokens(&a, &b);
        let (t0_ba, t1_ba) = sort_tokens(&b, &a);
        assert_eq!(t0_ab, t0_ba);
        assert_eq!(t1_ab, t1_ba);
    }

    // ---- Selector parity tests ----

    #[test]
    fn factory_selectors_match_dex_v0_canonical_strings() {
        fn _expected(method: &[u8]) -> [u8; 4] {
            let h = blake3::hash(method);
            let b = h.as_bytes();
            [b[0], b[1], b[2], b[3]]
        }
        assert_eq!(factory::SEL_CREATE_PAIR,        _expected(b"factory.create_pair(address,address)"));
        assert_eq!(factory::SEL_GET_PAIR,           _expected(b"factory.get_pair(address,address)"));
        assert_eq!(factory::SEL_ALL_PAIRS,          _expected(b"factory.all_pairs(u64)"));
        assert_eq!(factory::SEL_ALL_PAIRS_LENGTH,   _expected(b"factory.all_pairs_length()"));
        assert_eq!(factory::SEL_FEE_TO,             _expected(b"factory.fee_to()"));
        assert_eq!(factory::SEL_FEE_TO_SETTER,      _expected(b"factory.fee_to_setter()"));
        assert_eq!(factory::SEL_SET_FEE_TO,         _expected(b"factory.set_fee_to(address)"));
        assert_eq!(factory::SEL_SET_FEE_TO_SETTER,  _expected(b"factory.set_fee_to_setter(address)"));
    }

    // ---- Event topic parity (canonical-string assertion) ----

    #[test]
    fn event_topic_matches_canonical_signature() {
        // The chain-ABI macro builds the event signature as
        // `"<EventName>(<type1>,<type2>,...)"` (no contract-domain prefix —
        // see `event_sig` in bloom-chain-abi-macros). The `PairCreated`
        // declaration above is:
        //   event PairCreated(
        //       #[indexed] token0: Address,
        //       #[indexed] token1: Address,
        //       pair: Address,
        //       all_pairs_length: u64,
        //   );
        // so the canonical signature is the string below.
        let exp = blake3::hash(b"PairCreated(address,address,address,u64)");
        let b = exp.as_bytes();
        assert_eq!(factory::abi::events::PAIR_CREATED_TOPIC, [b[0], b[1], b[2], b[3]]);
    }

    // ---- Storage slot byte-equality parity (pre- vs post-migration) ----
    //
    // The macro-generated storage accessors derive slot keys from the
    // declared field tags. These asserts lock the storage layout: a slot tag
    // rename in the `contract!` block would change the on-disk key and break
    // upgrade compatibility. We compare against blake3 of the explicit byte
    // string the pre-migration factory used.

    #[test]
    fn storage_slot_parity_scalars() {
        use bloom_chain_abi::storage::slot_scalar;

        // Pre-migration tags used by the hand-rolled `k_*` helpers.
        let exp = blake3::hash(b"factory.pair_petal_hash");
        assert_eq!(&slot_scalar("factory.pair_petal_hash")[..], &exp.as_bytes()[..]);

        let exp = blake3::hash(b"factory.fee_to");
        assert_eq!(&slot_scalar("factory.fee_to")[..], &exp.as_bytes()[..]);

        let exp = blake3::hash(b"factory.fee_to_setter");
        assert_eq!(&slot_scalar("factory.fee_to_setter")[..], &exp.as_bytes()[..]);

        // `self_addr` uses an explicit `@ "factory.self"` override.
        let exp = blake3::hash(b"factory.self");
        assert_eq!(&slot_scalar("factory.self")[..], &exp.as_bytes()[..]);

        // `all_pairs_len` uses an explicit `@ "factory.all_pairs.len"` override
        // so the on-disk slot byte-matches the pre-migration `k_pairs_count`.
        let exp = blake3::hash(b"factory.all_pairs.len");
        assert_eq!(&slot_scalar("factory.all_pairs.len")[..], &exp.as_bytes()[..]);
    }

    #[test]
    fn storage_slot_parity_pair_of_mapping() {
        use bloom_chain_abi::storage::slot_mapping;

        let t0 = [0x11u8; 32];
        let t1 = [0x22u8; 32];

        // Pre-migration: blake3("factory.pair:" || t0 || t1).
        let mut buf = Vec::<u8>::new();
        buf.extend_from_slice(b"factory.pair:");
        buf.extend_from_slice(&t0);
        buf.extend_from_slice(&t1);
        let exp = blake3::hash(&buf);

        // Macro mapping encodes (Address, Address) as the 64-byte concat.
        let mut concat = [0u8; 64];
        concat[..32].copy_from_slice(&t0);
        concat[32..].copy_from_slice(&t1);
        assert_eq!(
            &slot_mapping("factory.pair:", &concat)[..],
            &exp.as_bytes()[..]
        );
    }

    #[test]
    fn storage_slot_parity_all_pairs_mapping() {
        use bloom_chain_abi::storage::slot_mapping;

        let i: u64 = 0xdead_beef;

        // Pre-migration: blake3("factory.all_pairs:" || u64_be(i)).
        let mut buf = Vec::<u8>::new();
        buf.extend_from_slice(b"factory.all_pairs:");
        buf.extend_from_slice(&i.to_be_bytes());
        let exp = blake3::hash(&buf);

        assert_eq!(
            &slot_mapping("factory.all_pairs:", &i.to_be_bytes())[..],
            &exp.as_bytes()[..]
        );

        // The local `all_pairs_at_slot(i)` helper must produce the same bytes
        // (this is the production code path).
        assert_eq!(&all_pairs_at_slot(i)[..], &exp.as_bytes()[..]);
    }

    // ---- Init payload tests ----

    #[test]
    fn init_payload_is_exactly_96_bytes() {
        let pair_hash    = [0x01u8; 32];
        let fee_setter   = [0x03u8; 32];
        let factory_self = [0x04u8; 32];

        let payload = factory::init_calldata(&pair_hash, &fee_setter, &factory_self);
        assert_eq!(payload.len(), 96, "factory init must be 96 bytes");
        assert_eq!(&payload[0..32],  &pair_hash);
        assert_eq!(&payload[32..64], &fee_setter);
        assert_eq!(&payload[64..96], &factory_self);

        let parsed = factory::parse_init(&payload).unwrap();
        assert_eq!(parsed.pair_petal_hash, pair_hash);
        assert_eq!(parsed.fee_to_setter, fee_setter);
        assert_eq!(parsed.factory_self_addr, factory_self);
    }

    #[test]
    fn init_payload_rejects_wrong_length() {
        // 95 bytes is short by one — must error.
        let bad = [0u8; 95];
        assert!(factory::parse_init(&bad).is_err());
        // 97 bytes is long by one — strict decoding rejects trailing bytes.
        let bad = [0u8; 97];
        assert!(factory::parse_init(&bad).is_err());
        // The pre-Phase-C 128-byte payload must also be rejected.
        let bad = [0u8; 128];
        assert!(factory::parse_init(&bad).is_err());
    }

    // ---- Pair init payload constructed for `host.deploy` ----

    #[test]
    fn pair_init_payload_is_exactly_96_bytes() {
        // The factory's `create_pair` builds the pair init payload inline
        // (it's a raw `host.deploy` blob, not a selector-dispatched method).
        // Phase C dropped the `reentrancy_addr` field, so the payload is
        // exactly `t0 || t1 || pair_self_addr` — 96 bytes. This test mirrors
        // the production layout to lock the wire format against accidental
        // size drift.
        let t0 = [0xAAu8; 32];
        let t1 = [0xBBu8; 32];
        let pair_self = [0xCCu8; 32];
        let mut cd = Vec::<u8>::with_capacity(96);
        cd.extend_from_slice(&t0);
        cd.extend_from_slice(&t1);
        cd.extend_from_slice(&pair_self);
        assert_eq!(cd.len(), 96, "pair init must be 96 bytes");
        assert_eq!(&cd[0..32],   &t0);
        assert_eq!(&cd[32..64],  &t1);
        assert_eq!(&cd[64..96],  &pair_self);
    }

    #[test]
    fn create_pair_call_layout() {
        // Client-side call builder produces selector + two addresses = 4 + 64.
        let a = [0xAAu8; 32];
        let b = [0xBBu8; 32];
        let cd = factory::calls::create_pair(&a, &b);
        assert_eq!(cd.len(), 4 + 32 + 32);
        assert_eq!(&cd[0..4], &factory::SEL_CREATE_PAIR);
        assert_eq!(&cd[4..36], &a);
        assert_eq!(&cd[36..68], &b);
    }
}
