//! bloom-dex-factory — Uniswap-v2-style DEX factory petal.
//!
//! Keeps a registry of deployed pair petals and deploys new ones on demand
//! via `host.deploy` (chain spec §7.6).
//!
//! # Storage layout (DEX spec §6.3)
//!
//! All keys are 32-byte BLAKE3 digests of domain-tagged tuples (values are
//! 32-byte slots per chain spec §6.2):
//!
//! | Constant          | Preimage                                      | Value type |
//! |-------------------|-----------------------------------------------|------------|
//! | `K_PAIR_HASH`     | `blake3("factory.pair_petal_hash")`           | bytes32    |
//! | `K_REENTRANCY`    | `blake3("factory.reentrancy")`                | Address    |
//! | `K_FEE_TO`        | `blake3("factory.fee_to")`                    | Address    |
//! | `K_FEE_SETTER`    | `blake3("factory.fee_to_setter")`             | Address    |
//! | `K_SELF`          | `blake3("factory.self")`                      | Address    |
//! | `K_PAIRS_COUNT`   | `blake3("factory.all_pairs.len")`             | u64 BE     |
//! | `K_PAIR(t0, t1)`  | `blake3("factory.pair:" \|\| t0 \|\| t1)`     | Address    |
//! | `K_ALL_PAIRS(i)`  | `blake3("factory.all_pairs:" \|\| u64_be(i))` | Address    |
//!
//! `K_PAIR` is stored for **both** orderings so `get_pair` is order-invariant.
//!
//! # ABI
//!
//! Selectors, calldata encoding, return packing, and the init layout are all
//! generated by the chain-owned `bloom_chain_abi::contract!` macro below.
//! Method signatures (canonical strings used for selector hashing) match the
//! DEX v0 spec §4.1.

#![no_std]

extern crate alloc;

use alloc::vec::Vec;

use bloom_chain_abi::{DispatchError, contract};
use bloom_petal_sdk::{crypto, host, log, msg, petal, state};

// ---------------------------------------------------------------------------
// Chain-owned ABI declaration
// ---------------------------------------------------------------------------

contract! {
    contract Factory {
        init(pair_petal_hash: Hash32, reentrancy_addr: Address, fee_to_setter: Address, factory_self_addr: Address);

        fn create_pair(token_a: Address, token_b: Address) -> Address;
        fn get_pair(token_a: Address, token_b: Address) -> Address;
        fn all_pairs(index: u64) -> Address;
        fn all_pairs_length() -> u64;
        fn fee_to() -> Address;
        fn fee_to_setter() -> Address;
        fn set_fee_to(addr: Address);
        fn set_fee_to_setter(addr: Address);
    }
}

// ---------------------------------------------------------------------------
// Storage key derivation
// ---------------------------------------------------------------------------

fn k_pair_hash() -> [u8; 32] {
    crypto::blake3(b"factory.pair_petal_hash")
}
fn k_reentrancy() -> [u8; 32] {
    crypto::blake3(b"factory.reentrancy")
}
fn k_fee_to() -> [u8; 32] {
    crypto::blake3(b"factory.fee_to")
}
fn k_fee_setter() -> [u8; 32] {
    crypto::blake3(b"factory.fee_to_setter")
}
fn k_self() -> [u8; 32] {
    crypto::blake3(b"factory.self")
}
fn k_pairs_count() -> [u8; 32] {
    crypto::blake3(b"factory.all_pairs.len")
}

/// Storage key for a specific pair by token order: `blake3("factory.pair:" || t0 || t1)`.
fn k_pair(t0: &[u8; 32], t1: &[u8; 32]) -> [u8; 32] {
    let mut buf = Vec::with_capacity(13 + 32 + 32);
    buf.extend_from_slice(b"factory.pair:");
    buf.extend_from_slice(t0);
    buf.extend_from_slice(t1);
    crypto::blake3(&buf)
}

/// Storage key for the i-th entry in allPairs: `blake3("factory.all_pairs:" || u64_be(i))`.
fn k_all_pairs(i: u64) -> [u8; 32] {
    let mut buf = Vec::with_capacity(18 + 8);
    buf.extend_from_slice(b"factory.all_pairs:");
    buf.extend_from_slice(&i.to_be_bytes());
    crypto::blake3(&buf)
}

// ---------------------------------------------------------------------------
// Storage helpers
// ---------------------------------------------------------------------------

fn sload(key: &[u8; 32]) -> [u8; 32] {
    state::read(key).unwrap_or([0u8; 32])
}
fn sstore(key: &[u8; 32], value: &[u8; 32]) {
    state::write(key, value);
}
fn sload_u64(key: &[u8; 32]) -> u64 {
    let slot = sload(key);
    u64::from_be_bytes(slot[24..32].try_into().unwrap_or([0u8; 8]))
}
fn sstore_u64(key: &[u8; 32], v: u64) {
    let mut slot = [0u8; 32];
    slot[24..32].copy_from_slice(&v.to_be_bytes());
    state::write(key, &slot);
}

// ---------------------------------------------------------------------------
// Pair sort + derivation helpers (pub for off-chain test pre-computation)
// ---------------------------------------------------------------------------

/// Sort two 32-byte addresses lexicographically; returns `(smaller, larger)`.
pub fn sort_tokens(a: &[u8; 32], b: &[u8; 32]) -> ([u8; 32], [u8; 32]) {
    if a <= b { (*a, *b) } else { (*b, *a) }
}

/// `salt = blake3("dex.pair.salt:" || t0 || t1)`. `t0` and `t1` must be sorted.
pub fn pair_salt(t0: &[u8; 32], t1: &[u8; 32]) -> [u8; 32] {
    let mut buf = Vec::with_capacity(14 + 32 + 32);
    buf.extend_from_slice(b"dex.pair.salt:");
    buf.extend_from_slice(t0);
    buf.extend_from_slice(t1);
    crypto::blake3(&buf)
}

/// Pre-compute the pair address via chain spec §7.7.
pub fn compute_pair_address(
    factory_addr: &[u8; 32],
    salt: &[u8; 32],
    pair_petal_hash: &[u8; 32],
) -> [u8; 32] {
    let prefix = b"bloom-chain.v0.addr:deploy:";
    let sep = b":";
    let mut preimage = Vec::with_capacity(prefix.len() + 32 + 1 + 32 + 1 + 32);
    preimage.extend_from_slice(prefix);
    preimage.extend_from_slice(factory_addr);
    preimage.extend_from_slice(sep);
    preimage.extend_from_slice(salt);
    preimage.extend_from_slice(sep);
    preimage.extend_from_slice(pair_petal_hash);
    crypto::blake3(&preimage)
}

const ZERO_ADDR: [u8; 32] = [0u8; 32];

// ---------------------------------------------------------------------------
// petal entry points (init + call wired into the macro-generated codec)
// ---------------------------------------------------------------------------

bloom_petal_sdk::petal! {
    init => do_init,
    call => do_call,
}

/// Decodes the 128-byte factory init payload via the chain-ABI codec and
/// writes the four config slots. Strict decoding (any length other than 128
/// is rejected by `factory::parse_init`).
fn do_init(calldata: alloc::vec::Vec<u8>) {
    let args = match factory::parse_init(&calldata) {
        Ok(a) => a,
        Err(_) => petal::revert("factory: init: calldata must be 128 bytes"),
    };

    sstore(&k_pair_hash(), &args.pair_petal_hash);
    sstore(&k_reentrancy(), &args.reentrancy_addr);
    sstore(&k_fee_to(), &ZERO_ADDR);
    sstore(&k_fee_setter(), &args.fee_to_setter);
    sstore(&k_self(), &args.factory_self_addr);
    sstore_u64(&k_pairs_count(), 0);
}

/// Routes a method call through the macro-generated dispatcher and translates
/// the typed result into the petal-SDK return / revert ABI.
fn do_call(calldata: alloc::vec::Vec<u8>) -> i32 {
    let mut handler = FactoryHandler;
    let caller = msg::sender();
    match factory::dispatch(&mut handler, &caller, &calldata) {
        Ok(data) => petal::return_data(&data),
        Err(DispatchError::ShortCalldata) => petal::revert("factory: calldata too short"),
        Err(DispatchError::UnknownSelector(_)) => petal::revert("factory: unknown selector"),
        Err(DispatchError::Decode(_)) => petal::revert("factory: bad args"),
        Err(DispatchError::Unauthorized) => petal::revert("factory: unauthorized"),
        Err(DispatchError::Handler(msg)) => petal::revert(msg),
    }
}

// ---------------------------------------------------------------------------
// Handler — pure business logic against the chain-owned ABI shape
// ---------------------------------------------------------------------------

struct FactoryHandler;

impl factory::Handler for FactoryHandler {
    fn create_pair(
        &mut self,
        token_a: [u8; 32],
        token_b: [u8; 32],
    ) -> Result<[u8; 32], &'static str> {
        if token_a == token_b {
            return Err("factory: identical addresses");
        }

        let (t0, t1) = sort_tokens(&token_a, &token_b);
        if t0 == ZERO_ADDR {
            return Err("factory: zero address");
        }

        if sload(&k_pair(&t0, &t1)) != ZERO_ADDR {
            return Err("factory: pair exists");
        }

        let salt = pair_salt(&t0, &t1);
        let pair_hash = sload(&k_pair_hash());
        let reentrancy_addr = sload(&k_reentrancy());
        let factory_self = sload(&k_self());
        let precomputed_pair_addr = compute_pair_address(&factory_self, &salt, &pair_hash);

        // Pair init: t0 || t1 || reentrancy_addr || pair_address (128 bytes).
        let mut init_calldata = Vec::with_capacity(128);
        init_calldata.extend_from_slice(&t0);
        init_calldata.extend_from_slice(&t1);
        init_calldata.extend_from_slice(&reentrancy_addr);
        init_calldata.extend_from_slice(&precomputed_pair_addr);

        let pair_addr = host::deploy(&pair_hash, &salt, &init_calldata)
            .map_err(|_| "factory: deploy failed")?;

        // Store pair in both directions; append to allPairs.
        sstore(&k_pair(&t0, &t1), &pair_addr);
        sstore(&k_pair(&t1, &t0), &pair_addr);

        let count = sload_u64(&k_pairs_count());
        sstore(&k_all_pairs(count), &pair_addr);
        let new_count = count + 1;
        sstore_u64(&k_pairs_count(), new_count);

        // Emit PairCreated(t0, t1, pair_addr, allPairsLength).
        let data = bloom_dex_abi::events::pack_pair_created(&t0, &t1, &pair_addr, new_count);
        log::emit(&[bloom_dex_abi::events::FACTORY_PAIR_CREATED_EVENT], &data);

        Ok(pair_addr)
    }

    fn get_pair(
        &mut self,
        token_a: [u8; 32],
        token_b: [u8; 32],
    ) -> Result<[u8; 32], &'static str> {
        let (t0, t1) = sort_tokens(&token_a, &token_b);
        Ok(sload(&k_pair(&t0, &t1)))
    }

    fn all_pairs(&mut self, index: u64) -> Result<[u8; 32], &'static str> {
        let count = sload_u64(&k_pairs_count());
        if index >= count {
            return Err("factory: allPairs: index out of bounds");
        }
        Ok(sload(&k_all_pairs(index)))
    }

    fn all_pairs_length(&mut self) -> Result<u64, &'static str> {
        Ok(sload_u64(&k_pairs_count()))
    }

    fn fee_to(&mut self) -> Result<[u8; 32], &'static str> {
        Ok(sload(&k_fee_to()))
    }

    fn fee_to_setter(&mut self) -> Result<[u8; 32], &'static str> {
        Ok(sload(&k_fee_setter()))
    }

    fn set_fee_to(&mut self, addr: [u8; 32]) -> Result<(), &'static str> {
        let setter = sload(&k_fee_setter());
        if msg::sender() != setter {
            return Err("factory: setFeeTo: not feeToSetter");
        }
        sstore(&k_fee_to(), &addr);
        Ok(())
    }

    fn set_fee_to_setter(&mut self, addr: [u8; 32]) -> Result<(), &'static str> {
        let setter = sload(&k_fee_setter());
        if msg::sender() != setter {
            return Err("factory: setFeeToSetter: not feeToSetter");
        }
        sstore(&k_fee_setter(), &addr);
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Tests (host-side, non-wasm32 only)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sort_tokens_already_sorted() {
        let a = [0u8; 32];
        let mut b = [0u8; 32];
        b[31] = 1;
        let (t0, t1) = sort_tokens(&a, &b);
        assert_eq!(t0, a);
        assert_eq!(t1, b);
    }

    #[test]
    fn sort_tokens_reversed() {
        let mut a = [0u8; 32];
        a[31] = 5;
        let b = [0u8; 32];
        let (t0, t1) = sort_tokens(&a, &b);
        assert_eq!(t0, b);
        assert_eq!(t1, a);
    }

    #[test]
    fn sort_tokens_is_commutative() {
        let mut a = [0u8; 32];
        a[0] = 0x10;
        let mut b = [0u8; 32];
        b[0] = 0x20;
        let (t0_ab, t1_ab) = sort_tokens(&a, &b);
        let (t0_ba, t1_ba) = sort_tokens(&b, &a);
        assert_eq!(t0_ab, t0_ba);
        assert_eq!(t1_ab, t1_ba);
    }

    #[test]
    fn factory_selectors_match_dex_v0_canonical_strings() {
        fn crate_sel(method: &[u8]) -> [u8; 4] {
            let h = blake3::hash(method);
            let b = h.as_bytes();
            [b[0], b[1], b[2], b[3]]
        }
        assert_eq!(factory::SEL_CREATE_PAIR,        crate_sel(b"factory.create_pair(address,address)"));
        assert_eq!(factory::SEL_GET_PAIR,           crate_sel(b"factory.get_pair(address,address)"));
        assert_eq!(factory::SEL_ALL_PAIRS,          crate_sel(b"factory.all_pairs(u64)"));
        assert_eq!(factory::SEL_ALL_PAIRS_LENGTH,   crate_sel(b"factory.all_pairs_length()"));
        assert_eq!(factory::SEL_FEE_TO,             crate_sel(b"factory.fee_to()"));
        assert_eq!(factory::SEL_FEE_TO_SETTER,      crate_sel(b"factory.fee_to_setter()"));
        assert_eq!(factory::SEL_SET_FEE_TO,         crate_sel(b"factory.set_fee_to(address)"));
        assert_eq!(factory::SEL_SET_FEE_TO_SETTER,  crate_sel(b"factory.set_fee_to_setter(address)"));
    }

    #[test]
    fn factory_selectors_match_legacy_dex_abi_constants() {
        // The chain-ABI macro must emit byte-identical selectors to the old
        // bloom-dex-abi build.rs table, so peer contracts (router etc.) keep
        // dispatching to the same handlers without code changes.
        assert_eq!(factory::SEL_CREATE_PAIR,      bloom_dex_abi::selectors::FACTORY_CREATE_PAIR);
        assert_eq!(factory::SEL_GET_PAIR,         bloom_dex_abi::selectors::FACTORY_GET_PAIR);
        assert_eq!(factory::SEL_ALL_PAIRS,        bloom_dex_abi::selectors::FACTORY_ALL_PAIRS);
        assert_eq!(factory::SEL_ALL_PAIRS_LENGTH, bloom_dex_abi::selectors::FACTORY_ALL_PAIRS_LENGTH);
    }

    #[test]
    fn init_payload_is_exactly_128_bytes() {
        let pair_hash    = [0x01u8; 32];
        let reentrancy   = [0x02u8; 32];
        let fee_setter   = [0x03u8; 32];
        let factory_self = [0x04u8; 32];

        let payload = factory::init_calldata(&pair_hash, &reentrancy, &fee_setter, &factory_self);
        assert_eq!(payload.len(), 128, "factory init must be 128 bytes");
        assert_eq!(&payload[0..32],   &pair_hash);
        assert_eq!(&payload[32..64],  &reentrancy);
        assert_eq!(&payload[64..96],  &fee_setter);
        assert_eq!(&payload[96..128], &factory_self);
    }

    #[test]
    fn init_payload_rejects_wrong_length() {
        // 127 bytes is short by one — must error.
        let bad = [0u8; 127];
        assert!(factory::parse_init(&bad).is_err());
        // 129 bytes is long by one — strict decoding rejects trailing bytes.
        let bad = [0u8; 129];
        assert!(factory::parse_init(&bad).is_err());
    }

    #[test]
    fn create_pair_call_layout() {
        // Client-side call builder produces selector + two addresses = 4 + 64.
        let a = [0xAAu8; 32];
        let b = [0xBBu8; 32];
        let cd = factory::calls::create_pair(&a, &b);
        assert_eq!(cd.len(), 4 + 32 + 32);
        assert_eq!(&cd[0..4], &factory::SEL_CREATE_PAIR);
        assert_eq!(&cd[4..36], &a);
        assert_eq!(&cd[36..68], &b);
    }
}
