//! bloom-dex-factory — Uniswap-v2-style DEX factory petal.
//!
//! Keeps a registry of deployed pair petals and deploys new ones on demand
//! via `host.deploy` (chain spec §7.6).
//!
//! # Storage layout (DEX spec §6.3)
//!
//! All keys are 32-byte BLAKE3 digests of domain-tagged tuples (values are
//! 32-byte slots per chain spec §6.2):
//!
//! | Constant          | Preimage                                      | Value type |
//! |-------------------|-----------------------------------------------|------------|
//! | `K_PAIR_HASH`     | `blake3("factory.pair_petal_hash")`           | bytes32    |
//! | `K_REENTRANCY`    | `blake3("factory.reentrancy")`                | Address    |
//! | `K_FEE_TO`        | `blake3("factory.fee_to")`                    | Address    |
//! | `K_FEE_SETTER`    | `blake3("factory.fee_to_setter")`             | Address    |
//! | `K_SELF`          | `blake3("factory.self")`                      | Address    |
//! | `K_PAIRS_COUNT`   | `blake3("factory.all_pairs.len")`             | u64 BE     |
//! | `K_PAIR(t0, t1)`  | `blake3("factory.pair:" \|\| t0 \|\| t1)`     | Address    |
//! | `K_ALL_PAIRS(i)`  | `blake3("factory.all_pairs:" \|\| u64_be(i))` | Address    |
//!
//! `K_PAIR` is stored for **both** orderings so `get_pair` is order-invariant.
//!
//! # Selectors
//!
//! Public selectors come from `bloom-dex-abi::selectors` (generated by
//! bloom-dex-abi's build.rs from the canonical method strings in DEX spec §4.1):
//! - `FACTORY_CREATE_PAIR`      — `factory.create_pair(address,address)`
//! - `FACTORY_GET_PAIR`         — `factory.get_pair(address,address)`
//! - `FACTORY_ALL_PAIRS`        — `factory.all_pairs(u64)`
//! - `FACTORY_ALL_PAIRS_LENGTH` — `factory.all_pairs_length()`
//!
//! Factory-internal selectors come from this crate's build.rs:
//! - `SEL_FEE_TO`             — `factory.fee_to()`
//! - `SEL_FEE_TO_SETTER`      — `factory.fee_to_setter()`
//! - `SEL_SET_FEE_TO`         — `factory.set_fee_to(address)`
//! - `SEL_SET_FEE_TO_SETTER`  — `factory.set_fee_to_setter(address)`
//!
//! # init calldata
//!
//! `pair_petal_hash (32B) || reentrancy_addr (32B) || fee_to_setter (32B) || factory_self_addr (32B)` — 128 B.
//!
//! `pair_petal_hash` is the BLAKE3 hash of the `bloom-dex-pair` WASM module
//! (computed off-chain at deploy-suite time and passed in).
//! `reentrancy_addr` is the address of the deployed `bloom-dex-reentrancy`
//! instance; every pair's `init` calldata embeds it.
//! `fee_to_setter` is the initial admin address.
//! `factory_self_addr` is the factory's own pre-computed CREATE2 address; the
//! factory stores it in `K_SELF` so that `createPair` can pre-compute the
//! pair address using chain spec §7.7 before deploying.
//!
//! # Pair salt (DEX spec §5.1)
//!
//! `salt = blake3("dex.pair.salt:" || t0 || t1)`
//! where `(t0, t1)` are sorted lexicographically (byte-wise, t0 ≤ t1).
//!
//! # Pair address derivation (chain spec §7.7)
//!
//! `pair_address = blake3("bloom-chain.v0.addr:deploy:" || factory || ":" || salt || ":" || pair_petal_hash)`
//! The deployer-of-record for `host.deploy` is the factory's own address
//! (chain spec §7.7). Clients can pre-compute `pair_address` from
//! `(factory_addr, tokenA, tokenB, pair_petal_hash)` alone.
//!
//! The factory pre-computes `pair_address` before calling `host.deploy` so it
//! can pass the address to the pair's 128B init calldata (Mismatch 3 fix).

#![no_std]

extern crate alloc;

use alloc::vec::Vec;

use bloom_dex_abi::decode::Buf;
use bloom_dex_abi::selectors;
use bloom_petal_sdk::{crypto, host, log, msg, petal, state};

// Factory-internal selectors generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/factory_selectors.rs"));

// ---------------------------------------------------------------------------
// Storage key derivation
// ---------------------------------------------------------------------------

/// Storage key for the pair petal hash: `blake3("factory.pair_petal_hash")`.
fn k_pair_hash() -> [u8; 32] {
    crypto::blake3(b"factory.pair_petal_hash")
}

/// Storage key for the reentrancy guard address: `blake3("factory.reentrancy")`.
fn k_reentrancy() -> [u8; 32] {
    crypto::blake3(b"factory.reentrancy")
}

/// Storage key for `feeTo`: `blake3("factory.fee_to")`.
fn k_fee_to() -> [u8; 32] {
    crypto::blake3(b"factory.fee_to")
}

/// Storage key for `feeToSetter`: `blake3("factory.fee_to_setter")`.
fn k_fee_setter() -> [u8; 32] {
    crypto::blake3(b"factory.fee_to_setter")
}

/// Storage key for the factory's own address: `blake3("factory.self")`.
///
/// Stored at init time (128B form). Required by `createPair` to pre-compute
/// the pair address per chain spec §7.7 before calling `host.deploy`.
fn k_self() -> [u8; 32] {
    crypto::blake3(b"factory.self")
}

/// Storage key for the total number of pairs: `blake3("factory.all_pairs.len")`.
fn k_pairs_count() -> [u8; 32] {
    crypto::blake3(b"factory.all_pairs.len")
}

/// Storage key for a specific pair by token order: `blake3("factory.pair:" || t0 || t1)`.
///
/// Must be called with tokens in the canonical sorted order before lookup.
/// Also called again with tokens reversed when recording both directions.
fn k_pair(t0: &[u8; 32], t1: &[u8; 32]) -> [u8; 32] {
    // Preimage: "factory.pair:" || t0 (32B) || t1 (32B)
    let mut buf = Vec::with_capacity(13 + 32 + 32);
    buf.extend_from_slice(b"factory.pair:");
    buf.extend_from_slice(t0);
    buf.extend_from_slice(t1);
    crypto::blake3(&buf)
}

/// Storage key for the i-th entry in allPairs: `blake3("factory.all_pairs:" || u64_be(i))`.
fn k_all_pairs(i: u64) -> [u8; 32] {
    // Preimage: "factory.all_pairs:" || i as u64 big-endian (8 bytes)
    let mut buf = Vec::with_capacity(18 + 8);
    buf.extend_from_slice(b"factory.all_pairs:");
    buf.extend_from_slice(&i.to_be_bytes());
    crypto::blake3(&buf)
}

// ---------------------------------------------------------------------------
// Storage helpers
// ---------------------------------------------------------------------------

/// Read a 32-byte value from storage; returns all-zeros if the slot is unset.
fn sload(key: &[u8; 32]) -> [u8; 32] {
    state::read(key).unwrap_or([0u8; 32])
}

/// Write a 32-byte address into storage.
fn sstore(key: &[u8; 32], value: &[u8; 32]) {
    state::write(key, value);
}

/// Read a u64 from storage (stored in the low 8 bytes of a 32-byte slot,
/// big-endian, high 24 bytes are zero).
fn sload_u64(key: &[u8; 32]) -> u64 {
    let slot = sload(key);
    // Low 8 bytes of the 32-byte slot, big-endian.
    u64::from_be_bytes(slot[24..32].try_into().unwrap_or([0u8; 8]))
}

/// Write a u64 into storage (stored in the low 8 bytes of a 32-byte slot,
/// big-endian, high 24 bytes are zero).
fn sstore_u64(key: &[u8; 32], v: u64) {
    let mut slot = [0u8; 32];
    slot[24..32].copy_from_slice(&v.to_be_bytes());
    state::write(key, &slot);
}

// ---------------------------------------------------------------------------
// Pair sort helper
// ---------------------------------------------------------------------------

/// Sort two 32-byte addresses lexicographically.
///
/// Returns `(smaller, larger)` where `smaller ≤ larger` byte-wise.
/// Used everywhere a canonical `(token0, token1)` pair is needed.
pub fn sort_tokens(a: &[u8; 32], b: &[u8; 32]) -> ([u8; 32], [u8; 32]) {
    if a <= b {
        (*a, *b)
    } else {
        (*b, *a)
    }
}

/// Compute the CREATE2-style pair salt per DEX spec §5.1:
/// `blake3("dex.pair.salt:" || t0 || t1)`.
///
/// `t0` and `t1` must already be sorted (t0 ≤ t1 lexicographically).
///
/// This is `pub` so host-side integration tests can pre-compute expected
/// pair addresses.
pub fn pair_salt(t0: &[u8; 32], t1: &[u8; 32]) -> [u8; 32] {
    let mut buf = Vec::with_capacity(14 + 32 + 32);
    buf.extend_from_slice(b"dex.pair.salt:");
    buf.extend_from_slice(t0);
    buf.extend_from_slice(t1);
    crypto::blake3(&buf)
}

// ---------------------------------------------------------------------------
// Pair address pre-computation (chain spec §7.7)
// ---------------------------------------------------------------------------

/// Pre-compute the pair address that `host.deploy` will assign, using the
/// chain spec §7.7 formula:
///
/// ```text
/// pair_address = blake3("bloom-chain.v0.addr:deploy:" || deployer || ":" || salt || ":" || petal_hash)
/// ```
///
/// `deployer` is the factory's own address (stored in K_SELF at init).
///
/// This must be called BEFORE `host.deploy` so the address can be passed to
/// the pair's 128B init calldata. After `host.deploy` returns, the returned
/// address is verified to equal the pre-computed one in tests.
pub fn compute_pair_address(
    factory_addr: &[u8; 32],
    salt: &[u8; 32],
    pair_petal_hash: &[u8; 32],
) -> [u8; 32] {
    // Preimage: "bloom-chain.v0.addr:deploy:" || factory (32B) || ":" || salt (32B) || ":" || pair_petal_hash (32B)
    let prefix = b"bloom-chain.v0.addr:deploy:";
    let sep = b":";
    let mut preimage = Vec::with_capacity(prefix.len() + 32 + 1 + 32 + 1 + 32);
    preimage.extend_from_slice(prefix);
    preimage.extend_from_slice(factory_addr);
    preimage.extend_from_slice(sep);
    preimage.extend_from_slice(salt);
    preimage.extend_from_slice(sep);
    preimage.extend_from_slice(pair_petal_hash);
    crypto::blake3(&preimage)
}

// ---------------------------------------------------------------------------
// Zero address constant
// ---------------------------------------------------------------------------

const ZERO_ADDR: [u8; 32] = [0u8; 32];

// ---------------------------------------------------------------------------
// petal entry points
// ---------------------------------------------------------------------------

bloom_petal_sdk::petal! {
    init => do_init,
    call => do_call,
}

/// `init(pair_petal_hash (32B) || reentrancy_addr (32B) || fee_to_setter (32B) || factory_self_addr (32B))`
///
/// Stores the factory's four configuration values and initialises
/// `pairs_count = 0`. `feeTo` is set to the zero address (v0: no protocol fee).
///
/// The 128-byte layout is mandatory (DEX spec §6.3). The `factory_self_addr`
/// field is required so that `createPair` can pre-compute the pair address via
/// chain spec §7.7 before invoking `host.deploy`.
fn do_init(calldata: alloc::vec::Vec<u8>) {
    if calldata.len() < 128 {
        petal::revert("factory: init: calldata must be 128 bytes");
    }

    let pair_hash: [u8; 32] = calldata[0..32].try_into().unwrap();
    let reentrancy_addr: [u8; 32] = calldata[32..64].try_into().unwrap();
    let fee_to_setter: [u8; 32] = calldata[64..96].try_into().unwrap();
    let factory_self_addr: [u8; 32] = calldata[96..128].try_into().unwrap();

    // Store pair petal hash.
    sstore(&k_pair_hash(), &pair_hash);
    // Store reentrancy guard address.
    sstore(&k_reentrancy(), &reentrancy_addr);
    // feeTo starts at zero (v0: fee accrual deferred, spec §2 non-goals).
    sstore(&k_fee_to(), &ZERO_ADDR);
    // Store fee_to_setter.
    sstore(&k_fee_setter(), &fee_to_setter);
    // Store factory's own address for pair-address pre-computation.
    sstore(&k_self(), &factory_self_addr);
    // Initialise pairs count to zero.
    sstore_u64(&k_pairs_count(), 0);
}

/// `call(calldata_ptr, calldata_len) -> i32` — 4-byte selector dispatch.
fn do_call(calldata: alloc::vec::Vec<u8>) -> i32 {
    if calldata.len() < 4 {
        petal::revert("factory: calldata too short");
    }

    let sel: [u8; 4] = calldata[0..4].try_into().unwrap();
    let args = &calldata[4..];

    if sel == selectors::FACTORY_GET_PAIR {
        handle_get_pair(args);
    } else if sel == selectors::FACTORY_ALL_PAIRS {
        handle_all_pairs(args);
    } else if sel == selectors::FACTORY_ALL_PAIRS_LENGTH {
        handle_all_pairs_length(args);
    } else if sel == selectors::FACTORY_CREATE_PAIR {
        handle_create_pair(args);
    } else if sel == SEL_FEE_TO {
        handle_fee_to(args);
    } else if sel == SEL_FEE_TO_SETTER {
        handle_fee_to_setter(args);
    } else if sel == SEL_SET_FEE_TO {
        handle_set_fee_to(args);
    } else if sel == SEL_SET_FEE_TO_SETTER {
        handle_set_fee_to_setter(args);
    } else {
        petal::revert("factory: unknown selector");
    }

    // Unreachable — all handlers call petal::return_data or petal::revert.
    0
}

// ---------------------------------------------------------------------------
// Method handlers
// ---------------------------------------------------------------------------

/// `feeTo() -> Address`
///
/// v0: always returns the stored value (initialised to 0x0 — fee accrual
/// deferred per DEX spec §2 non-goals). The slot is writable via `setFeeTo`
/// so that v1+ can activate fee collection without redeploying the factory.
fn handle_fee_to(_args: &[u8]) {
    let fee_to = sload(&k_fee_to());
    petal::return_data(&fee_to);
}

/// `feeToSetter() -> Address`
fn handle_fee_to_setter(_args: &[u8]) {
    let setter = sload(&k_fee_setter());
    petal::return_data(&setter);
}

/// `setFeeTo(addr: Address)` — only `feeToSetter` can call.
fn handle_set_fee_to(args: &[u8]) {
    let mut buf = Buf::new(args);
    let new_fee_to = match buf.read_address() {
        Ok(a) => a,
        Err(_) => petal::revert("factory: setFeeTo: bad args"),
    };

    let setter = sload(&k_fee_setter());
    let caller = msg::sender();
    if caller != setter {
        petal::revert("factory: setFeeTo: not feeToSetter");
    }

    sstore(&k_fee_to(), &new_fee_to);
    petal::return_data(&[]);
}

/// `setFeeToSetter(addr: Address)` — only `feeToSetter` can call.
fn handle_set_fee_to_setter(args: &[u8]) {
    let mut buf = Buf::new(args);
    let new_setter = match buf.read_address() {
        Ok(a) => a,
        Err(_) => petal::revert("factory: setFeeToSetter: bad args"),
    };

    let setter = sload(&k_fee_setter());
    let caller = msg::sender();
    if caller != setter {
        petal::revert("factory: setFeeToSetter: not feeToSetter");
    }

    sstore(&k_fee_setter(), &new_setter);
    petal::return_data(&[]);
}

/// `getPair(tokenA: Address, tokenB: Address) -> Address`
///
/// Order-invariant: sorts `(tokenA, tokenB)` before lookup.
/// Returns `0x0` (32 zero bytes) if no pair exists.
fn handle_get_pair(args: &[u8]) {
    let mut buf = Buf::new(args);
    let token_a = match buf.read_address() {
        Ok(a) => a,
        Err(_) => petal::revert("factory: getPair: bad args"),
    };
    let token_b = match buf.read_address() {
        Ok(a) => a,
        Err(_) => petal::revert("factory: getPair: bad args"),
    };

    let (t0, t1) = sort_tokens(&token_a, &token_b);
    let pair = sload(&k_pair(&t0, &t1));
    petal::return_data(&pair);
}

/// `allPairs(index: u64) -> Address`
fn handle_all_pairs(args: &[u8]) {
    let mut buf = Buf::new(args);
    let index = match buf.read_u64() {
        Ok(i) => i,
        Err(_) => petal::revert("factory: allPairs: bad args"),
    };

    let count = sload_u64(&k_pairs_count());
    if index >= count {
        petal::revert("factory: allPairs: index out of bounds");
    }

    let addr = sload(&k_all_pairs(index));
    petal::return_data(&addr);
}

/// `allPairsLength() -> u64`
fn handle_all_pairs_length(_args: &[u8]) {
    let count = sload_u64(&k_pairs_count());
    // Return as 8 bytes big-endian (u64 per spec §4.1 return type).
    petal::return_data(&count.to_be_bytes());
}

/// `createPair(tokenA: Address, tokenB: Address) -> Address`
///
/// Per DEX spec §5.2 (updated for 128B pair init, Mismatch 3 fix):
/// 1. Revert if `tokenA == tokenB` ("factory: identical addresses").
/// 2. Sort to `(t0, t1)` with `t0 ≤ t1` lexicographically.
/// 3. Revert if `t0 == 0x0` ("factory: zero address").
/// 4. Revert if pair already exists ("factory: pair exists").
/// 5. Compute `salt = blake3("dex.pair.salt:" || t0 || t1)`.
/// 6. Pre-compute `pair_address` via chain spec §7.7 formula using factory's
///    own address (stored in K_SELF at init time).
/// 7. Build pair init calldata: `t0 || t1 || reentrancy_addr || pair_address` (128 bytes).
/// 8. Call `host::deploy(pair_petal_hash, salt, init_calldata)`.
///    Revert with "factory: deploy failed" on error.
/// 9. Store pair in both directions + append to `allPairs` list.
/// 10. Emit `PairCreated(t0, t1, pair_addr, allPairsLength)`.
/// 11. Return `pair_addr` (32 bytes).
fn handle_create_pair(args: &[u8]) {
    let mut buf = Buf::new(args);
    let token_a = match buf.read_address() {
        Ok(a) => a,
        Err(_) => petal::revert("factory: createPair: bad args"),
    };
    let token_b = match buf.read_address() {
        Ok(a) => a,
        Err(_) => petal::revert("factory: createPair: bad args"),
    };

    // 1. Identical addresses check.
    if token_a == token_b {
        petal::revert("factory: identical addresses");
    }

    // 2. Sort tokens lexicographically.
    let (t0, t1) = sort_tokens(&token_a, &token_b);

    // 3. Zero address check (t0 is the smaller; if t0 == 0 the other is also
    //    at risk, but identical-address check above covers t0==t1==0).
    if t0 == ZERO_ADDR {
        petal::revert("factory: zero address");
    }

    // 4. Pair-exists check.
    let existing = sload(&k_pair(&t0, &t1));
    if existing != ZERO_ADDR {
        petal::revert("factory: pair exists");
    }

    // 5. Compute salt.
    let salt = pair_salt(&t0, &t1);

    // 6. Load configuration and pre-compute pair address.
    let pair_hash = sload(&k_pair_hash());
    let reentrancy_addr = sload(&k_reentrancy());
    let factory_self = sload(&k_self());

    // Pre-compute pair address per chain spec §7.7:
    // pair_address = blake3("bloom-chain.v0.addr:deploy:" || factory || ":" || salt || ":" || pair_petal_hash)
    let precomputed_pair_addr = compute_pair_address(&factory_self, &salt, &pair_hash);

    // 7. Build pair init calldata: token0 (32B) || token1 (32B) || reentrancy_addr (32B) || pair_address (32B).
    let mut init_calldata = Vec::with_capacity(128);
    init_calldata.extend_from_slice(&t0);
    init_calldata.extend_from_slice(&t1);
    init_calldata.extend_from_slice(&reentrancy_addr);
    init_calldata.extend_from_slice(&precomputed_pair_addr);

    // 8. Deploy the pair petal via host.deploy.
    let pair_addr = match host::deploy(&pair_hash, &salt, &init_calldata) {
        Ok(addr) => addr,
        Err(_) => petal::revert("factory: deploy failed"),
    };

    // 9. Store pair in both directions.
    sstore(&k_pair(&t0, &t1), &pair_addr);
    sstore(&k_pair(&t1, &t0), &pair_addr);

    // Append to allPairs list and increment count.
    let count = sload_u64(&k_pairs_count());
    sstore(&k_all_pairs(count), &pair_addr);
    let new_count = count + 1;
    sstore_u64(&k_pairs_count(), new_count);

    // 10. Emit PairCreated(t0, t1, pair_addr, allPairsLength).
    //    Topic: FACTORY_PAIR_CREATED_EVENT (4-byte BLAKE3 prefix of
    //    "PairCreated(address,address,address,u64)", zero-padded to 32B by log::emit).
    //    Data: token0 (32B) || token1 (32B) || pair_addr (32B) || count as u64 (8B).
    let data = bloom_dex_abi::events::pack_pair_created(&t0, &t1, &pair_addr, new_count);
    log::emit(&[bloom_dex_abi::events::FACTORY_PAIR_CREATED_EVENT], &data);

    // 11. Return pair_addr.
    petal::return_data(&pair_addr);
}

// ---------------------------------------------------------------------------
// Tests (host-side, non-wasm32 only)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -----------------------------------------------------------------------
    // sort_tokens — address sorting invariant
    // -----------------------------------------------------------------------

    #[test]
    fn sort_tokens_already_sorted() {
        let a = [0u8; 32];
        let mut b = [0u8; 32];
        b[31] = 1;
        let (t0, t1) = sort_tokens(&a, &b);
        assert_eq!(t0, a);
        assert_eq!(t1, b);
    }

    #[test]
    fn sort_tokens_reversed() {
        let mut a = [0u8; 32];
        a[31] = 5;
        let b = [0u8; 32]; // b < a
        let (t0, t1) = sort_tokens(&a, &b);
        assert_eq!(t0, b, "smaller must be t0");
        assert_eq!(t1, a, "larger must be t1");
    }

    #[test]
    fn sort_tokens_equal_returns_original_order() {
        let a = [42u8; 32];
        let b = [42u8; 32];
        let (t0, t1) = sort_tokens(&a, &b);
        assert_eq!(t0, a);
        assert_eq!(t1, b);
    }

    #[test]
    fn sort_tokens_is_commutative() {
        // sort_tokens(a, b) must equal sort_tokens(b, a) for any a, b.
        let mut a = [0u8; 32];
        a[0] = 0x10;
        let mut b = [0u8; 32];
        b[0] = 0x20;
        let (t0_ab, t1_ab) = sort_tokens(&a, &b);
        let (t0_ba, t1_ba) = sort_tokens(&b, &a);
        assert_eq!(t0_ab, t0_ba, "sort must be commutative (t0)");
        assert_eq!(t1_ab, t1_ba, "sort must be commutative (t1)");
    }

    #[test]
    fn sort_tokens_lexicographic_high_byte() {
        // Compare at byte 0 (most significant in our byte-wise ordering).
        let mut a = [0u8; 32];
        a[0] = 0xFF;
        let b = [0u8; 32];
        let (t0, _t1) = sort_tokens(&a, &b);
        assert_eq!(t0, b, "address with 0x00 high byte must sort first");
    }

    #[test]
    fn sort_tokens_produces_ordered_pair() {
        // After sorting, t0 <= t1 must always hold.
        let test_cases: &[([u8; 32], [u8; 32])] = &[
            ([0u8; 32], [1u8; 32]),
            ([0xFFu8; 32], [0x00u8; 32]),
            ([0x10u8; 32], [0x20u8; 32]),
        ];
        for (a, b) in test_cases {
            let (t0, t1) = sort_tokens(a, b);
            assert!(t0 <= t1, "sort_tokens must produce t0 <= t1");
        }
    }

    // -----------------------------------------------------------------------
    // pair_salt preimage structure
    // -----------------------------------------------------------------------

    #[test]
    fn pair_salt_preimage_structure() {
        // Verify preimage: "dex.pair.salt:" || t0 (32B) || t1 (32B) = 78 bytes.
        let domain = b"dex.pair.salt:";
        let t0 = [1u8; 32];
        let t1 = [2u8; 32];

        let mut preimage = Vec::new();
        preimage.extend_from_slice(domain);
        preimage.extend_from_slice(&t0);
        preimage.extend_from_slice(&t1);

        assert_eq!(preimage.len(), 14 + 32 + 32, "pair salt preimage must be 78 bytes");
        assert_eq!(&preimage[..14], b"dex.pair.salt:");
        assert_eq!(&preimage[14..46], &t0);
        assert_eq!(&preimage[46..78], &t1);
    }

    #[test]
    fn pair_salt_is_order_dependent() {
        // The salt preimage uses the sorted (t0, t1) — so salt(t0,t1) != salt(t1,t0)
        // when t0 != t1. Verify the preimages differ.
        let t0 = [1u8; 32];
        let t1 = [2u8; 32];

        let mut pre_01 = Vec::new();
        pre_01.extend_from_slice(b"dex.pair.salt:");
        pre_01.extend_from_slice(&t0);
        pre_01.extend_from_slice(&t1);

        let mut pre_10 = Vec::new();
        pre_10.extend_from_slice(b"dex.pair.salt:");
        pre_10.extend_from_slice(&t1);
        pre_10.extend_from_slice(&t0);

        assert_ne!(pre_01, pre_10, "salt preimages must differ when tokens differ");
    }

    #[test]
    fn pair_salt_order_invariance_via_sort() {
        // Given tokens a and b (unsorted), sort_tokens then pair_salt
        // must produce the same result regardless of input order.
        let mut a = [0u8; 32];
        a[31] = 100;
        let b = [0u8; 32]; // b < a

        let (t0_ab, t1_ab) = sort_tokens(&a, &b);
        let (t0_ba, t1_ba) = sort_tokens(&b, &a);

        // After sorting, both orderings produce the same (t0, t1).
        assert_eq!(t0_ab, t0_ba);
        assert_eq!(t1_ab, t1_ba);

        // And the sorted pair satisfies t0 <= t1.
        assert!(t0_ab <= t1_ab);
    }

    // -----------------------------------------------------------------------
    // createPair revert-path logic (pure logic checks, no host imports)
    // -----------------------------------------------------------------------

    #[test]
    fn identical_tokens_detected() {
        let a = [0xABu8; 32];
        let b = [0xABu8; 32];
        assert_eq!(a, b, "identical-address check: must detect equal tokens");
    }

    #[test]
    fn zero_address_sorts_first() {
        // When one token is zero and the other is non-zero,
        // the zero address sorts first → triggers "zero address" revert path.
        let zero = [0u8; 32];
        let mut nonzero = [0u8; 32];
        nonzero[31] = 1;
        let (t0, _t1) = sort_tokens(&zero, &nonzero);
        assert_eq!(t0, ZERO_ADDR, "zero address must sort as t0, triggering revert");
    }

    #[test]
    fn pair_exists_guard() {
        // Simulate stored pair address being non-zero → "pair exists" revert.
        let existing_pair = [0xFFu8; 32];
        assert_ne!(existing_pair, ZERO_ADDR, "non-zero stored pair triggers revert");
    }

    #[test]
    fn no_pair_passes_check() {
        // Zero stored value → no pair exists, createPair should proceed.
        let empty = [0u8; 32];
        assert_eq!(empty, ZERO_ADDR, "all-zeros means no pair → should not revert");
    }

    // -----------------------------------------------------------------------
    // Storage key preimage checks
    // -----------------------------------------------------------------------

    #[test]
    fn k_pair_preimages_differ_by_order() {
        // Verify K_PAIR(t0,t1) and K_PAIR(t1,t0) have distinct preimages.
        let t0 = [1u8; 32];
        let t1 = [2u8; 32];

        let mut pre_01 = Vec::new();
        pre_01.extend_from_slice(b"factory.pair:");
        pre_01.extend_from_slice(&t0);
        pre_01.extend_from_slice(&t1);

        let mut pre_10 = Vec::new();
        pre_10.extend_from_slice(b"factory.pair:");
        pre_10.extend_from_slice(&t1);
        pre_10.extend_from_slice(&t0);

        assert_ne!(pre_01, pre_10, "K_PAIR(t0,t1) and K_PAIR(t1,t0) must have distinct preimages");
    }

    #[test]
    fn k_all_pairs_index_is_big_endian() {
        // Verify the all_pairs key encodes the index in big-endian.
        let i: u64 = 0x0102030405060708;
        let mut pre = Vec::new();
        pre.extend_from_slice(b"factory.all_pairs:");
        pre.extend_from_slice(&i.to_be_bytes());
        // Last 8 bytes of the preimage must be the BE encoding of i.
        assert_eq!(&pre[18..], &[0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08]);
    }

    // -----------------------------------------------------------------------
    // Build-time selector verification (against blake3 crate)
    // -----------------------------------------------------------------------

    #[test]
    fn factory_selectors_match_blake3_crate() {
        // Verify the selectors generated by build.rs (included from OUT_DIR)
        // against direct blake3 crate hashing. These are the factory-internal
        // selectors not covered by bloom-dex-abi's generated constants.
        fn crate_sel(method: &[u8]) -> [u8; 4] {
            let h = blake3::hash(method);
            let b = h.as_bytes();
            [b[0], b[1], b[2], b[3]]
        }

        assert_eq!(SEL_FEE_TO,          crate_sel(b"factory.fee_to()"),             "fee_to selector mismatch");
        assert_eq!(SEL_FEE_TO_SETTER,   crate_sel(b"factory.fee_to_setter()"),      "fee_to_setter selector mismatch");
        assert_eq!(SEL_SET_FEE_TO,      crate_sel(b"factory.set_fee_to(address)"),  "set_fee_to selector mismatch");
        assert_eq!(SEL_SET_FEE_TO_SETTER, crate_sel(b"factory.set_fee_to_setter(address)"), "set_fee_to_setter selector mismatch");
    }

    // -----------------------------------------------------------------------
    // 128B factory init layout
    // -----------------------------------------------------------------------

    #[test]
    fn factory_init_requires_128_bytes() {
        // Verify that the 128B init layout is correct:
        // pair_petal_hash (32B) || reentrancy_addr (32B) || fee_to_setter (32B) || factory_self_addr (32B)
        let pair_hash      = [0x01u8; 32];
        let reentrancy     = [0x02u8; 32];
        let fee_setter     = [0x03u8; 32];
        let factory_self   = [0x04u8; 32];

        let mut init = Vec::new();
        init.extend_from_slice(&pair_hash);
        init.extend_from_slice(&reentrancy);
        init.extend_from_slice(&fee_setter);
        init.extend_from_slice(&factory_self);

        assert_eq!(init.len(), 128, "factory init must be 128 bytes");

        // Verify field offsets.
        assert_eq!(&init[0..32],   &pair_hash,    "pair_hash at bytes 0..32");
        assert_eq!(&init[32..64],  &reentrancy,   "reentrancy at bytes 32..64");
        assert_eq!(&init[64..96],  &fee_setter,   "fee_setter at bytes 64..96");
        assert_eq!(&init[96..128], &factory_self, "factory_self at bytes 96..128");
    }

    // -----------------------------------------------------------------------
    // Pair address pre-computation (chain spec §7.7)
    // -----------------------------------------------------------------------

    #[test]
    fn compute_pair_address_preimage_structure() {
        // Verify the preimage structure:
        // "bloom-chain.v0.addr:deploy:" || factory (32B) || ":" || salt (32B) || ":" || pair_hash (32B)
        let prefix = b"bloom-chain.v0.addr:deploy:";
        let factory = [0xAA_u8; 32];
        let salt    = [0xBB_u8; 32];
        let hash    = [0xCC_u8; 32];

        let mut preimage = Vec::new();
        preimage.extend_from_slice(prefix);
        preimage.extend_from_slice(&factory);
        preimage.extend_from_slice(b":");
        preimage.extend_from_slice(&salt);
        preimage.extend_from_slice(b":");
        preimage.extend_from_slice(&hash);

        let expected_len = prefix.len() + 32 + 1 + 32 + 1 + 32;
        assert_eq!(preimage.len(), expected_len, "pair address preimage length");
        assert_eq!(&preimage[..prefix.len()], prefix, "domain prefix");
        assert_eq!(&preimage[prefix.len()..prefix.len()+32], &factory, "factory addr");
    }

    #[test]
    fn compute_pair_address_is_deterministic() {
        // Same inputs → same output (pure function of inputs).
        let factory = [0x11_u8; 32];
        let salt    = [0x22_u8; 32];
        let hash    = [0x33_u8; 32];

        // We can't call crypto::blake3 from host-side tests directly since it's a
        // host import. Instead verify the preimage contents deterministically.
        let mut pre1 = Vec::new();
        pre1.extend_from_slice(b"bloom-chain.v0.addr:deploy:");
        pre1.extend_from_slice(&factory);
        pre1.extend_from_slice(b":");
        pre1.extend_from_slice(&salt);
        pre1.extend_from_slice(b":");
        pre1.extend_from_slice(&hash);

        let mut pre2 = Vec::new();
        pre2.extend_from_slice(b"bloom-chain.v0.addr:deploy:");
        pre2.extend_from_slice(&factory);
        pre2.extend_from_slice(b":");
        pre2.extend_from_slice(&salt);
        pre2.extend_from_slice(b":");
        pre2.extend_from_slice(&hash);

        assert_eq!(pre1, pre2, "preimage must be deterministic");
    }

    #[test]
    fn compute_pair_address_differs_by_factory() {
        // Different factory addresses → different preimages → different pair addresses.
        let factory_a = [0x01_u8; 32];
        let factory_b = [0x02_u8; 32];
        let salt  = [0xBB_u8; 32];
        let hash  = [0xCC_u8; 32];

        let mut pre_a = Vec::new();
        pre_a.extend_from_slice(b"bloom-chain.v0.addr:deploy:");
        pre_a.extend_from_slice(&factory_a);
        pre_a.extend_from_slice(b":");
        pre_a.extend_from_slice(&salt);
        pre_a.extend_from_slice(b":");
        pre_a.extend_from_slice(&hash);

        let mut pre_b = Vec::new();
        pre_b.extend_from_slice(b"bloom-chain.v0.addr:deploy:");
        pre_b.extend_from_slice(&factory_b);
        pre_b.extend_from_slice(b":");
        pre_b.extend_from_slice(&salt);
        pre_b.extend_from_slice(b":");
        pre_b.extend_from_slice(&hash);

        assert_ne!(pre_a, pre_b, "different factories must produce different pair address preimages");
    }

    // -----------------------------------------------------------------------
    // createPair: 128B pair init layout
    // -----------------------------------------------------------------------

    #[test]
    fn create_pair_builds_128b_init() {
        // Verify the 128B pair init calldata layout:
        // t0 (32B) || t1 (32B) || reentrancy_addr (32B) || pair_address (32B)
        let t0             = [0x10_u8; 32];
        let t1             = [0x20_u8; 32];
        let reentrancy     = [0x30_u8; 32];
        let pair_address   = [0x40_u8; 32];

        let mut init = Vec::new();
        init.extend_from_slice(&t0);
        init.extend_from_slice(&t1);
        init.extend_from_slice(&reentrancy);
        init.extend_from_slice(&pair_address);

        assert_eq!(init.len(), 128, "pair init calldata must be 128 bytes");
        assert_eq!(&init[0..32],   &t0,           "t0 at bytes 0..32");
        assert_eq!(&init[32..64],  &t1,           "t1 at bytes 32..64");
        assert_eq!(&init[64..96],  &reentrancy,   "reentrancy at bytes 64..96");
        assert_eq!(&init[96..128], &pair_address, "pair_address at bytes 96..128");
    }
}
