#!/usr/bin/env bash
# scripts/gen-docker-compose.sh — emit a templated docker-compose.yml for an
# N-validator bloom-chain testnet.
#
# Usage:
#   scripts/gen-docker-compose.sh <N> > /tmp/docker-compose.gen.yml
#
# The schema matches the hand-written docker-compose.yml at repo root for
# N=4. Each validator service `valI` (I in 0..N-1) binds container port 8545
# to host port (18545+I) so tests can drive each one over TCP from the host.
#
# Required env (passed to compose at `up` time, not at generation time):
#   BLOOM_DOCKER_TMPDIR — absolute host path containing home0..home(N-1).

set -euo pipefail

if [ $# -ne 1 ]; then
    echo "usage: $0 <validator_count>" >&2
    exit 1
fi

N="$1"
if ! [[ "$N" =~ ^[0-9]+$ ]] || [ "$N" -lt 1 ] || [ "$N" -gt 32 ]; then
    echo "validator_count must be an integer in [1, 32]; got '$N'" >&2
    exit 1
fi

cat <<'HEADER'
# AUTO-GENERATED by scripts/gen-docker-compose.sh
# N-validator bloom-chain test network. Edit gen-docker-compose.sh, not this
# file. (When N=4, the hand-written docker-compose.yml is byte-identical.)

services:
HEADER

for i in $(seq 0 $((N - 1))); do
    host_port=$((18545 + i))
    cat <<SERVICE
  val${i}:
    image: bloom-eth:test
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloom-val${i}
    hostname: val${i}
    command: ["--home", "/home/bloom", "chain", "run-validator"]
    environment:
      RUST_LOG: \${RUST_LOG:-warn}
      RUST_BACKTRACE: "1"
      BLOOM_BLOCK_PRUNE_WINDOW: \${BLOOM_BLOCK_PRUNE_WINDOW:-8}
      BLOOM_STATE_BLOB_RETENTION: \${BLOOM_STATE_BLOB_RETENTION:-4}
      BLOOM_RPC_UDS: "0"
    volumes:
      - \${BLOOM_DOCKER_TMPDIR}/home${i}:/home/bloom
    ports:
      - "127.0.0.1:$((18656 + i)):26656"
      - "127.0.0.1:${host_port}:8545"
    expose:
      - "26656"
      - "8545"
    healthcheck:
      test: ["CMD-SHELL", "BLOOM_RPC_TCP=127.0.0.1:8545 /usr/local/bin/bloom --home /home/bloom chain health >/dev/null"]
      interval: 2s
      timeout: 2s
      retries: 60
      start_period: 5s

SERVICE
done
