#!/usr/bin/env bash
# Opt-in public-relay acceptance against an already-running disposable Triad.
# The virtual authenticator exercises genuine WebAuthn proofs; execution uses
# only a loopback Anvil chain. No real wallet or public-chain funds are used.
set -euo pipefail
umask 077
[ "${BLOOM_REMOTE_RELAY_E2E:-}" = 1 ] || { echo 'Set BLOOM_REMOTE_RELAY_E2E=1 for disposable acceptance.' >&2; exit 1; }
[ "$#" = 3 ] || { echo 'usage: test-remote-relay-approval.sh TRIAD_ENV ANVIL_RPC RUN_DIR' >&2; exit 1; }
triad_env="$1"; rpc="$2"; run_dir="$3"
[[ "$rpc" =~ ^http://127\.0\.0\.1:[0-9]{1,5}/?$ ]] || { echo 'Anvil must be loopback-only' >&2; exit 1; }
[ "$(cast chain-id --rpc-url "$rpc")" = 31337 ] || { echo 'Expected disposable chain 31337' >&2; exit 1; }
mkdir "$run_dir"
chmod 0700 "$run_dir"
# This is the public connection-settings file generated by triad-dev-launch.sh.
# shellcheck disable=SC1090
source "$triad_env"
driver="${BLOOM_INTEGRATION_DEBUG_DRIVER_BIN:?Set the exact candidate Broker debug-driver binary}"
[ -x "$driver" ] || { echo 'Debug driver must be executable' >&2; exit 1; }
driver="$(cd "$(dirname "$driver")" && pwd -P)/$(basename "$driver")"
shasum -a 256 "$BLOOM_BIN" "$driver" > "$run_dir/binaries.sha256"
cli() { "$BLOOM_BIN" --home "$BLOOM_HOME" "$@"; }
read_vfs() { cli vfs cat "$1"; }
write_vfs() { cli vfs write "$1" --data "$2"; }
wait_vfs() {
  local value i
  for ((i=0;i<100;i++)); do
    if value="$(read_vfs "$1" 2>/dev/null)" && [ -n "$value" ]; then printf '%s' "$value"; return 0; fi
    sleep 0.2
  done
  echo "VFS result timed out: $1" >&2; return 1
}
remote_url() {
  local value
  value="$(sed -n 's/^ceremony_url: //p' "$1")"
  [[ "$value" =~ ^https://[a-z2-7]{26}\.relay\.bloom\.directory/\#cap=[A-Za-z0-9_-]{43}$ ]] || { echo 'Expected an assigned public HTTPS ceremony URL' >&2; return 1; }
  printf '%s' "$value"
}
complete() {
  "$driver" complete "$1" --authenticator-seed-file "$run_dir/authenticator.seed" --sign-count "$2"
}
# Fresh test-only authenticator state stays outside Machine's home.
python3 - "$run_dir/authenticator.seed" <<'PY'
import secrets,sys
with open(sys.argv[1], 'x') as f: f.write(secrets.token_hex(32))
PY
wallet_name="relay-e2e-$(date +%s)"
cli wallet new "$wallet_name" > "$run_dir/register.txt"
url="$(remote_url "$run_dir/register.txt")"
# Browsers negotiate HTTP/2; check the landing page independently of ureq's
# HTTP/1.1 ceremony client so authority handling is exercised on both paths.
navigation="$(curl --http2 --max-time 20 --silent --show-error \
  -H 'Sec-Fetch-Site: none' -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-Dest: document' \
  --output "$run_dir/landing.html" --write-out '%{http_code} %{http_version}' \
  "${url%%/#cap=*}/")"
[ "$navigation" = '200 2' ] || { echo "Public HTTP/2 navigation failed: $navigation" >&2; exit 1; }
printf 'PASS public HTTP/2 browser navigation\n'
complete "$url" 1 > "$run_dir/register-result.json"
wallet="$(jq -er '.wallet_id' "$run_dir/register-result.json")"
address="$(cli wallet address "$wallet")"
printf '%s\n' "$wallet" > "$run_dir/wallet-id"
printf 'PASS remote wallet registration %s\n' "$wallet"
recipient=0x000000000000000000000000000000000000dEaD
read_vfs "/wallets/$wallet/policy.json" | jq --arg recipient "$recipient" \
  '.allowed_destinations = ((.allowed_destinations // []) + [{chain:"anvil",destination:$recipient}] | unique | sort)' > "$run_dir/policy.json"
cli wallet update-policy "$wallet" --file "$run_dir/policy.json" > "$run_dir/policy.txt"
complete "$(remote_url "$run_dir/policy.txt")" 2 > "$run_dir/policy-result.json"
operation="$(sed -n 's/^operation_id: //p' "$run_dir/policy.txt")"
cli wallet commit-policy "$operation" > "$run_dir/policy-commit.json"
printf 'PASS remote policy authorization\n'
cast rpc --rpc-url "$rpc" anvil_setBalance "$address" 0x8ac7230489e80000 > /dev/null
before="$(cast balance --rpc-url "$rpc" "$recipient")"
intent="$(jq -nc --arg to "$recipient" '{kind:"send",to:$to,value:"1 eth",chain:"anvil",usd_value_hint:"1"}')"
write_vfs "/wallets/$wallet/0/chains/anvil/outbox/new.tx" "$intent" > /dev/null
pending="/wallets/$wallet/0/chains/anvil/outbox/pending"
entry=''
for ((i=0;i<100;i++)); do
  entry="$(cli vfs ls "$pending" | awk -F '\t' '$2 == "Dir" {print $1;exit}')"
  [ -n "$entry" ] && break
  sleep 0.2
done
[ -n "$entry" ] || { echo 'No pending transfer appeared' >&2; exit 1; }
confirm="$pending/$entry/confirm"
if write_vfs "$confirm" y > "$run_dir/before-approval.txt" 2>&1; then
  echo 'Execution unexpectedly succeeded before approval' >&2; exit 1
fi
wait_vfs "$pending/$entry/ceremony.json" > "$run_dir/approval.json"
jq -e '.approval_operation_id | test("^[0-9a-f]{64}$")' "$run_dir/approval.json" > /dev/null
url="$(jq -er '.ceremony_url' "$run_dir/approval.json")"
[[ "$url" =~ ^https://[a-z2-7]{26}\.relay\.bloom\.directory/\#cap=[A-Za-z0-9_-]{43}$ ]] || { echo 'Sealed Approval did not use hosted HTTPS' >&2; exit 1; }
[ "$(cast nonce --rpc-url "$rpc" "$address")" = 0 ]
printf 'PASS execution refused before remote Sealed Approval\n'
complete "$url" 3 > "$run_dir/approval-result.json"
[ "$(cast nonce --rpc-url "$rpc" "$address")" = 0 ]
[ "$(cast balance --rpc-url "$rpc" "$recipient")" = "$before" ]
printf 'PASS remote Sealed Approval activated without executing\n'
write_vfs "$confirm" y > "$run_dir/confirm.txt"
tx="$(wait_vfs "/wallets/$wallet/0/chains/anvil/outbox/sent/$entry/tx_hash" | tr -d '[:space:]')"
read_vfs "/wallets/$wallet/0/chains/anvil/outbox/sent/$entry/ceremony.json" > "$run_dir/terminal-ceremony.json"
jq -e '.sign_dispatched == true and .ceremony_url == null' "$run_dir/terminal-ceremony.json" > /dev/null
cast receipt --rpc-url "$rpc" --json "$tx" > "$run_dir/receipt.json"
jq -e --arg from "$(printf '%s' "$address" | tr '[:upper:]' '[:lower:]')" --arg to "$(printf '%s' "$recipient" | tr '[:upper:]' '[:lower:]')" \
  '(.status == "0x1" or .status == "1") and (.from|ascii_downcase)==$from and (.to|ascii_downcase)==$to' "$run_dir/receipt.json" > /dev/null
[ "$(cast nonce --rpc-url "$rpc" "$address")" = 1 ]
after="$(cast balance --rpc-url "$rpc" "$recipient")"
python3 - "$before" "$after" <<'PY'
import sys
assert int(sys.argv[2])-int(sys.argv[1]) == 10**18, 'recipient delta differs from exact approved amount'
PY
printf 'PASS separate execution mined once on disposable Anvil: %s\n' "$tx"
printf 'Evidence retained at %s; test wallet %s\n' "$run_dir" "$wallet"
