//! 4-byte BLAKE3 event topic prefixes and log-packing helpers.
//!
//! Per DEX spec §10: topics are 4-byte BLAKE3 prefixes of the event
//! signature string (same rule as method selectors). Data fields are
//! packed per §4 fixed-width encoding (address=32B, u256=32B, u128=16B, etc.).
//!
//! These constants are generated by `build.rs`.

#[cfg(not(feature = "std"))]
use alloc::vec::Vec;

include!(concat!(env!("OUT_DIR"), "/events_generated.rs"));

/// Pack a `Transfer(from, to, value)` log payload.
///
/// Topics: `[ERC20_TRANSFER_EVENT]`
/// Data: `from (32) || to (32) || value (32)`
pub fn pack_transfer(from: &[u8; 32], to: &[u8; 32], value: &[u8; 32]) -> Vec<u8> {
    let mut v = Vec::with_capacity(96);
    v.extend_from_slice(from);
    v.extend_from_slice(to);
    v.extend_from_slice(value);
    v
}

/// Pack an `Approval(owner, spender, value)` log payload.
pub fn pack_approval(owner: &[u8; 32], spender: &[u8; 32], value: &[u8; 32]) -> Vec<u8> {
    let mut v = Vec::with_capacity(96);
    v.extend_from_slice(owner);
    v.extend_from_slice(spender);
    v.extend_from_slice(value);
    v
}

/// Pack a `Mint(sender, amount0, amount1)` log payload.
pub fn pack_mint(sender: &[u8; 32], amount0: &[u8; 32], amount1: &[u8; 32]) -> Vec<u8> {
    let mut v = Vec::with_capacity(96);
    v.extend_from_slice(sender);
    v.extend_from_slice(amount0);
    v.extend_from_slice(amount1);
    v
}

/// Pack a `Burn(sender, amount0, amount1, to)` log payload.
pub fn pack_burn(
    sender: &[u8; 32],
    amount0: &[u8; 32],
    amount1: &[u8; 32],
    to: &[u8; 32],
) -> Vec<u8> {
    let mut v = Vec::with_capacity(128);
    v.extend_from_slice(sender);
    v.extend_from_slice(amount0);
    v.extend_from_slice(amount1);
    v.extend_from_slice(to);
    v
}

/// Pack a `Swap(sender, a0in, a1in, a0out, a1out, to)` log payload.
pub fn pack_swap(
    sender: &[u8; 32],
    a0in: &[u8; 32],
    a1in: &[u8; 32],
    a0out: &[u8; 32],
    a1out: &[u8; 32],
    to: &[u8; 32],
) -> Vec<u8> {
    let mut v = Vec::with_capacity(192);
    v.extend_from_slice(sender);
    v.extend_from_slice(a0in);
    v.extend_from_slice(a1in);
    v.extend_from_slice(a0out);
    v.extend_from_slice(a1out);
    v.extend_from_slice(to);
    v
}

/// Pack a `Sync(reserve0, reserve1)` log payload.
///
/// `reserve0` and `reserve1` are `u128`, so 16 bytes each.
pub fn pack_sync(reserve0: u128, reserve1: u128) -> Vec<u8> {
    let mut v = Vec::with_capacity(32);
    v.extend_from_slice(&reserve0.to_be_bytes());
    v.extend_from_slice(&reserve1.to_be_bytes());
    v
}

/// Pack a `PairCreated(token0, token1, pair, index)` log payload.
///
/// `index` is `u64`.
pub fn pack_pair_created(
    token0: &[u8; 32],
    token1: &[u8; 32],
    pair: &[u8; 32],
    index: u64,
) -> Vec<u8> {
    let mut v = Vec::with_capacity(104);
    v.extend_from_slice(token0);
    v.extend_from_slice(token1);
    v.extend_from_slice(pair);
    v.extend_from_slice(&index.to_be_bytes());
    v
}
