//! bloom-dex-erc20 — ERC-20 fungible token as a bloom-chain petal.
//!
//! # Storage layout (declared via `storage { ... }` in `contract!` below)
//!
//! All keys are 32-byte BLAKE3 digests; their domain tags are chosen to be
//! collision-free with the pair AMM keys.
//!
//! | Field          | Domain tag                            | Value type           |
//! |----------------|---------------------------------------|----------------------|
//! | `name`         | `"erc20.name"`                        | Bytes32 (NUL-padded) |
//! | `symbol`       | `"erc20.symbol"`                      | Bytes32 (NUL-padded) |
//! | `decimals`     | `"erc20.decimals"`                    | u64 (low byte = u8)  |
//! | `total_supply` | `"erc20.total_supply"`                | U256                 |
//! | `balances`     | `"erc20.balance:" \|\| addr`          | U256                 |
//! | `allowances`   | `"erc20.allowance:" \|\| owner \|\| s`| U256                 |
//!
//! The ERC-20 key namespace (`erc20.*`) is intentionally shared with the
//! bloom-dex-pair petal's LP-token surface (spec §6.1). Pair declares the same
//! `total_supply`/`balances`/`allowances` tags via the same `@ "erc20.*"`
//! overrides so the two petals can read each other's state without re-encoding.
//!
//! # Init payload (chain spec §7.8 / DEX spec §6.1)
//!
//! ```text
//! name_len   : u16 BE
//! name_bytes : [u8; name_len]   (ASCII, ≤ 32 bytes)
//! symbol_len : u16 BE
//! symbol_bytes: [u8; symbol_len] (ASCII, ≤ 32 bytes)
//! decimals   : u8
//! initial_supply : [u8; 32]     (u256 BE)
//! initial_holder : [u8; 32]     (Address)
//! ```
//!
//! The init payload uses variable-length, length-prefixed string fields and a
//! `u8` for decimals — none of which are expressible in the chain-ABI
//! `contract!` macro's fixed-width type system. We therefore keep `do_init`
//! hand-rolled and only model the runtime-dispatched calls (whose args ARE
//! fixed-width) through the macro.
//!
//! # ABI
//!
//! All runtime method selectors, calldata encoding, return packing, storage
//! accessors, event emitters, and the dispatcher are generated by the chain-
//! owned `bloom_chain_abi::contract!` macro below. Method signatures
//! (canonical strings used for selector hashing) match the DEX v0 spec §4.1
//! byte-for-byte.
//!
//! `erc20.decimals()` returns a single `u8` byte, which the macro's typed
//! return system does not currently model (smallest macro int is `u64`). We
//! hand-dispatch that one selector before falling through to the macro's
//! `erc20::dispatch(...)`. The selector is computed from the canonical
//! signature string via `bloom_chain_abi::selector` so it remains anchored
//! to the same hashing rule the macro uses.

#![no_std]

extern crate alloc;

use alloc::vec::Vec;

use bloom_chain_abi::{DispatchError, U256, contract};
use bloom_petal_sdk::{msg, petal};

// ---------------------------------------------------------------------------
// Chain-owned ABI declaration
// ---------------------------------------------------------------------------

contract! {
    contract Erc20 {
        storage {
            name:          Bytes32;
            symbol:        Bytes32;
            decimals:      u64;

            total_supply:  U256                              @ "erc20.total_supply";
            balances:      Mapping<Address, U256>            @ "erc20.balance:";
            allowances:    Mapping<(Address, Address), U256> @ "erc20.allowance:";
        }

        event Transfer(#[indexed] from: Address, #[indexed] to: Address, value: U256);
        event Approval(#[indexed] owner: Address, #[indexed] spender: Address, value: U256);

        fn total_supply() -> U256;
        fn balance_of(owner: Address) -> U256;
        fn allowance(owner: Address, spender: Address) -> U256;
        fn transfer(to: Address, amount: U256) -> bool;
        fn transfer_from(from: Address, to: Address, amount: U256) -> bool;
        fn approve(spender: Address, value: U256) -> bool;
        fn name() -> Bytes32;
        fn symbol() -> Bytes32;
    }
}

// ---------------------------------------------------------------------------
// U256::MAX sentinel for unlimited allowance
// ---------------------------------------------------------------------------

const U256_MAX: U256 = U256([0xff; 32]);

// ---------------------------------------------------------------------------
// Mint helper (used by init)
// ---------------------------------------------------------------------------

/// Increase the balance of `to` by `amount` and update total supply.
/// Emits Transfer(0x0, to, amount).
fn mint(to: &[u8; 32], amount: U256) {
    if amount.is_zero() {
        return;
    }
    // Update balance.
    let prev = erc20::abi::storage::balances::get(to);
    let next = prev
        .checked_add(amount)
        .unwrap_or_else(|| petal::revert("erc20: mint overflow"));
    erc20::abi::storage::balances::set(to, &next);

    // Update total supply.
    let ts = erc20::abi::storage::total_supply();
    let ts_next = ts
        .checked_add(amount)
        .unwrap_or_else(|| petal::revert("erc20: total supply overflow"));
    erc20::abi::storage::set_total_supply(&ts_next);

    // Emit Transfer(0x0, to, amount).
    let zero = [0u8; 32];
    erc20::abi::events::emit_transfer(&zero, to, &amount);
}

// ---------------------------------------------------------------------------
// Internal transfer (no event — callers emit events)
// ---------------------------------------------------------------------------

/// Debit `amount` from `from` and credit to `to`. Returns the error message
/// on insufficient balance / overflow so the caller can surface it through
/// the `Handler::Err` channel.
fn do_transfer(from: &[u8; 32], to: &[u8; 32], amount: U256) -> Result<(), &'static str> {
    if amount.is_zero() {
        // Zero transfers are allowed; nothing to do.
        return Ok(());
    }
    let from_bal = erc20::abi::storage::balances::get(from);
    let new_from = from_bal
        .checked_sub(amount)
        .ok_or("erc20: insufficient balance")?;
    erc20::abi::storage::balances::set(from, &new_from);

    let to_bal = erc20::abi::storage::balances::get(to);
    let new_to = to_bal
        .checked_add(amount)
        .ok_or("erc20: balance overflow")?;
    erc20::abi::storage::balances::set(to, &new_to);
    Ok(())
}

// ---------------------------------------------------------------------------
// Init payload parser helpers
// ---------------------------------------------------------------------------

/// Parse a `u16-BE length || bytes` field from a raw slice, returning the
/// field bytes and the remaining slice. Reverts if the slice is too short.
fn parse_length_prefixed<'a>(data: &'a [u8]) -> (&'a [u8], &'a [u8]) {
    if data.len() < 2 {
        petal::revert("erc20: init payload truncated at length prefix");
    }
    let len = u16::from_be_bytes([data[0], data[1]]) as usize;
    let rest = &data[2..];
    if rest.len() < len {
        petal::revert("erc20: init payload truncated in field bytes");
    }
    (&rest[..len], &rest[len..])
}

/// Write a string of up to 32 bytes into a `bytes32` slot (left-zero-padded,
/// i.e. ASCII occupies the right portion). Reverts if the string exceeds 32 bytes.
fn str_to_bytes32(s: &[u8]) -> [u8; 32] {
    if s.len() > 32 {
        petal::revert("erc20: name/symbol too long (max 32 bytes)");
    }
    let mut slot = [0u8; 32];
    // Right-align: put string at the end of the slot.
    let offset = 32 - s.len();
    slot[offset..].copy_from_slice(s);
    slot
}

// ---------------------------------------------------------------------------
// petal entry points (init + call wired into the macro-generated codec)
// ---------------------------------------------------------------------------

bloom_petal_sdk::petal! {
    init => do_init,
    call => do_call,
}

/// `init` — runs once at deploy time.
///
/// Payload: `name_len (u16 BE) | name | symbol_len (u16 BE) | symbol |
///           decimals (u8) | initial_supply (u256 BE, 32 B) | initial_holder (Address, 32 B)`
///
/// Kept hand-rolled because the payload is variable-length (length-prefixed
/// strings) and contains a `u8` — neither of which the chain-ABI
/// `contract!` macro can model today.
fn do_init(calldata: Vec<u8>) {
    let data = calldata.as_slice();

    // Parse name.
    let (name_bytes, rest) = parse_length_prefixed(data);
    let name_slot = str_to_bytes32(name_bytes);

    // Parse symbol.
    let (symbol_bytes, rest) = parse_length_prefixed(rest);
    let symbol_slot = str_to_bytes32(symbol_bytes);

    // Parse decimals (1 byte).
    if rest.is_empty() {
        petal::revert("erc20: init payload truncated at decimals");
    }
    let decimals = rest[0];
    let rest = &rest[1..];

    // Parse initial_supply (32 bytes, u256 BE).
    if rest.len() < 32 {
        petal::revert("erc20: init payload truncated at initial_supply");
    }
    let mut supply_bytes = [0u8; 32];
    supply_bytes.copy_from_slice(&rest[..32]);
    let initial_supply = U256(supply_bytes);
    let rest = &rest[32..];

    // Parse initial_holder (32 bytes, Address).
    if rest.len() < 32 {
        petal::revert("erc20: init payload truncated at initial_holder");
    }
    let mut holder = [0u8; 32];
    holder.copy_from_slice(&rest[..32]);
    let rest = &rest[32..];

    // No trailing bytes allowed.
    if !rest.is_empty() {
        petal::revert("erc20: init payload has trailing bytes");
    }

    // Write metadata to storage.
    erc20::abi::storage::set_name(&name_slot);
    erc20::abi::storage::set_symbol(&symbol_slot);

    // Decimals: u8 widened to u64 — the macro's u64 setter writes the value
    // big-endian into `slot[24..32]`, so the low byte (slot[31]) is the same
    // as the pre-migration `slot[31] = decimals` hand-rolled write for any
    // decimals value that fits in u8.
    erc20::abi::storage::set_decimals(decimals as u64);

    // Mint initial supply to holder (also sets total_supply).
    mint(&holder, initial_supply);
}

/// Selector for `erc20.decimals()`. Hand-dispatched because the macro's
/// typed return system cannot model a 1-byte `u8` return today. Computed at
/// runtime from the canonical signature via `bloom_chain_abi::selector`, so
/// the hashing rule stays anchored to the same source-of-truth the macro
/// uses (no hand-rolled constant).
fn sel_decimals() -> [u8; 4] {
    bloom_chain_abi::selector("erc20.decimals()")
}

/// `call` — dispatches on the 4-byte selector.
fn do_call(calldata: Vec<u8>) -> i32 {
    if calldata.len() < 4 {
        petal::revert("erc20: calldata too short");
    }
    let sel: [u8; 4] = [calldata[0], calldata[1], calldata[2], calldata[3]];

    // Hand-dispatch decimals() (1-byte return, not modelable by the macro).
    if sel == sel_decimals() {
        if calldata.len() != 4 {
            petal::revert("erc20: decimals: trailing calldata bytes");
        }
        // Storage slot was written from a u8 → u64 widening, so the low byte
        // is identical to the legacy single-byte write.
        let d = erc20::abi::storage::decimals() as u8;
        petal::return_data(&[d]);
    }

    let mut handler = Erc20Handler;
    let caller = msg::sender();
    match erc20::dispatch(&mut handler, &caller, &calldata) {
        Ok(data) => petal::return_data(&data),
        Err(DispatchError::ShortCalldata) => petal::revert("erc20: calldata too short"),
        Err(DispatchError::UnknownSelector(_)) => petal::revert("erc20: unknown selector"),
        Err(DispatchError::Decode(_)) => petal::revert("erc20: bad args"),
        Err(DispatchError::Unauthorized) => petal::revert("erc20: unauthorized"),
        Err(DispatchError::Handler(msg)) => petal::revert(msg),
    }
}

// ---------------------------------------------------------------------------
// Handler — pure business logic against the chain-owned ABI shape
// ---------------------------------------------------------------------------

struct Erc20Handler;

impl erc20::Handler for Erc20Handler {
    fn total_supply(&mut self) -> Result<U256, &'static str> {
        Ok(erc20::abi::storage::total_supply())
    }

    fn balance_of(&mut self, owner: [u8; 32]) -> Result<U256, &'static str> {
        Ok(erc20::abi::storage::balances::get(&owner))
    }

    fn allowance(
        &mut self,
        owner: [u8; 32],
        spender: [u8; 32],
    ) -> Result<U256, &'static str> {
        Ok(erc20::abi::storage::allowances::get((&owner, &spender)))
    }

    fn transfer(&mut self, to: [u8; 32], amount: U256) -> Result<bool, &'static str> {
        let sender = msg::sender();
        do_transfer(&sender, &to, amount)?;

        // Emit Transfer(sender, to, amount).
        erc20::abi::events::emit_transfer(&sender, &to, &amount);
        Ok(true)
    }

    fn transfer_from(
        &mut self,
        from: [u8; 32],
        to: [u8; 32],
        amount: U256,
    ) -> Result<bool, &'static str> {
        let caller = msg::sender();

        // Check and deduct allowance (u256::MAX means unlimited).
        let current_allow = erc20::abi::storage::allowances::get((&from, &caller));
        if current_allow != U256_MAX {
            let new_allow = current_allow
                .checked_sub(amount)
                .ok_or("erc20: insufficient allowance")?;
            erc20::abi::storage::allowances::set((&from, &caller), &new_allow);
        }

        do_transfer(&from, &to, amount)?;

        // Emit Transfer(from, to, amount).
        erc20::abi::events::emit_transfer(&from, &to, &amount);
        Ok(true)
    }

    fn approve(&mut self, spender: [u8; 32], value: U256) -> Result<bool, &'static str> {
        let owner = msg::sender();
        erc20::abi::storage::allowances::set((&owner, &spender), &value);

        // Emit Approval(owner, spender, value).
        erc20::abi::events::emit_approval(&owner, &spender, &value);
        Ok(true)
    }

    fn name(&mut self) -> Result<[u8; 32], &'static str> {
        Ok(erc20::abi::storage::name())
    }

    fn symbol(&mut self) -> Result<[u8; 32], &'static str> {
        Ok(erc20::abi::storage::symbol())
    }
}

// ---------------------------------------------------------------------------
// Host-side unit tests (cfg(test), host target only)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use bloom_chain_abi::{Buf, Encoder, U256};

    // ---------------------------------------------------------------------------
    // Helper: build init payload
    // ---------------------------------------------------------------------------

    fn encode_init(
        name: &[u8],
        symbol: &[u8],
        decimals: u8,
        initial_supply: U256,
        initial_holder: [u8; 32],
    ) -> alloc::vec::Vec<u8> {
        let mut v = alloc::vec::Vec::new();
        // name_len (u16 BE) + bytes
        v.extend_from_slice(&(name.len() as u16).to_be_bytes());
        v.extend_from_slice(name);
        // symbol_len (u16 BE) + bytes
        v.extend_from_slice(&(symbol.len() as u16).to_be_bytes());
        v.extend_from_slice(symbol);
        // decimals
        v.push(decimals);
        // initial_supply (u256 BE, 32 bytes)
        v.extend_from_slice(&initial_supply.0);
        // initial_holder (32 bytes)
        v.extend_from_slice(&initial_holder);
        v
    }

    // ---------------------------------------------------------------------------
    // Helper: build calldata for each method
    // ---------------------------------------------------------------------------

    fn cd_balance_of(addr: [u8; 32]) -> alloc::vec::Vec<u8> {
        let mut e = Encoder::with_selector(erc20::SEL_BALANCE_OF);
        e.push_address(&addr);
        e.finish()
    }

    fn cd_allowance(owner: [u8; 32], spender: [u8; 32]) -> alloc::vec::Vec<u8> {
        let mut e = Encoder::with_selector(erc20::SEL_ALLOWANCE);
        e.push_address(&owner);
        e.push_address(&spender);
        e.finish()
    }

    fn cd_transfer(to: [u8; 32], value: U256) -> alloc::vec::Vec<u8> {
        let mut e = Encoder::with_selector(erc20::SEL_TRANSFER);
        e.push_address(&to);
        e.push_u256(value);
        e.finish()
    }

    fn cd_transfer_from(from: [u8; 32], to: [u8; 32], value: U256) -> alloc::vec::Vec<u8> {
        let mut e = Encoder::with_selector(erc20::SEL_TRANSFER_FROM);
        e.push_address(&from);
        e.push_address(&to);
        e.push_u256(value);
        e.finish()
    }

    fn cd_approve(spender: [u8; 32], value: U256) -> alloc::vec::Vec<u8> {
        let mut e = Encoder::with_selector(erc20::SEL_APPROVE);
        e.push_address(&spender);
        e.push_u256(value);
        e.finish()
    }

    // ---------------------------------------------------------------------------
    // Tests: calldata encoding round-trips (ABI surface only — no host calls)
    // ---------------------------------------------------------------------------

    /// Verify that the selector for ERC20_BALANCE_OF is 4 bytes and that a
    /// calldata blob can be decoded back out with the matching Buf reader.
    #[test]
    fn balance_of_calldata_roundtrip() {
        let addr = [42u8; 32];
        let cd = cd_balance_of(addr);

        // Should be 4-byte selector + 32-byte address = 36 bytes.
        assert_eq!(cd.len(), 36);
        assert_eq!(&cd[..4], &erc20::SEL_BALANCE_OF);

        // Decode args.
        let mut buf = Buf::new(&cd[4..]);
        let decoded_addr = buf.read_address().unwrap();
        assert_eq!(decoded_addr, addr);
        assert!(buf.expect_eof().is_ok());
    }

    #[test]
    fn allowance_calldata_roundtrip() {
        let owner   = [1u8; 32];
        let spender = [2u8; 32];
        let cd = cd_allowance(owner, spender);

        assert_eq!(cd.len(), 4 + 32 + 32);
        assert_eq!(&cd[..4], &erc20::SEL_ALLOWANCE);

        let mut buf = Buf::new(&cd[4..]);
        assert_eq!(buf.read_address().unwrap(), owner);
        assert_eq!(buf.read_address().unwrap(), spender);
        assert!(buf.expect_eof().is_ok());
    }

    #[test]
    fn transfer_calldata_roundtrip() {
        let to     = [7u8; 32];
        let amount = U256::from_u128(1_000_000_000_000_000_000u128); // 1e18
        let cd = cd_transfer(to, amount);

        assert_eq!(cd.len(), 4 + 32 + 32);
        assert_eq!(&cd[..4], &erc20::SEL_TRANSFER);

        let mut buf = Buf::new(&cd[4..]);
        assert_eq!(buf.read_address().unwrap(), to);
        assert_eq!(buf.read_u256().unwrap(), amount);
        assert!(buf.expect_eof().is_ok());
    }

    #[test]
    fn transfer_from_calldata_roundtrip() {
        let from   = [10u8; 32];
        let to     = [20u8; 32];
        let amount = U256::from_u64(500);
        let cd = cd_transfer_from(from, to, amount);

        assert_eq!(cd.len(), 4 + 32 + 32 + 32);
        assert_eq!(&cd[..4], &erc20::SEL_TRANSFER_FROM);

        let mut buf = Buf::new(&cd[4..]);
        assert_eq!(buf.read_address().unwrap(), from);
        assert_eq!(buf.read_address().unwrap(), to);
        assert_eq!(buf.read_u256().unwrap(), amount);
        assert!(buf.expect_eof().is_ok());
    }

    #[test]
    fn approve_calldata_roundtrip() {
        let spender = [99u8; 32];
        let value   = U256([0xffu8; 32]); // u256::MAX (unlimited allowance)
        let cd = cd_approve(spender, value);

        assert_eq!(cd.len(), 4 + 32 + 32);
        assert_eq!(&cd[..4], &erc20::SEL_APPROVE);

        let mut buf = Buf::new(&cd[4..]);
        assert_eq!(buf.read_address().unwrap(), spender);
        assert_eq!(buf.read_u256().unwrap(), value);
        assert!(buf.expect_eof().is_ok());
    }

    /// Verify the init payload encoding round-trips correctly.
    #[test]
    fn init_payload_roundtrip() {
        let name    = b"TestToken";
        let symbol  = b"TST";
        let decimals = 18u8;
        let supply  = U256::from_u128(1_000_000_000_000_000_000_000_000u128); // 1e24
        let holder  = [0xABu8; 32];

        let payload = encode_init(name, symbol, decimals, supply, holder);

        // Manually decode and verify.
        let mut pos = 0usize;

        // name
        let name_len = u16::from_be_bytes([payload[pos], payload[pos + 1]]) as usize;
        pos += 2;
        assert_eq!(&payload[pos..pos + name_len], name);
        pos += name_len;

        // symbol
        let sym_len = u16::from_be_bytes([payload[pos], payload[pos + 1]]) as usize;
        pos += 2;
        assert_eq!(&payload[pos..pos + sym_len], symbol);
        pos += sym_len;

        // decimals
        assert_eq!(payload[pos], decimals);
        pos += 1;

        // supply
        let mut s = [0u8; 32];
        s.copy_from_slice(&payload[pos..pos + 32]);
        assert_eq!(U256(s), supply);
        pos += 32;

        // holder
        let mut h = [0u8; 32];
        h.copy_from_slice(&payload[pos..pos + 32]);
        assert_eq!(h, holder);
        pos += 32;

        assert_eq!(pos, payload.len(), "no trailing bytes");
    }

    /// Verify the `str_to_bytes32` alignment (right-align / left-zero-pad).
    #[test]
    fn str_to_bytes32_alignment() {
        // A 3-byte symbol "TST" should occupy bytes [29..32] of the slot.
        let s = b"TST";
        let mut expected = [0u8; 32];
        expected[29..32].copy_from_slice(s);

        // Test the logic directly (duplicated here since the fn is private).
        let mut slot = [0u8; 32];
        let offset = 32 - s.len();
        slot[offset..].copy_from_slice(s);

        assert_eq!(slot, expected);
    }

    /// Verify u256::MAX round-trips as the unlimited-allowance sentinel.
    #[test]
    fn u256_max_sentinel() {
        let max = U256([0xff; 32]);
        let mut e = Encoder::new();
        e.push_u256(max);
        let out = e.finish();
        let mut buf = Buf::new(&out);
        let decoded = buf.read_u256().unwrap();
        assert_eq!(decoded, max);
    }

    /// Sanity-check that all 9 ERC-20 selectors are distinct (no 4-byte collision).
    #[test]
    fn selectors_are_unique() {
        use alloc::collections::BTreeSet;
        let sels: &[[u8; 4]] = &[
            erc20::SEL_NAME,
            erc20::SEL_SYMBOL,
            super::sel_decimals(),
            erc20::SEL_TOTAL_SUPPLY,
            erc20::SEL_BALANCE_OF,
            erc20::SEL_ALLOWANCE,
            erc20::SEL_TRANSFER,
            erc20::SEL_TRANSFER_FROM,
            erc20::SEL_APPROVE,
        ];
        let set: BTreeSet<[u8; 4]> = sels.iter().cloned().collect();
        assert_eq!(set.len(), sels.len(), "selector collision detected");
    }

    // ---------------------------------------------------------------------------
    // Chain-ABI macro selector-parity tests (the byte-compatibility guarantee)
    // ---------------------------------------------------------------------------

    #[test]
    fn erc20_selectors_match_dex_v0_canonical_strings() {
        fn _expected(method: &[u8]) -> [u8; 4] {
            let h = blake3::hash(method);
            let b = h.as_bytes();
            [b[0], b[1], b[2], b[3]]
        }
        assert_eq!(erc20::SEL_TOTAL_SUPPLY,  _expected(b"erc20.total_supply()"));
        assert_eq!(erc20::SEL_BALANCE_OF,    _expected(b"erc20.balance_of(address)"));
        assert_eq!(erc20::SEL_ALLOWANCE,     _expected(b"erc20.allowance(address,address)"));
        assert_eq!(erc20::SEL_TRANSFER,      _expected(b"erc20.transfer(address,u256)"));
        assert_eq!(erc20::SEL_TRANSFER_FROM, _expected(b"erc20.transfer_from(address,address,u256)"));
        assert_eq!(erc20::SEL_APPROVE,       _expected(b"erc20.approve(address,u256)"));
        assert_eq!(erc20::SEL_NAME,          _expected(b"erc20.name()"));
        assert_eq!(erc20::SEL_SYMBOL,        _expected(b"erc20.symbol()"));
        assert_eq!(super::sel_decimals(),    _expected(b"erc20.decimals()"));
    }

    /// Sanity-check the macro-emitted call builder layout for `transfer`.
    #[test]
    fn macro_call_builder_transfer_layout() {
        let to = [0x77u8; 32];
        let amount = U256::from_u64(123);
        let cd = erc20::calls::transfer(&to, amount);
        assert_eq!(cd.len(), 4 + 32 + 32);
        assert_eq!(&cd[..4], &erc20::SEL_TRANSFER);
        assert_eq!(&cd[4..36], &to);
        let mut b = [0u8; 32];
        b.copy_from_slice(&cd[36..]);
        assert_eq!(U256(b), amount);
    }

    // ---------------------------------------------------------------------------
    // Storage slot byte-equality parity (pre- vs post-migration)
    //
    // The macro-generated storage accessors derive slot keys from the
    // declared field tags. These asserts lock the storage layout: a slot
    // tag rename in the `contract!` block would change the on-disk key and
    // break upgrade compatibility. We compare against blake3 of the
    // explicit byte string the pre-migration erc20 used.
    // ---------------------------------------------------------------------------

    #[test]
    fn storage_slot_parity_scalars() {
        use bloom_chain_abi::storage::slot_scalar;

        // Auto-derived tags: "erc20.<field>" (default for scalar fields in
        // contract `Erc20`).
        let exp = blake3::hash(b"erc20.name");
        assert_eq!(&slot_scalar("erc20.name")[..], &exp.as_bytes()[..]);

        let exp = blake3::hash(b"erc20.symbol");
        assert_eq!(&slot_scalar("erc20.symbol")[..], &exp.as_bytes()[..]);

        let exp = blake3::hash(b"erc20.decimals");
        assert_eq!(&slot_scalar("erc20.decimals")[..], &exp.as_bytes()[..]);

        // Shared "erc20.total_supply" namespace with bloom-dex-pair (explicit
        // `@ "erc20.total_supply"` override on the `total_supply` field).
        let exp = blake3::hash(b"erc20.total_supply");
        assert_eq!(&slot_scalar("erc20.total_supply")[..], &exp.as_bytes()[..]);
    }

    #[test]
    fn storage_slot_parity_mappings() {
        use bloom_chain_abi::storage::slot_mapping;

        let addr = [0x42u8; 32];

        // Pre-migration: blake3("erc20.balance:" || addr).
        let mut buf = alloc::vec::Vec::<u8>::new();
        buf.extend_from_slice(b"erc20.balance:");
        buf.extend_from_slice(&addr);
        let exp = blake3::hash(&buf);
        assert_eq!(&slot_mapping("erc20.balance:", &addr)[..], &exp.as_bytes()[..]);

        // Pre-migration: blake3("erc20.allowance:" || owner || spender).
        let owner = [0x11u8; 32];
        let spender = [0x22u8; 32];
        let mut buf = alloc::vec::Vec::<u8>::new();
        buf.extend_from_slice(b"erc20.allowance:");
        buf.extend_from_slice(&owner);
        buf.extend_from_slice(&spender);
        let exp = blake3::hash(&buf);

        let mut concat = [0u8; 64];
        concat[..32].copy_from_slice(&owner);
        concat[32..].copy_from_slice(&spender);
        assert_eq!(
            &slot_mapping("erc20.allowance:", &concat)[..],
            &exp.as_bytes()[..]
        );
    }
}
