//! Canonical ABI signature rendering.
//!
//! Both `#[bloom::contract]` and `#[bloom::interface]` derive the 4-byte
//! selector for each method as `blake3(domain.method(types))`, with the
//! type list rendered into a canonical string form. `#[event]` and
//! `#[error]` follow the same canonicalisation for topic / selector
//! signatures. Keeping the rendering centralised guarantees that a method
//! declared on an interface ends up with byte-for-byte the same selector
//! as the contract handler that implements it.
//!
//! Canonical form per type shape:
//!
//! | Rust syntax            | Canonical form        |
//! |------------------------|-----------------------|
//! | `u256`, `Address`, ... | `u256`, `address`     |
//! | `Vec<u256>`            | `vec<u256>`           |
//! | `Option<U256>`         | `option<u256>`        |
//! | `Result<U256, Err>`    | `result<u256,err>`    |
//! | `(u8, U256)`           | `(u8,u256)`           |
//! | `[u8; 32]`             | `[u8;32]`             |
//! | `[T; N]`               | `[t;n]`               |
//! | `()`                   | `()`                  |
//! | unsupported            | `?`                   |
//!
//! Last-segment identifiers are lowercased so a `MyStruct` field shows up
//! as `mystruct`, matching the `AbiType::ABI_TYPE` form generated by
//! `#[derive(AbiType)]`.

use syn::{Expr, GenericArgument, Lit, PathArguments, Type};

/// Render a `syn::Type` into canonical ABI signature form. See module docs
/// for the rule table.
pub fn render_type(out: &mut String, ty: &Type) {
    match ty {
        Type::Path(tp) => {
            if let Some(seg) = tp.path.segments.last() {
                out.push_str(&seg.ident.to_string().to_ascii_lowercase());
                if let PathArguments::AngleBracketed(ab) = &seg.arguments {
                    out.push('<');
                    let mut first = true;
                    for arg in &ab.args {
                        if !first {
                            out.push(',');
                        }
                        first = false;
                        match arg {
                            GenericArgument::Type(t) => render_type(out, t),
                            GenericArgument::Const(Expr::Lit(lit)) => {
                                render_lit(out, &lit.lit);
                            }
                            _ => out.push('?'),
                        }
                    }
                    out.push('>');
                }
                return;
            }
            out.push('?');
        }
        Type::Tuple(t) => {
            out.push('(');
            let mut first = true;
            for elem in &t.elems {
                if !first {
                    out.push(',');
                }
                first = false;
                render_type(out, elem);
            }
            out.push(')');
        }
        Type::Array(a) => {
            out.push('[');
            render_type(out, &a.elem);
            out.push(';');
            match &a.len {
                Expr::Lit(lit) => render_lit(out, &lit.lit),
                _ => out.push('?'),
            }
            out.push(']');
        }
        Type::Reference(r) => render_type(out, &r.elem),
        Type::Paren(p) => render_type(out, &p.elem),
        Type::Group(g) => render_type(out, &g.elem),
        _ => out.push('?'),
    }
}

fn render_lit(out: &mut String, lit: &Lit) {
    match lit {
        Lit::Int(i) => out.push_str(i.base10_digits()),
        Lit::Bool(b) => out.push_str(if b.value { "true" } else { "false" }),
        Lit::Str(s) => {
            out.push('"');
            out.push_str(&s.value());
            out.push('"');
        }
        _ => out.push('?'),
    }
}

/// `domain.method(t0,t1,...)` for handler selectors.
pub fn build_method_signature(domain: &str, method: &str, args: &[Type]) -> String {
    let mut s = String::new();
    s.push_str(domain);
    s.push('.');
    s.push_str(method);
    s.push('(');
    let mut first = true;
    for ty in args {
        if !first {
            s.push(',');
        }
        first = false;
        render_type(&mut s, ty);
    }
    s.push(')');
    s
}

/// Manifest label for a single type — same canonical form as
/// `render_type`, used to populate `inputs[].ty`, `outputs[].ty`,
/// `events.fields[].ty`, etc., so a manifest reader sees the same string
/// the selector signature was hashed from.
pub fn type_label(ty: &Type) -> String {
    let mut s = String::new();
    render_type(&mut s, ty);
    s
}
