/// Build script for bloom-dex-abi.
///
/// Computes all 4-byte BLAKE3 selectors from the canonical method strings
/// defined in DEX spec §4.1 and emits them as a Rust source file that
/// `src/selectors.rs` includes via `include!(concat!(env!("OUT_DIR"), ...))`.
///
/// Using a build script avoids the "blake3::hash is not const fn" limitation
/// while keeping selectors usable as `pub const` in the library.

use std::env;
use std::fs;
use std::path::Path;

fn selector(method: &str) -> [u8; 4] {
    let h = blake3::hash(method.as_bytes());
    let b = h.as_bytes();
    [b[0], b[1], b[2], b[3]]
}

fn arr_literal(s: [u8; 4]) -> String {
    format!("[0x{:02x}, 0x{:02x}, 0x{:02x}, 0x{:02x}]", s[0], s[1], s[2], s[3])
}

fn main() {
    // All canonical method strings from DEX spec §4.1, grouped by petal.
    let methods: &[(&str, &str)] = &[
        // ERC-20 / LP token
        ("ERC20_TOTAL_SUPPLY",        "erc20.total_supply()"),
        ("ERC20_BALANCE_OF",          "erc20.balance_of(address)"),
        ("ERC20_ALLOWANCE",           "erc20.allowance(address,address)"),
        ("ERC20_TRANSFER",            "erc20.transfer(address,u256)"),
        ("ERC20_TRANSFER_FROM",       "erc20.transfer_from(address,address,u256)"),
        ("ERC20_APPROVE",             "erc20.approve(address,u256)"),
        ("ERC20_NAME",                "erc20.name()"),
        ("ERC20_SYMBOL",              "erc20.symbol()"),
        ("ERC20_DECIMALS",            "erc20.decimals()"),
        // Pair
        ("PAIR_TOKEN0",               "pair.token0()"),
        ("PAIR_TOKEN1",               "pair.token1()"),
        ("PAIR_GET_RESERVES",         "pair.get_reserves()"),
        ("PAIR_MINT",                 "pair.mint(address)"),
        ("PAIR_BURN",                 "pair.burn(address)"),
        ("PAIR_SWAP",                 "pair.swap(u256,u256,address)"),
        ("PAIR_SKIM",                 "pair.skim(address)"),
        ("PAIR_SYNC",                 "pair.sync()"),
        // Factory
        ("FACTORY_CREATE_PAIR",       "factory.create_pair(address,address)"),
        ("FACTORY_GET_PAIR",          "factory.get_pair(address,address)"),
        ("FACTORY_ALL_PAIRS",         "factory.all_pairs(u64)"),
        ("FACTORY_ALL_PAIRS_LENGTH",  "factory.all_pairs_length()"),
        // Router
        ("ROUTER_ADD_LIQUIDITY",              "router.add_liquidity(address,address,u256,u256,u256,u256,address,u64)"),
        ("ROUTER_ADD_LIQUIDITY_LOOM",         "router.add_liquidity_loom(address,u256,u256,u256,address,u64)"),
        ("ROUTER_REMOVE_LIQUIDITY",           "router.remove_liquidity(address,address,u256,u256,u256,address,u64)"),
        ("ROUTER_REMOVE_LIQUIDITY_LOOM",      "router.remove_liquidity_loom(address,u256,u256,u256,address,u64)"),
        ("ROUTER_SWAP_EXACT_TOKENS_FOR_TOKENS","router.swap_exact_tokens_for_tokens(u256,u256,Vec<Address>,address,u64)"),
        ("ROUTER_SWAP_TOKENS_FOR_EXACT_TOKENS","router.swap_tokens_for_exact_tokens(u256,u256,Vec<Address>,address,u64)"),
        ("ROUTER_SWAP_EXACT_LOOM_FOR_TOKENS", "router.swap_exact_loom_for_tokens(u256,Vec<Address>,address,u64)"),
        ("ROUTER_SWAP_TOKENS_FOR_EXACT_LOOM", "router.swap_tokens_for_exact_loom(u256,u256,Vec<Address>,address,u64)"),
        ("ROUTER_SWAP_EXACT_TOKENS_FOR_LOOM", "router.swap_exact_tokens_for_loom(u256,u256,Vec<Address>,address,u64)"),
        ("ROUTER_SWAP_LOOM_FOR_EXACT_TOKENS", "router.swap_loom_for_exact_tokens(u256,Vec<Address>,address,u64)"),
        // Router quoting (pure)
        ("ROUTER_QUOTE",                      "router.quote(u256,u256,u256)"),
        ("ROUTER_GET_AMOUNT_OUT",             "router.get_amount_out(u256,u256,u256)"),
        ("ROUTER_GET_AMOUNT_IN",              "router.get_amount_in(u256,u256,u256)"),
        ("ROUTER_GET_AMOUNTS_OUT",            "router.get_amounts_out(u256,Vec<Address>)"),
        ("ROUTER_GET_AMOUNTS_IN",             "router.get_amounts_in(u256,Vec<Address>)"),
        // Wrapped LOOM
        ("WLOOM_DEPOSIT",             "wloom.deposit()"),
        ("WLOOM_WITHDRAW",            "wloom.withdraw(u256)"),
        // Reentrancy guard
        ("REENTRANCY_ENTER",          "reentrancy.enter(address,bytes)"),
        // Pair internal selectors (callable only by reentrancy petal)
        ("PAIR_LOCK_CHECK_AND_SET",   "pair.lock_check_and_set()"),
        ("PAIR_LOCK_CLEAR",           "pair.lock_clear()"),
        ("PAIR_MINT_INNER",           "pair._mint_inner(address)"),
        ("PAIR_BURN_INNER",           "pair._burn_inner(address)"),
        ("PAIR_SWAP_INNER",           "pair._swap_inner(u256,u256,address)"),
    ];

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs — do not edit.\n");
    out.push_str("// Selectors are the first 4 bytes of blake3(method_string).\n\n");

    for (name, method) in methods {
        let sel = selector(method);
        out.push_str(&format!(
            "/// Selector for `{method}`\n\
             pub const {name}: [u8; 4] = {lit};\n\n",
            method = method,
            name = name,
            lit = arr_literal(sel),
        ));
    }

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("selectors_generated.rs");
    fs::write(dest, out).unwrap();

    // Also emit event topic constants (§10 — 4-byte BLAKE3 prefixes of event sigs).
    let events: &[(&str, &str)] = &[
        ("ERC20_TRANSFER_EVENT",    "Transfer(address,address,u256)"),
        ("ERC20_APPROVAL_EVENT",    "Approval(address,address,u256)"),
        ("PAIR_MINT_EVENT",         "Mint(address,u256,u256)"),
        ("PAIR_BURN_EVENT",         "Burn(address,u256,u256,address)"),
        ("PAIR_SWAP_EVENT",         "Swap(address,u256,u256,u256,u256,address)"),
        ("PAIR_SYNC_EVENT",         "Sync(u128,u128)"),
        ("FACTORY_PAIR_CREATED_EVENT", "PairCreated(address,address,address,u64)"),
    ];

    let mut ev_out = String::new();
    ev_out.push_str("// Auto-generated by build.rs — do not edit.\n");
    ev_out.push_str("// Event topic prefixes are the first 4 bytes of blake3(event_signature).\n\n");

    for (name, sig) in events {
        let sel = selector(sig);
        ev_out.push_str(&format!(
            "/// Topic prefix for event `{sig}`\n\
             pub const {name}: [u8; 4] = {lit};\n\n",
            sig = sig,
            name = name,
            lit = arr_literal(sel),
        ));
    }

    let ev_dest = Path::new(&out_dir).join("events_generated.rs");
    fs::write(ev_dest, ev_out).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
}
